import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-stackit). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as Redacted from "effect/Redacted";
import { UnknownStackitError } from "../errors.ts";
import { StackitProtocol, type StackitOpError, type StackitOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { StackitOpError, StackitOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export type CreateIntakeRequestRegionId = "eu01" | "eu02";
export const CreateIntakeRequestRegionId = S.String;

export interface DremioAuth {
  /** A Dremio personal access token for authentication */
  personalAccessToken: string;
  /** The URL to the Dremio instance's OAuth 2.0 token endpoint */
  tokenEndpoint: string;
}
export const DremioAuth = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    personalAccessToken: S.String,
    tokenEndpoint: S.String,
  }),
).annotate({ identifier: "DremioAuth" }) as any as S.Schema<DremioAuth>;

/** Means of authentication for catalog requests */
export type CatalogAuthType = "none" | "dremio";
export const CatalogAuthType = S.String;

/** Configures authentication for the Iceberg catalog */
export interface CatalogAuth {
  dremio?: DremioAuth;
  type: CatalogAuthType | (string & {});
}
export const CatalogAuth = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    dremio: S.optional(DremioAuth),
    type: CatalogAuthType,
  }),
).annotate({ identifier: "CatalogAuth" }) as any as S.Schema<CatalogAuth>;

/** List of Iceberg partitioning expressions to use when creating the target table. This setting can only be used when `partitioning` is set to `manual`. Partitioning configuration of an Intake can be changed after creation, but will only take effect once the table has been changed as well. In case of not updating the table to a new one, the old partitioning configuration will remain. See the [Apache Iceberg spec](https://iceberg.apache.org/spec/#partitioning) for more details. */
export type IntakeCatalogPartitionByList = Array<string>;
export const IntakeCatalogPartitionByList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<IntakeCatalogPartitionByList>;

/** The target table's partitioning. * `none` disables partitioning, the default. * `intake-time` configures daily partitioning based on the automatically created ingestion time column `__intake_ts`. * `manual` allows arbitrary Iceberg partitioning expression to be set via `partitionBy`. */
export type PartitioningType = "none" | "intake-time" | "manual";
export const PartitioningType = S.String;

/** The Iceberg catalog configuration */
export interface IntakeCatalog {
  auth?: CatalogAuth;
  /** The namespace to which data shall be written. It will be automatically created, if it does not exist. */
  namespace?: string;
  /** List of Iceberg partitioning expressions to use when creating the target table. This setting can only be used when `partitioning` is set to `manual`. Partitioning configuration of an Intake can be changed after creation, but will only take effect once the table has been changed as well. In case of not updating the table to a new one, the old partitioning configuration will remain. See the [Apache Iceberg spec](https://iceberg.apache.org/spec/#partitioning) for more details. */
  partitionBy?: IntakeCatalogPartitionByList | null;
  partitioning?: PartitioningType | (string & {});
  /** The table name is a short name chosen by the user to identify the table in Iceberg. */
  tableName?: string;
  /** The URI to the Iceberg catalog endpoint */
  uri: string;
  /** The Iceberg warehouse to connect to, required when the catalog has no default warehouse configured. */
  warehouse: string;
}
export const IntakeCatalog = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    auth: S.optional(CatalogAuth),
    namespace: S.optional(S.String),
    partitionBy: S.optional(S.NullOr(IntakeCatalogPartitionByList)),
    partitioning: S.optional(PartitioningType),
    tableName: S.optional(S.String),
    uri: S.String,
    warehouse: S.String,
  }),
).annotate({ identifier: "IntakeCatalog" }) as any as S.Schema<IntakeCatalog>;

/** Labels are a set of key-value pairs assigned to resources. */
export type CreateIntakeRequestLabelsMap = { [key: string]: string | undefined };
export const CreateIntakeRequestLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateIntakeRequestLabelsMap>;

export interface CreateIntakeRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: CreateIntakeRequestRegionId | (string & {});
  catalog: IntakeCatalog;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName: string;
  /** The unique id of the intake runner this intake should run on. */
  intakeRunnerId: string;
  /** Labels are a set of key-value pairs assigned to resources. */
  labels?: CreateIntakeRequestLabelsMap | null;
}
export const CreateIntakeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: CreateIntakeRequestRegionId.pipe(T.Label()),
    catalog: IntakeCatalog,
    description: S.optional(S.String),
    displayName: S.String,
    intakeRunnerId: S.String,
    labels: S.optional(S.NullOr(CreateIntakeRequestLabelsMap)),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "CreateIntakeRequest" }) as any as S.Schema<CreateIntakeRequest>;

/** Labels are a set of key-value pairs assigned to resources. */
export type IntakeResponseLabelsMap = { [key: string]: string | undefined };
export const IntakeResponseLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<IntakeResponseLabelsMap>;

/** The current state of the resource. */
export type IntakeResponseState = "reconciling" | "active" | "deleting" | "failed";
export const IntakeResponseState = S.String;

export interface IntakeResponse {
  catalog: IntakeCatalog;
  /** The point in time the resource was created. */
  create_time: string;
  /** The topic where undelivered messages are published (Dead Letter Queue). */
  deadLetterTopic: string;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName: string;
  /** A human-readable description of the error, if the state is 'failed'. */
  failure_message?: string;
  /** A auto generated unique id which identifies the resource. */
  id: string;
  /** The unique id of the intake runner this intake is running on. */
  intakeRunnerId: string;
  /** Labels are a set of key-value pairs assigned to resources. */
  labels?: IntakeResponseLabelsMap | null;
  /** The current state of the resource. */
  state: IntakeResponseState;
  /** The topic to publish data to. */
  topic: string;
  /** Number of messages that failed delivery and were sent to the Dead Letter Queue. */
  undeliveredMessageCount?: number;
  /** The URI for reaching the resource. */
  uri: string;
}
export const IntakeResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    catalog: IntakeCatalog,
    create_time: S.String,
    deadLetterTopic: S.String,
    description: S.optional(S.String),
    displayName: S.String,
    failure_message: S.optional(S.String),
    id: S.String,
    intakeRunnerId: S.String,
    labels: S.optional(S.NullOr(IntakeResponseLabelsMap)),
    state: IntakeResponseState,
    topic: S.String,
    undeliveredMessageCount: S.optional(S.Number),
    uri: S.String,
  }),
).annotate({ identifier: "IntakeResponse" }) as any as S.Schema<IntakeResponse>;

export type CreateIntakeRunnerRequestRegionId = "eu01" | "eu02";
export const CreateIntakeRunnerRequestRegionId = S.String;

/** Labels are a set of key-value pairs assigned to resources. */
export type CreateIntakeRunnerRequestLabelsMap = { [key: string]: string | undefined };
export const CreateIntakeRunnerRequestLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateIntakeRunnerRequestLabelsMap>;

export interface CreateIntakeRunnerRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: CreateIntakeRunnerRequestRegionId | (string & {});
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName: string;
  /** Labels are a set of key-value pairs assigned to resources. */
  labels?: CreateIntakeRunnerRequestLabelsMap | null;
  /** The maximum size of a message in kibibytes (1 KiB = 1024 bytes). */
  maxMessageSizeKiB: number;
  /** The maximum number of messages per hour. */
  maxMessagesPerHour: number;
}
export const CreateIntakeRunnerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: CreateIntakeRunnerRequestRegionId.pipe(T.Label()),
    description: S.optional(S.String),
    displayName: S.String,
    labels: S.optional(S.NullOr(CreateIntakeRunnerRequestLabelsMap)),
    maxMessageSizeKiB: S.Number,
    maxMessagesPerHour: S.Number,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intake-runners",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({
  identifier: "CreateIntakeRunnerRequest",
}) as any as S.Schema<CreateIntakeRunnerRequest>;

/** Labels are a set of key-value pairs assigned to resources. */
export type IntakeRunnerResponseLabelsMap = { [key: string]: string | undefined };
export const IntakeRunnerResponseLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<IntakeRunnerResponseLabelsMap>;

/** The current state of the resource. */
export type IntakeRunnerResponseState = "reconciling" | "active" | "deleting";
export const IntakeRunnerResponseState = S.String;

export interface IntakeRunnerResponse {
  /** The point in time the resource was created. */
  create_time: string;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName: string;
  /** A auto generated unique id which identifies the resource. */
  id: string;
  /** Labels are a set of key-value pairs assigned to resources. */
  labels?: IntakeRunnerResponseLabelsMap | null;
  /** The maximum size of a message in kibibytes (1 KiB = 1024 bytes). */
  maxMessageSizeKiB: number;
  /** The maximum number of messages per hour. */
  maxMessagesPerHour: number;
  /** The current state of the resource. */
  state: IntakeRunnerResponseState;
  /** The URI for reaching the resource. */
  uri: string;
}
export const IntakeRunnerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    create_time: S.String,
    description: S.optional(S.String),
    displayName: S.String,
    id: S.String,
    labels: S.optional(S.NullOr(IntakeRunnerResponseLabelsMap)),
    maxMessageSizeKiB: S.Number,
    maxMessagesPerHour: S.Number,
    state: IntakeRunnerResponseState,
    uri: S.String,
  }),
).annotate({ identifier: "IntakeRunnerResponse" }) as any as S.Schema<IntakeRunnerResponse>;

export type CreateIntakeUserRequestRegionId = "eu01" | "eu02";
export const CreateIntakeUserRequestRegionId = S.String;

/** Labels are key-value pairs associated with the resource. */
export type CreateIntakeUserRequestLabelsMap = { [key: string]: string | undefined };
export const CreateIntakeUserRequestLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateIntakeUserRequestLabelsMap>;

/** Type of user, 'intake' allows writing to the Intake, 'dead-letter' allows reading from the dead-letter queue */
export type UserType = "intake" | "dead-letter";
export const UserType = S.String;

export interface CreateIntakeUserRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: CreateIntakeUserRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName: string;
  /** Labels are key-value pairs associated with the resource. */
  labels?: CreateIntakeUserRequestLabelsMap | null;
  /** A password chosen by the user. The password must consist of at least of each of these categories: * lower case letter * upper case letter * number * other character */
  password: string | Redacted.Redacted<string>;
  type?: UserType | (string & {});
}
export const CreateIntakeUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: CreateIntakeUserRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
    displayName: S.String,
    labels: S.optional(S.NullOr(CreateIntakeUserRequestLabelsMap)),
    password: S.String.pipe(T.SensitiveValue({})),
    type: S.optional(UserType),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}/users",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "CreateIntakeUserRequest" }) as any as S.Schema<CreateIntakeUserRequest>;

/** Configuration properties for supported clients. */
export interface ClientConfig {
  /** Configuration for Java Kafka clients. */
  java: string;
  /** Configuration for Kafka clients using librdkafka */
  librdkafka: string;
}
export const ClientConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    java: S.String,
    librdkafka: S.String,
  }),
).annotate({ identifier: "ClientConfig" }) as any as S.Schema<ClientConfig>;

/** Labels are a set of key-value pairs assigned to resources. */
export type IntakeUserResponseLabelsMap = { [key: string]: string | undefined };
export const IntakeUserResponseLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<IntakeUserResponseLabelsMap>;

/** The current state of the resource. */
export type IntakeUserResponseState = "reconciling" | "active" | "deleting";
export const IntakeUserResponseState = S.String;

export interface IntakeUserResponse {
  clientConfig?: ClientConfig;
  /** The point in time the resource was created. */
  create_time: string;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName: string;
  /** A auto generated unique id which identifies the resource. */
  id: string;
  /** Labels are a set of key-value pairs assigned to resources. */
  labels?: IntakeUserResponseLabelsMap | null;
  /** The current state of the resource. */
  state: IntakeUserResponseState;
  type: UserType;
  /** The user to connect to the intake. */
  user: string;
}
export const IntakeUserResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clientConfig: S.optional(ClientConfig),
    create_time: S.String,
    description: S.optional(S.String),
    displayName: S.String,
    id: S.String,
    labels: S.optional(S.NullOr(IntakeUserResponseLabelsMap)),
    state: IntakeUserResponseState,
    type: UserType,
    user: S.String,
  }),
).annotate({ identifier: "IntakeUserResponse" }) as any as S.Schema<IntakeUserResponse>;

export type DeleteIntakeRequestRegionId = "eu01" | "eu02";
export const DeleteIntakeRequestRegionId = S.String;

export interface DeleteIntakeRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: DeleteIntakeRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  /** If true, deletes all child resources. If false, the resource remains in a 'deletion state' while child resources exist. */
  force?: boolean;
}
export const DeleteIntakeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: DeleteIntakeRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    force: S.optional(S.Boolean.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "DeleteIntakeRequest" }) as any as S.Schema<DeleteIntakeRequest>;

export interface DeleteIntakeResponse {}
export const DeleteIntakeResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteIntakeResponse",
}) as any as S.Schema<DeleteIntakeResponse>;

export type DeleteIntakeRunnerRequestRegionId = "eu01" | "eu02";
export const DeleteIntakeRunnerRequestRegionId = S.String;

export interface DeleteIntakeRunnerRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: DeleteIntakeRunnerRequestRegionId | (string & {});
  /** The intake runner UUID. */
  intakeRunnerId: string;
  /** If true, deletes all child resources. If false, the resource remains in a 'deletion state' while child resources exist. */
  force?: boolean;
}
export const DeleteIntakeRunnerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: DeleteIntakeRunnerRequestRegionId.pipe(T.Label()),
    intakeRunnerId: S.String.pipe(T.Label()),
    force: S.optional(S.Boolean.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intake-runners/{intakeRunnerId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({
  identifier: "DeleteIntakeRunnerRequest",
}) as any as S.Schema<DeleteIntakeRunnerRequest>;

export interface DeleteIntakeRunnerResponse {}
export const DeleteIntakeRunnerResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteIntakeRunnerResponse",
}) as any as S.Schema<DeleteIntakeRunnerResponse>;

export type DeleteIntakeUserRequestRegionId = "eu01" | "eu02";
export const DeleteIntakeUserRequestRegionId = S.String;

export interface DeleteIntakeUserRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: DeleteIntakeUserRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  /** The intake user UUID. */
  intakeUserId: string;
}
export const DeleteIntakeUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: DeleteIntakeUserRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    intakeUserId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}/users/{intakeUserId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "DeleteIntakeUserRequest" }) as any as S.Schema<DeleteIntakeUserRequest>;

export interface DeleteIntakeUserResponse {}
export const DeleteIntakeUserResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteIntakeUserResponse",
}) as any as S.Schema<DeleteIntakeUserResponse>;

export type GetIntakeRequestRegionId = "eu01" | "eu02";
export const GetIntakeRequestRegionId = S.String;

export interface GetIntakeRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: GetIntakeRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
}
export const GetIntakeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: GetIntakeRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetIntakeRequest" }) as any as S.Schema<GetIntakeRequest>;

export type GetIntakeRunnerRequestRegionId = "eu01" | "eu02";
export const GetIntakeRunnerRequestRegionId = S.String;

export interface GetIntakeRunnerRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: GetIntakeRunnerRequestRegionId | (string & {});
  /** The intake runner UUID. */
  intakeRunnerId: string;
}
export const GetIntakeRunnerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: GetIntakeRunnerRequestRegionId.pipe(T.Label()),
    intakeRunnerId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intake-runners/{intakeRunnerId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetIntakeRunnerRequest" }) as any as S.Schema<GetIntakeRunnerRequest>;

export type GetIntakeUserRequestRegionId = "eu01" | "eu02";
export const GetIntakeUserRequestRegionId = S.String;

export interface GetIntakeUserRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: GetIntakeUserRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  /** The intake user UUID. */
  intakeUserId: string;
}
export const GetIntakeUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: GetIntakeUserRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    intakeUserId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}/users/{intakeUserId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetIntakeUserRequest" }) as any as S.Schema<GetIntakeUserRequest>;

export type ListIntakeRunnersRequestRegionId = "eu01" | "eu02";
export const ListIntakeRunnersRequestRegionId = S.String;

export interface ListIntakeRunnersRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: ListIntakeRunnersRequestRegionId | (string & {});
  /** A token to retrieve the next page of results. */
  pageToken?: string;
  /** Maximum number of items to return */
  pageSize?: number;
}
export const ListIntakeRunnersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: ListIntakeRunnersRequestRegionId.pipe(T.Label()),
    pageToken: S.optional(S.String.pipe(T.Query())),
    pageSize: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intake-runners",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "ListIntakeRunnersRequest" }) as any as S.Schema<ListIntakeRunnersRequest>;

export type ListIntakeRunnersResponseIntakeRunnersList = Array<IntakeRunnerResponse>;
export const ListIntakeRunnersResponseIntakeRunnersList = /*@__PURE__*/ S.Array(
  IntakeRunnerResponse,
) as any as S.Schema<ListIntakeRunnersResponseIntakeRunnersList>;

export interface ListIntakeRunnersResponse {
  intakeRunners: ListIntakeRunnersResponseIntakeRunnersList;
  /** A token to retrieve the next page of results. */
  nextPageToken?: string;
}
export const ListIntakeRunnersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    intakeRunners: ListIntakeRunnersResponseIntakeRunnersList,
    nextPageToken: S.optional(S.String),
  }),
).annotate({
  identifier: "ListIntakeRunnersResponse",
}) as any as S.Schema<ListIntakeRunnersResponse>;

export type ListIntakesRequestRegionId = "eu01" | "eu02";
export const ListIntakesRequestRegionId = S.String;

export interface ListIntakesRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: ListIntakesRequestRegionId | (string & {});
  /** A token to retrieve the next page of results. */
  pageToken?: string;
  /** Maximum number of items to return */
  pageSize?: number;
}
export const ListIntakesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: ListIntakesRequestRegionId.pipe(T.Label()),
    pageToken: S.optional(S.String.pipe(T.Query())),
    pageSize: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "ListIntakesRequest" }) as any as S.Schema<ListIntakesRequest>;

export type ListIntakesResponseIntakesList = Array<IntakeResponse>;
export const ListIntakesResponseIntakesList = /*@__PURE__*/ S.Array(
  IntakeResponse,
) as any as S.Schema<ListIntakesResponseIntakesList>;

export interface ListIntakesResponse {
  intakes: ListIntakesResponseIntakesList;
  /** A token to retrieve the next page of results. */
  nextPageToken?: string;
}
export const ListIntakesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    intakes: ListIntakesResponseIntakesList,
    nextPageToken: S.optional(S.String),
  }),
).annotate({ identifier: "ListIntakesResponse" }) as any as S.Schema<ListIntakesResponse>;

export type ListIntakeUsersRequestRegionId = "eu01" | "eu02";
export const ListIntakeUsersRequestRegionId = S.String;

export interface ListIntakeUsersRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: ListIntakeUsersRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  /** A token to retrieve the next page of results. */
  pageToken?: string;
  /** Maximum number of items to return */
  pageSize?: number;
}
export const ListIntakeUsersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: ListIntakeUsersRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    pageToken: S.optional(S.String.pipe(T.Query())),
    pageSize: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}/users",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "ListIntakeUsersRequest" }) as any as S.Schema<ListIntakeUsersRequest>;

export type ListIntakeUsersResponseIntakeUsersList = Array<IntakeUserResponse>;
export const ListIntakeUsersResponseIntakeUsersList = /*@__PURE__*/ S.Array(
  IntakeUserResponse,
) as any as S.Schema<ListIntakeUsersResponseIntakeUsersList>;

export interface ListIntakeUsersResponse {
  intakeUsers: ListIntakeUsersResponseIntakeUsersList;
  /** A token to retrieve the next page of results. */
  nextPageToken?: string;
}
export const ListIntakeUsersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    intakeUsers: ListIntakeUsersResponseIntakeUsersList,
    nextPageToken: S.optional(S.String),
  }),
).annotate({ identifier: "ListIntakeUsersResponse" }) as any as S.Schema<ListIntakeUsersResponse>;

export type UpdateIntakeRequestRegionId = "eu01" | "eu02";
export const UpdateIntakeRequestRegionId = S.String;

export interface DremioAuthPatch {
  /** A Dremio personal access token for authentication */
  personalAccessToken?: string;
  /** The URL to the Dremio instance's OAuth 2.0 token endpoint */
  tokenEndpoint?: string;
}
export const DremioAuthPatch = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    personalAccessToken: S.optional(S.String),
    tokenEndpoint: S.optional(S.String),
  }),
).annotate({ identifier: "DremioAuthPatch" }) as any as S.Schema<DremioAuthPatch>;

/** Configures authentication for the Iceberg catalog */
export interface CatalogAuthPatch {
  dremio?: DremioAuthPatch;
  type?: CatalogAuthType | (string & {});
}
export const CatalogAuthPatch = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    dremio: S.optional(DremioAuthPatch),
    type: S.optional(CatalogAuthType),
  }),
).annotate({ identifier: "CatalogAuthPatch" }) as any as S.Schema<CatalogAuthPatch>;

/** List of Iceberg partitioning expressions to use when creating the target table. This setting can only be used when `partitioning` is set to `manual`. See the [Apache Iceberg spec](https://iceberg.apache.org/spec/#partitioning) for more details. */
export type IntakeCatalogPatchPartitionByList = Array<string>;
export const IntakeCatalogPatchPartitionByList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<IntakeCatalogPatchPartitionByList>;

/** The target table's partitioning. * `none` disables partitioning. * `intake-time` configures daily partitioning based on the automatically created ingestion time column `__intake_ts`. * `manual` allows arbitrary Iceberg partitioning expression to be set via `partitionBy`. */
export type PartitioningUpdateType = "none" | "intake-time" | "manual";
export const PartitioningUpdateType = S.String;

/** The Iceberg catalog configuration */
export interface IntakeCatalogPatch {
  auth?: CatalogAuthPatch;
  /** The namespace to which data shall be written. It will be automatically created, if it does not exist. */
  namespace?: string;
  /** List of Iceberg partitioning expressions to use when creating the target table. This setting can only be used when `partitioning` is set to `manual`. See the [Apache Iceberg spec](https://iceberg.apache.org/spec/#partitioning) for more details. */
  partitionBy?: IntakeCatalogPatchPartitionByList | null;
  partitioning?: PartitioningUpdateType | (string & {});
  /** The table name is a short name chosen by the user to identify the table in Iceberg. */
  tableName?: string;
  /** The URI to the Iceberg catalog endpoint */
  uri?: string;
  /** The Iceberg warehouse to connect to, required when the catalog has no default warehouse configured. */
  warehouse?: string;
}
export const IntakeCatalogPatch = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    auth: S.optional(CatalogAuthPatch),
    namespace: S.optional(S.String),
    partitionBy: S.optional(S.NullOr(IntakeCatalogPatchPartitionByList)),
    partitioning: S.optional(PartitioningUpdateType),
    tableName: S.optional(S.String),
    uri: S.optional(S.String),
    warehouse: S.optional(S.String),
  }),
).annotate({ identifier: "IntakeCatalogPatch" }) as any as S.Schema<IntakeCatalogPatch>;

/** Labels are key-value pairs associated with the resource. To update labels: - Provide a new set of key-value pairs to replace the existing labels. - Send empty object `{}` to remove all labels. - Omit this field to leave the labels unchanged. */
export type UpdateIntakeRequestLabelsMap = { [key: string]: string | undefined };
export const UpdateIntakeRequestLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<UpdateIntakeRequestLabelsMap>;

export interface UpdateIntakeRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: UpdateIntakeRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  catalog?: IntakeCatalogPatch;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName?: string;
  /** The unique id of the intake runner this intake should run on. */
  intakeRunnerId: string;
  /** Labels are key-value pairs associated with the resource. To update labels: - Provide a new set of key-value pairs to replace the existing labels. - Send empty object `{}` to remove all labels. - Omit this field to leave the labels unchanged. */
  labels?: UpdateIntakeRequestLabelsMap | null;
}
export const UpdateIntakeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: UpdateIntakeRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    catalog: S.optional(IntakeCatalogPatch),
    description: S.optional(S.String),
    displayName: S.optional(S.String),
    intakeRunnerId: S.String,
    labels: S.optional(S.NullOr(UpdateIntakeRequestLabelsMap)),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateIntakeRequest" }) as any as S.Schema<UpdateIntakeRequest>;

export type UpdateIntakeRunnerRequestRegionId = "eu01" | "eu02";
export const UpdateIntakeRunnerRequestRegionId = S.String;

/** Labels are key-value pairs associated with the resource. To update labels: - Provide a new set of key-value pairs to replace the existing labels. - Send empty object `{}` to remove all labels. - Omit this field to leave the labels unchanged. */
export type UpdateIntakeRunnerRequestLabelsMap = { [key: string]: string | undefined };
export const UpdateIntakeRunnerRequestLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<UpdateIntakeRunnerRequestLabelsMap>;

export interface UpdateIntakeRunnerRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: UpdateIntakeRunnerRequestRegionId | (string & {});
  /** The intake runner UUID. */
  intakeRunnerId: string;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName?: string;
  /** Labels are key-value pairs associated with the resource. To update labels: - Provide a new set of key-value pairs to replace the existing labels. - Send empty object `{}` to remove all labels. - Omit this field to leave the labels unchanged. */
  labels?: UpdateIntakeRunnerRequestLabelsMap | null;
  /** The maximum size of a message in kibibytes (1 KiB = 1024 bytes). */
  maxMessageSizeKiB?: number;
  /** The maximum number of messages per hour. */
  maxMessagesPerHour?: number;
}
export const UpdateIntakeRunnerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: UpdateIntakeRunnerRequestRegionId.pipe(T.Label()),
    intakeRunnerId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
    displayName: S.optional(S.String),
    labels: S.optional(S.NullOr(UpdateIntakeRunnerRequestLabelsMap)),
    maxMessageSizeKiB: S.optional(S.Number),
    maxMessagesPerHour: S.optional(S.Number),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intake-runners/{intakeRunnerId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({
  identifier: "UpdateIntakeRunnerRequest",
}) as any as S.Schema<UpdateIntakeRunnerRequest>;

export type UpdateIntakeUserRequestRegionId = "eu01" | "eu02";
export const UpdateIntakeUserRequestRegionId = S.String;

/** Labels are key-value pairs associated with the resource. To update labels: - Provide a new set of key-value pairs to replace the existing labels. - Send empty object `{}` to remove all labels. - Omit this field to leave the labels unchanged. */
export type UpdateIntakeUserRequestLabelsMap = { [key: string]: string | undefined };
export const UpdateIntakeUserRequestLabelsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<UpdateIntakeUserRequestLabelsMap>;

export interface UpdateIntakeUserRequest {
  /** The STACKIT portal project UUID the resource is located in. */
  projectId: string;
  /** The STACKIT region name the resource is located in. */
  regionId: UpdateIntakeUserRequestRegionId | (string & {});
  /** The intake UUID. */
  intakeId: string;
  /** The intake user UUID. */
  intakeUserId: string;
  /** The description is a longer text chosen by the user to provide more context for the resource. */
  description?: string;
  /** The display name is a short name chosen by the user to identify the resource. */
  displayName?: string;
  /** Labels are key-value pairs associated with the resource. To update labels: - Provide a new set of key-value pairs to replace the existing labels. - Send empty object `{}` to remove all labels. - Omit this field to leave the labels unchanged. */
  labels?: UpdateIntakeUserRequestLabelsMap | null;
  /** A password chosen by the user. */
  password?: string | Redacted.Redacted<string>;
  type?: UserType | (string & {});
}
export const UpdateIntakeUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    regionId: UpdateIntakeUserRequestRegionId.pipe(T.Label()),
    intakeId: S.String.pipe(T.Label()),
    intakeUserId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
    displayName: S.optional(S.String),
    labels: S.optional(S.NullOr(UpdateIntakeUserRequestLabelsMap)),
    password: S.optional(S.String.pipe(T.SensitiveValue({}))),
    type: S.optional(UserType),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1beta/projects/{projectId}/regions/{regionId}/intakes/{intakeId}/users/{intakeUserId}",
      code: 200,
      baseUrl: "https://intake.api.stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateIntakeUserRequest" }) as any as S.Schema<UpdateIntakeUserRequest>;

export type CreateIntakeError = BadRequest | Conflict | StackitOpError;
/** Creates a new intake within the project. */
export const createIntake: API.OperationMethod<
  CreateIntakeRequest,
  IntakeResponse,
  CreateIntakeError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateIntakeRequest,
  output: IntakeResponse,
  errors: [BadRequest, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type CreateIntakeRunnerError = BadRequest | Conflict | StackitOpError;
/** Creates a new intake runner within the project. */
export const createIntakeRunner: API.OperationMethod<
  CreateIntakeRunnerRequest,
  IntakeRunnerResponse,
  CreateIntakeRunnerError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateIntakeRunnerRequest,
  output: IntakeRunnerResponse,
  errors: [BadRequest, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type CreateIntakeUserError = BadRequest | Conflict | StackitOpError;
/** Creates a new user for this intake. */
export const createIntakeUser: API.OperationMethod<
  CreateIntakeUserRequest,
  IntakeUserResponse,
  CreateIntakeUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateIntakeUserRequest,
  output: IntakeUserResponse,
  errors: [BadRequest, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteIntakeError = NotFound | Conflict | StackitOpError;
/** Deletes the given intake. */
export const deleteIntake: API.OperationMethod<
  DeleteIntakeRequest,
  DeleteIntakeResponse,
  DeleteIntakeError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteIntakeRequest,
  output: DeleteIntakeResponse,
  errors: [NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteIntakeRunnerError = NotFound | Conflict | StackitOpError;
/** Deletes the given intake runner. */
export const deleteIntakeRunner: API.OperationMethod<
  DeleteIntakeRunnerRequest,
  DeleteIntakeRunnerResponse,
  DeleteIntakeRunnerError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteIntakeRunnerRequest,
  output: DeleteIntakeRunnerResponse,
  errors: [NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteIntakeUserError = NotFound | Conflict | StackitOpError;
/** Deletes the given intake user. */
export const deleteIntakeUser: API.OperationMethod<
  DeleteIntakeUserRequest,
  DeleteIntakeUserResponse,
  DeleteIntakeUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteIntakeUserRequest,
  output: DeleteIntakeUserResponse,
  errors: [NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetIntakeError = NotFound | StackitOpError;
/** Returns the details for the given intake. */
export const getIntake: API.OperationMethod<
  GetIntakeRequest,
  IntakeResponse,
  GetIntakeError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetIntakeRequest,
  output: IntakeResponse,
  errors: [NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetIntakeRunnerError = NotFound | StackitOpError;
/** Returns the details for the given intake runner. */
export const getIntakeRunner: API.OperationMethod<
  GetIntakeRunnerRequest,
  IntakeRunnerResponse,
  GetIntakeRunnerError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetIntakeRunnerRequest,
  output: IntakeRunnerResponse,
  errors: [NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetIntakeUserError = NotFound | StackitOpError;
/** Returns the details for the given user. */
export const getIntakeUser: API.OperationMethod<
  GetIntakeUserRequest,
  IntakeUserResponse,
  GetIntakeUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetIntakeUserRequest,
  output: IntakeUserResponse,
  errors: [NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type ListIntakeRunnersError = StackitOpError;
/** Returns a list of all intake runners within the project. */
export const listIntakeRunners: API.OperationMethod<
  ListIntakeRunnersRequest,
  ListIntakeRunnersResponse,
  ListIntakeRunnersError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListIntakeRunnersRequest,
  output: ListIntakeRunnersResponse,
  errors: [UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type ListIntakesError = StackitOpError;
/** Returns a list of all intakes within the project. */
export const listIntakes: API.OperationMethod<
  ListIntakesRequest,
  ListIntakesResponse,
  ListIntakesError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListIntakesRequest,
  output: ListIntakesResponse,
  errors: [UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type ListIntakeUsersError = StackitOpError;
/** Returns a list of all intake users within the project and intake. */
export const listIntakeUsers: API.OperationMethod<
  ListIntakeUsersRequest,
  ListIntakeUsersResponse,
  ListIntakeUsersError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListIntakeUsersRequest,
  output: ListIntakeUsersResponse,
  errors: [UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateIntakeError = NotFound | Conflict | StackitOpError;
/** Updates the given intake. */
export const updateIntake: API.OperationMethod<
  UpdateIntakeRequest,
  IntakeResponse,
  UpdateIntakeError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateIntakeRequest,
  output: IntakeResponse,
  errors: [NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateIntakeRunnerError = BadRequest | Conflict | StackitOpError;
/** Updates a intake runner within the project. */
export const updateIntakeRunner: API.OperationMethod<
  UpdateIntakeRunnerRequest,
  IntakeRunnerResponse,
  UpdateIntakeRunnerError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateIntakeRunnerRequest,
  output: IntakeRunnerResponse,
  errors: [BadRequest, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateIntakeUserError = NotFound | Conflict | StackitOpError;
/** Updates the given intake user. */
export const updateIntakeUser: API.OperationMethod<
  UpdateIntakeUserRequest,
  IntakeUserResponse,
  UpdateIntakeUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateIntakeUserRequest,
  output: IntakeUserResponse,
  errors: [NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));
