import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-stackit). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as Redacted from "effect/Redacted";
import { UnknownStackitError } from "../errors.ts";
import { StackitProtocol, type StackitOpError, type StackitOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { StackitOpError, StackitOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export interface CreateACLRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The given IP/IP Range that is permitted to access. */
  cidr: string;
}
export const CreateACLRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    cidr: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/acls",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "CreateACLRequest" }) as any as S.Schema<CreateACLRequest>;

export interface ACL {
  /** The given IP/IP Range that is permitted to access. */
  cidr: string;
  /** A auto generated unique id which identifies the acl. */
  id: string;
}
export const ACL = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cidr: S.String,
    id: S.String,
  }),
).annotate({ identifier: "ACL" }) as any as S.Schema<ACL>;

export interface CreateApproleRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** A user chosen description to differentiate between multiple approles. */
  description?: string;
  secret_id_num_uses?: number;
  /** Token TTL in time.Duration format (eg 15m for 15 minutes, 1h for 1 hour). */
  secret_id_ttl?: string;
  /** Is true if the approle has write access to the secrets engine. Is false for a read-only approle. */
  write?: boolean;
}
export const CreateApproleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
    secret_id_num_uses: S.optional(S.Number),
    secret_id_ttl: S.optional(S.String),
    write: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "CreateApproleRequest" }) as any as S.Schema<CreateApproleRequest>;

export interface Approle {
  /** A user chosen description to differentiate between multiple approles. */
  description: string;
  /** Identifier used for authentication */
  role_id: string;
  secret_id_num_uses: number;
  /** Token TTL in time.Duration format (eg 15m for 15 minutes, 1h for 1 hour). */
  secret_id_ttl: string;
  /** Is true if the approle has write access to the secrets engine. Is false for a read-only approle. */
  write: boolean;
}
export const Approle = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.String,
    role_id: S.String,
    secret_id_num_uses: S.Number,
    secret_id_ttl: S.String,
    write: S.Boolean,
  }),
).annotate({ identifier: "Approle" }) as any as S.Schema<Approle>;

export interface CreateApproleSecretIdRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
  /** A user chosen description to differentiate between multiple approle secrets. */
  description?: string;
}
export const CreateApproleSecretIdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}/secretids",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({
  identifier: "CreateApproleSecretIdRequest",
}) as any as S.Schema<CreateApproleSecretIdRequest>;

export interface ApproleSecret {
  /** A user chosen description to differentiate between multiple approle secrets. */
  description: string;
  num_uses: number;
  /** Identifier used for authentication, returned only at creation */
  secret_id?: string;
  /** Token TTL in time.Duration format (eg 15m for 15 minutes, 1h for 1 hour). */
  ttl: string;
  /** Accessor used for handling secrets */
  version: number;
}
export const ApproleSecret = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.String,
    num_uses: S.Number,
    secret_id: S.optional(S.String),
    ttl: S.String,
    version: S.Number,
  }),
).annotate({ identifier: "ApproleSecret" }) as any as S.Schema<ApproleSecret>;

/** The key for secret encryption and decryption. */
export interface KmsKeyPayload {
  /** The key UUID. */
  keyId: string;
  /** The key ring UUID the key is part of. */
  keyRingId: string;
  /** The Key version number. */
  keyVersion: number;
  /** The Service account email that will consume the key. Must be in the same project as the Secrets Manager instance. */
  serviceAccountEmail: string;
}
export const KmsKeyPayload = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    keyId: S.String,
    keyRingId: S.String,
    keyVersion: S.Number,
    serviceAccountEmail: S.String,
  }),
).annotate({ identifier: "KmsKeyPayload" }) as any as S.Schema<KmsKeyPayload>;

export interface CreateInstanceRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  kmsKey?: KmsKeyPayload;
  /** A user chosen name to distinguish multiple secrets manager instances. */
  name: string;
}
export const CreateInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    kmsKey: S.optional(KmsKeyPayload),
    name: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/projects/{projectId}/instances",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "CreateInstanceRequest" }) as any as S.Schema<CreateInstanceRequest>;

export interface Instance {
  /** The API endpoint for connecting to the secrets engine. */
  apiUrl: string;
  /** The date and time the creation of the Secrets Manager instance was finished. */
  creationFinishedDate?: string;
  /** The date and time the creation of the Secrets Manager instance was triggered. */
  creationStartDate: string;
  /** A auto generated unique id which identifies the secrets manager instances. */
  id: string;
  kmsKey?: KmsKeyPayload;
  /** A user chosen name to distinguish multiple secrets manager instances. */
  name: string;
  /** The number of secrets currently stored inside of the instance. This value will be updated once per hour. */
  secretCount: number;
  /** The name of the secrets engine. */
  secretsEngine: string;
  /** The current state of the Secrets Manager instance. */
  state: string;
  updateFinishedDate?: string;
  updateStartDate?: string;
}
export const Instance = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    apiUrl: S.String,
    creationFinishedDate: S.optional(S.String),
    creationStartDate: S.String,
    id: S.String,
    kmsKey: S.optional(KmsKeyPayload),
    name: S.String,
    secretCount: S.Number,
    secretsEngine: S.String,
    state: S.String,
    updateFinishedDate: S.optional(S.String),
    updateStartDate: S.optional(S.String),
  }),
).annotate({ identifier: "Instance" }) as any as S.Schema<Instance>;

export interface CreateUserRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** A user chosen description to differentiate between multiple users. */
  description: string;
  /** Is true if the user has write access to the secrets engine. Is false for a read-only user. */
  write: boolean;
}
export const CreateUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    description: S.String,
    write: S.Boolean,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/users",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "CreateUserRequest" }) as any as S.Schema<CreateUserRequest>;

export interface User {
  /** A user chosen description to differentiate between multiple users. */
  description: string;
  /** A auto generated unique id which identifies the users. */
  id: string;
  /** A auto generated password for logging in with the user. */
  password: string | Redacted.Redacted<string>;
  /** A auto generated username for logging in with the user. */
  username: string;
  /** Is true if the user has write access to the secrets engine. Is false for a read-only user. */
  write: boolean;
}
export const User = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.String,
    id: S.String,
    password: S.String.pipe(T.SensitiveValue({})),
    username: S.String,
    write: S.Boolean,
  }),
).annotate({ identifier: "User" }) as any as S.Schema<User>;

export interface DeleteACLRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The acl UUID of the Secrets Manager instance. */
  aclId: string;
}
export const DeleteACLRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    aclId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/acls/{aclId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "DeleteACLRequest" }) as any as S.Schema<DeleteACLRequest>;

export interface DeleteACLResponse {}
export const DeleteACLResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteACLResponse",
}) as any as S.Schema<DeleteACLResponse>;

export interface DeleteApproleRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
}
export const DeleteApproleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "DeleteApproleRequest" }) as any as S.Schema<DeleteApproleRequest>;

export interface DeleteApproleResponse {}
export const DeleteApproleResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteApproleResponse",
}) as any as S.Schema<DeleteApproleResponse>;

export interface DeleteApproleSecretIdRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
  /** The version of the secret id. */
  secretIdVersion: number;
}
export const DeleteApproleSecretIdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
    secretIdVersion: S.Number.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}/secretids/{secretIdVersion}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({
  identifier: "DeleteApproleSecretIdRequest",
}) as any as S.Schema<DeleteApproleSecretIdRequest>;

export interface DeleteApproleSecretIdResponse {}
export const DeleteApproleSecretIdResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteApproleSecretIdResponse",
}) as any as S.Schema<DeleteApproleSecretIdResponse>;

export interface DeleteInstanceRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
}
export const DeleteInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/projects/{projectId}/instances/{instanceId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "DeleteInstanceRequest" }) as any as S.Schema<DeleteInstanceRequest>;

export interface DeleteInstanceResponse {}
export const DeleteInstanceResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteInstanceResponse",
}) as any as S.Schema<DeleteInstanceResponse>;

export interface DeleteUserRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The user UUID with permissions on the Secrets Manager instance. */
  userId: string;
}
export const DeleteUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    userId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/users/{userId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "DeleteUserRequest" }) as any as S.Schema<DeleteUserRequest>;

export interface DeleteUserResponse {}
export const DeleteUserResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteUserResponse",
}) as any as S.Schema<DeleteUserResponse>;

export interface GetACLRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The acl UUID of the Secrets Manager instance. */
  aclId: string;
}
export const GetACLRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    aclId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/acls/{aclId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetACLRequest" }) as any as S.Schema<GetACLRequest>;

export interface GetApproleRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
}
export const GetApproleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetApproleRequest" }) as any as S.Schema<GetApproleRequest>;

export interface GetApprolesRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
}
export const GetApprolesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetApprolesRequest" }) as any as S.Schema<GetApprolesRequest>;

export type ApproleListApprolesList = Array<Approle>;
export const ApproleListApprolesList = /*@__PURE__*/ S.Array(
  Approle,
) as any as S.Schema<ApproleListApprolesList>;

export interface ApproleList {
  approles: ApproleListApprolesList;
}
export const ApproleList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    approles: ApproleListApprolesList,
  }),
).annotate({ identifier: "ApproleList" }) as any as S.Schema<ApproleList>;

export interface GetApproleSecretIdRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
  /** The version of the secret id. */
  secretIdVersion: number;
}
export const GetApproleSecretIdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
    secretIdVersion: S.Number.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}/secretids/{secretIdVersion}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({
  identifier: "GetApproleSecretIdRequest",
}) as any as S.Schema<GetApproleSecretIdRequest>;

export interface GetInstanceRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
}
export const GetInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetInstanceRequest" }) as any as S.Schema<GetInstanceRequest>;

export interface GetUserRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The user UUID with permissions on the Secrets Manager instance. */
  userId: string;
}
export const GetUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    userId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/users/{userId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "GetUserRequest" }) as any as S.Schema<GetUserRequest>;

export interface ListACLsRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
}
export const ListACLsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/acls",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "ListACLsRequest" }) as any as S.Schema<ListACLsRequest>;

export type ListACLsResponseAclsList = Array<ACL>;
export const ListACLsResponseAclsList = /*@__PURE__*/ S.Array(
  ACL,
) as any as S.Schema<ListACLsResponseAclsList>;

export interface ListACLsResponse {
  acls: ListACLsResponseAclsList;
}
export const ListACLsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    acls: ListACLsResponseAclsList,
  }),
).annotate({ identifier: "ListACLsResponse" }) as any as S.Schema<ListACLsResponse>;

export interface ListApproleSecretIdsRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
}
export const ListApproleSecretIdsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}/secretids",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({
  identifier: "ListApproleSecretIdsRequest",
}) as any as S.Schema<ListApproleSecretIdsRequest>;

export type ApproleSecretListSecretIdsList = Array<ApproleSecret>;
export const ApproleSecretListSecretIdsList = /*@__PURE__*/ S.Array(
  ApproleSecret,
) as any as S.Schema<ApproleSecretListSecretIdsList>;

export interface ApproleSecretList {
  secretIds: ApproleSecretListSecretIdsList;
}
export const ApproleSecretList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretIds: ApproleSecretListSecretIdsList,
  }),
).annotate({ identifier: "ApproleSecretList" }) as any as S.Schema<ApproleSecretList>;

export interface ListInstancesRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
}
export const ListInstancesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "ListInstancesRequest" }) as any as S.Schema<ListInstancesRequest>;

export type ListInstancesResponseInstancesList = Array<Instance>;
export const ListInstancesResponseInstancesList = /*@__PURE__*/ S.Array(
  Instance,
) as any as S.Schema<ListInstancesResponseInstancesList>;

export interface ListInstancesResponse {
  instances: ListInstancesResponseInstancesList;
}
export const ListInstancesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    instances: ListInstancesResponseInstancesList,
  }),
).annotate({ identifier: "ListInstancesResponse" }) as any as S.Schema<ListInstancesResponse>;

export interface ListUsersRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
}
export const ListUsersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/users",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "ListUsersRequest" }) as any as S.Schema<ListUsersRequest>;

export type ListUsersResponseUsersList = Array<User>;
export const ListUsersResponseUsersList = /*@__PURE__*/ S.Array(
  User,
) as any as S.Schema<ListUsersResponseUsersList>;

export interface ListUsersResponse {
  users: ListUsersResponseUsersList;
}
export const ListUsersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    users: ListUsersResponseUsersList,
  }),
).annotate({ identifier: "ListUsersResponse" }) as any as S.Schema<ListUsersResponse>;

export interface UpdateACLRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The acl UUID of the Secrets Manager instance. */
  aclId: string;
  /** The given IP/IP Range that is permitted to access. */
  cidr: string;
}
export const UpdateACLRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    aclId: S.String.pipe(T.Label()),
    cidr: S.String,
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/acls/{aclId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateACLRequest" }) as any as S.Schema<UpdateACLRequest>;

export interface UpdateACLResponse {}
export const UpdateACLResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "UpdateACLResponse",
}) as any as S.Schema<UpdateACLResponse>;

export interface UpdateACLPayload {
  /** The given IP/IP Range that is permitted to access. */
  cidr: string;
}
export const UpdateACLPayload = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cidr: S.String,
  }),
).annotate({ identifier: "UpdateACLPayload" }) as any as S.Schema<UpdateACLPayload>;

export type UpdateACLsRequestCidrsList = Array<UpdateACLPayload>;
export const UpdateACLsRequestCidrsList = /*@__PURE__*/ S.Array(
  UpdateACLPayload,
) as any as S.Schema<UpdateACLsRequestCidrsList>;

export interface UpdateACLsRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  cidrs?: UpdateACLsRequestCidrsList;
}
export const UpdateACLsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    cidrs: S.optional(UpdateACLsRequestCidrsList),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/acls",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateACLsRequest" }) as any as S.Schema<UpdateACLsRequest>;

export interface UpdateACLsResponse {}
export const UpdateACLsResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "UpdateACLsResponse",
}) as any as S.Schema<UpdateACLsResponse>;

export interface UpdateApproleRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
  /** A user chosen description to differentiate between multiple approles. */
  description?: string;
  secret_id_num_uses?: number;
  /** Token TTL in time.Duration format (eg 15m for 15 minutes, 1h for 1 hour). */
  secret_id_ttl?: string;
  /** Is true if the approle has write access to the secrets engine. Is false for a read-only approle. */
  write?: boolean;
}
export const UpdateApproleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
    secret_id_num_uses: S.optional(S.Number),
    secret_id_ttl: S.optional(S.String),
    write: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateApproleRequest" }) as any as S.Schema<UpdateApproleRequest>;

export interface UpdateApproleSecretIdRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The approle with permissions on the Secrets Manager instance. */
  roleId: string;
  /** The version of the secret id. */
  secretIdVersion: number;
  /** A user chosen description to differentiate between multiple approle secrets. */
  description?: string;
}
export const UpdateApproleSecretIdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    roleId: S.String.pipe(T.Label()),
    secretIdVersion: S.Number.pipe(T.Label()),
    description: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/approles/{roleId}/secretids/{secretIdVersion}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({
  identifier: "UpdateApproleSecretIdRequest",
}) as any as S.Schema<UpdateApproleSecretIdRequest>;

export interface UpdateInstanceRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  kmsKey?: KmsKeyPayload;
  /** A user chosen name to distinguish multiple secrets manager instances. */
  name: string;
}
export const UpdateInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    kmsKey: S.optional(KmsKeyPayload),
    name: S.String,
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1/projects/{projectId}/instances/{instanceId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateInstanceRequest" }) as any as S.Schema<UpdateInstanceRequest>;

export interface UpdateInstanceResponse {}
export const UpdateInstanceResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "UpdateInstanceResponse",
}) as any as S.Schema<UpdateInstanceResponse>;

export interface UpdateUserRequest {
  /** The STACKIT portal project UUID the Secrets Manager instance is part of. */
  projectId: string;
  /** The Secrets Manager instance UUID. */
  instanceId: string;
  /** The user UUID with permissions on the Secrets Manager instance. */
  userId: string;
  /** A user chosen description to differentiate between multiple users. */
  description?: string;
  /** Is true if the user has write access to the secrets engine. Is false for a read-only user. */
  write?: boolean;
}
export const UpdateUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    projectId: S.String.pipe(T.Label()),
    instanceId: S.String.pipe(T.Label()),
    userId: S.String.pipe(T.Label()),
    description: S.optional(S.String),
    write: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/v1/projects/{projectId}/instances/{instanceId}/users/{userId}",
      code: 200,
      baseUrl: "https://secrets-manager.api.{region}stackit.cloud",
    }),
  ),
).annotate({ identifier: "UpdateUserRequest" }) as any as S.Schema<UpdateUserRequest>;

export interface UpdateUserResponse {}
export const UpdateUserResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "UpdateUserResponse",
}) as any as S.Schema<UpdateUserResponse>;

export type CreateACLError = BadRequest | NotFound | Conflict | StackitOpError;
/** Creates a new Secrets Manager acl within the project. */
export const createACL: API.OperationMethod<
  CreateACLRequest,
  ACL,
  CreateACLError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateACLRequest,
  output: ACL,
  errors: [BadRequest, NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type CreateApproleError = BadRequest | NotFound | Conflict | StackitOpError;
/** Creates a new approle for the given Secrets Manager instance. */
export const createApprole: API.OperationMethod<
  CreateApproleRequest,
  Approle,
  CreateApproleError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateApproleRequest,
  output: Approle,
  errors: [BadRequest, NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type CreateApproleSecretIdError = BadRequest | NotFound | StackitOpError;
/** Generate new secret id for the given approle. */
export const createApproleSecretId: API.OperationMethod<
  CreateApproleSecretIdRequest,
  ApproleSecret,
  CreateApproleSecretIdError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateApproleSecretIdRequest,
  output: ApproleSecret,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type CreateInstanceError = BadRequest | StackitOpError;
/** Creates a new Secrets Manager instance within the project. */
export const createInstance: API.OperationMethod<
  CreateInstanceRequest,
  Instance,
  CreateInstanceError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateInstanceRequest,
  output: Instance,
  errors: [BadRequest, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type CreateUserError = BadRequest | NotFound | Conflict | StackitOpError;
/** Creates a new user for the given Secrets Manager instance. */
export const createUser: API.OperationMethod<
  CreateUserRequest,
  User,
  CreateUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateUserRequest,
  output: User,
  errors: [BadRequest, NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteACLError = BadRequest | NotFound | StackitOpError;
/** Deletes the given acl. */
export const deleteACL: API.OperationMethod<
  DeleteACLRequest,
  DeleteACLResponse,
  DeleteACLError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteACLRequest,
  output: DeleteACLResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteApproleError = BadRequest | NotFound | StackitOpError;
/** Deletes the given approle. */
export const deleteApprole: API.OperationMethod<
  DeleteApproleRequest,
  DeleteApproleResponse,
  DeleteApproleError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteApproleRequest,
  output: DeleteApproleResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteApproleSecretIdError = BadRequest | NotFound | StackitOpError;
/** Deletes the secret id by its given version. */
export const deleteApproleSecretId: API.OperationMethod<
  DeleteApproleSecretIdRequest,
  DeleteApproleSecretIdResponse,
  DeleteApproleSecretIdError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteApproleSecretIdRequest,
  output: DeleteApproleSecretIdResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteInstanceError = BadRequest | NotFound | StackitOpError;
/** Deletes the given Secrets Manager instance. */
export const deleteInstance: API.OperationMethod<
  DeleteInstanceRequest,
  DeleteInstanceResponse,
  DeleteInstanceError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteInstanceRequest,
  output: DeleteInstanceResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type DeleteUserError = BadRequest | NotFound | StackitOpError;
/** Deletes the given user. */
export const deleteUser: API.OperationMethod<
  DeleteUserRequest,
  DeleteUserResponse,
  DeleteUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteUserRequest,
  output: DeleteUserResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetACLError = BadRequest | NotFound | StackitOpError;
/** Returns the details for the given acl. */
export const getACL: API.OperationMethod<GetACLRequest, ACL, GetACLError, StackitOpContext> =
  /*@__PURE__*/ API.make(() => ({
    input: GetACLRequest,
    output: ACL,
    errors: [BadRequest, NotFound, UnknownStackitError],
    protocol: StackitProtocol,
    retry: Retry.Retry,
  }));

export type GetApproleError = BadRequest | NotFound | StackitOpError;
/** Returns the details for the given approle. */
export const getApprole: API.OperationMethod<
  GetApproleRequest,
  Approle,
  GetApproleError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetApproleRequest,
  output: Approle,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetApprolesError = BadRequest | NotFound | StackitOpError;
/** Returns the approles for the given Secrets Manager instance. */
export const getApproles: API.OperationMethod<
  GetApprolesRequest,
  ApproleList,
  GetApprolesError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetApprolesRequest,
  output: ApproleList,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetApproleSecretIdError = BadRequest | NotFound | StackitOpError;
/** Read the properties of a given secret id by its given version. */
export const getApproleSecretId: API.OperationMethod<
  GetApproleSecretIdRequest,
  ApproleSecret,
  GetApproleSecretIdError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetApproleSecretIdRequest,
  output: ApproleSecret,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetInstanceError = BadRequest | NotFound | StackitOpError;
/** Returns the details for the given Secrets Manager instance. */
export const getInstance: API.OperationMethod<
  GetInstanceRequest,
  Instance,
  GetInstanceError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetInstanceRequest,
  output: Instance,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type GetUserError = BadRequest | NotFound | StackitOpError;
/** Returns the details for the given user. */
export const getUser: API.OperationMethod<GetUserRequest, User, GetUserError, StackitOpContext> =
  /*@__PURE__*/ API.make(() => ({
    input: GetUserRequest,
    output: User,
    errors: [BadRequest, NotFound, UnknownStackitError],
    protocol: StackitProtocol,
    retry: Retry.Retry,
  }));

export type ListACLsError = BadRequest | NotFound | StackitOpError;
/** Returns the acls for the given Secrets Manager instance. */
export const listACLs: API.OperationMethod<
  ListACLsRequest,
  ListACLsResponse,
  ListACLsError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListACLsRequest,
  output: ListACLsResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type ListApproleSecretIdsError = BadRequest | NotFound | StackitOpError;
/** Returns the secret id list for the given Secrets Manager instance and approle. */
export const listApproleSecretIds: API.OperationMethod<
  ListApproleSecretIdsRequest,
  ApproleSecretList,
  ListApproleSecretIdsError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListApproleSecretIdsRequest,
  output: ApproleSecretList,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type ListInstancesError = BadRequest | StackitOpError;
/** Returns a list of all Secrets Manager instances within the project. */
export const listInstances: API.OperationMethod<
  ListInstancesRequest,
  ListInstancesResponse,
  ListInstancesError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListInstancesRequest,
  output: ListInstancesResponse,
  errors: [BadRequest, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type ListUsersError = BadRequest | NotFound | StackitOpError;
/** Returns the users for the given Secrets Manager instance. */
export const listUsers: API.OperationMethod<
  ListUsersRequest,
  ListUsersResponse,
  ListUsersError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListUsersRequest,
  output: ListUsersResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateACLError = BadRequest | NotFound | StackitOpError;
/** Updates the ip ranges for the acl. */
export const updateACL: API.OperationMethod<
  UpdateACLRequest,
  UpdateACLResponse,
  UpdateACLError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateACLRequest,
  output: UpdateACLResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateACLsError = BadRequest | NotFound | Conflict | StackitOpError;
/** Changes a list of ACLs within the project. */
export const updateACLs: API.OperationMethod<
  UpdateACLsRequest,
  UpdateACLsResponse,
  UpdateACLsError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateACLsRequest,
  output: UpdateACLsResponse,
  errors: [BadRequest, NotFound, Conflict, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateApproleError = BadRequest | NotFound | StackitOpError;
/** Updates the details for the given approle. */
export const updateApprole: API.OperationMethod<
  UpdateApproleRequest,
  Approle,
  UpdateApproleError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateApproleRequest,
  output: Approle,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateApproleSecretIdError = BadRequest | NotFound | StackitOpError;
/** Update the description of a secret id by its given version. */
export const updateApproleSecretId: API.OperationMethod<
  UpdateApproleSecretIdRequest,
  ApproleSecret,
  UpdateApproleSecretIdError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateApproleSecretIdRequest,
  output: ApproleSecret,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateInstanceError = BadRequest | NotFound | StackitOpError;
/** Updates the given Secrets Manager instance. */
export const updateInstance: API.OperationMethod<
  UpdateInstanceRequest,
  UpdateInstanceResponse,
  UpdateInstanceError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateInstanceRequest,
  output: UpdateInstanceResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));

export type UpdateUserError = BadRequest | NotFound | StackitOpError;
/** Updates the details for the given user. */
export const updateUser: API.OperationMethod<
  UpdateUserRequest,
  UpdateUserResponse,
  UpdateUserError,
  StackitOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateUserRequest,
  output: UpdateUserResponse,
  errors: [BadRequest, NotFound, UnknownStackitError],
  protocol: StackitProtocol,
  retry: Retry.Retry,
}));
