import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (docs.slack.dev JSON twins). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { SlackError, SlackRateLimited } from "../errors.ts";
import { SlackProtocol, type SlackOpError, type SlackOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { SlackOpError, SlackOpContext };

export type ValidateBlockRequestBlocksCase1ItemMap = { [key: string]: unknown | undefined };
export const ValidateBlockRequestBlocksCase1ItemMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<ValidateBlockRequestBlocksCase1ItemMap>;

export type ValidateBlockRequestBlocksCase1List = Array<ValidateBlockRequestBlocksCase1ItemMap>;
export const ValidateBlockRequestBlocksCase1List = /*@__PURE__*/ S.Array(
  ValidateBlockRequestBlocksCase1ItemMap,
) as any as S.Schema<ValidateBlockRequestBlocksCase1List>;

/** A JSON-encoded array of [structured blocks](/reference/block-kit/blocks). Provide exactly one of `blocks`, `view`, or `message`. */
export type ValidateBlockRequestBlocks = string | ValidateBlockRequestBlocksCase1List;
export const ValidateBlockRequestBlocks = /*@__PURE__*/ S.Unknown.pipe(T.UnionCases([[], []]));

export interface ValidateBlockRequest {
  /** A JSON-encoded array of [structured blocks](/reference/block-kit/blocks). Provide exactly one of `blocks`, `view`, or `message`. */
  blocks?: ValidateBlockRequestBlocks;
  /** A JSON-encoded [message payload](/messaging/creating-interactive-messages) to validate. Provide exactly one of `blocks`, `view`, or `message`. */
  message?: string;
  /** A JSON-encoded [view payload](/reference/views) to validate. Provide exactly one of `blocks`, `view`, or `message`. */
  view?: string;
}
export const ValidateBlockRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    blocks: S.optional(ValidateBlockRequestBlocks),
    message: S.optional(S.String),
    view: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/blocks.validate", code: 200 })),
).annotate({ identifier: "ValidateBlockRequest" }) as any as S.Schema<ValidateBlockRequest>;

export interface ValidateBlockResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
}
export const ValidateBlockResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
  }),
).annotate({ identifier: "ValidateBlockResponse" }) as any as S.Schema<ValidateBlockResponse>;

export type ValidateBlockError = SlackOpError;
/** Validates blocks, messages, and views Block Kit JSON payloads. Method-specific errors (the `error` slug on the SlackError): - `invalid_arguments` — The request arguments are invalid. Ensure you provide exactly one of `blocks`, `view`, or `message`, and that the value is valid JSON. Consult `response_metadata.messages` for details. - `invalid_blocks` — The blocks array failed validation. The `errors` field contains a list of issues, each with a JSON pointer path to the invalid element, the constraint that failed, and the expected value. - `invalid_view` — The view payload failed validation. The `errors` field contains a list of issues, each with a JSON pointer path to the invalid element, the constraint that failed, and the expected value. - `invalid_message` — The message payload failed validation. The `errors` field contains a list of issues, each with a JSON pointer path to the invalid element, the constraint that failed, and the expected value. - `ratelimited` — Too many requests. Reduce your request rate and retry after a brief wait. See https://docs.slack.dev/reference/methods/blocks.validate */
export const validateBlock: API.OperationMethod<
  ValidateBlockRequest,
  ValidateBlockResponse,
  ValidateBlockError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ValidateBlockRequest,
  output: ValidateBlockResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));
