import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (docs.slack.dev JSON twins). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { SlackError, SlackRateLimited } from "../errors.ts";
import { slackPaginate } from "../pagination.ts";
import { SlackProtocol, type SlackOpError, type SlackOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { SlackOpError, SlackOpContext };

export interface AddStarRequest {
  /** Channel to add star to, or channel where the message to add star to was posted (used with `timestamp`). */
  channel?: string;
  /** File to add star to. */
  file?: string;
  /** File comment to add star to. */
  file_comment?: string;
  /** Timestamp of the message to add star to. */
  timestamp?: string;
}
export const AddStarRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    channel: S.optional(S.String),
    file: S.optional(S.String),
    file_comment: S.optional(S.String),
    timestamp: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/stars.add", code: 200 })),
).annotate({ identifier: "AddStarRequest" }) as any as S.Schema<AddStarRequest>;

export interface AddStarResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
}
export const AddStarResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
  }),
).annotate({ identifier: "AddStarResponse" }) as any as S.Schema<AddStarResponse>;

export interface ListStarsRequest {
  count?: number;
  /** Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute returned by the previous request's `response_metadata`. This parameter is optional, but pagination is mandatory: the default value simply fetches the first "page" of the collection. See [pagination](/apis/web-api/pagination) for more details. */
  cursor?: string;
  /** The maximum number of items to return. Fewer than the requested number of items may be returned, even if the end of the list hasn't been reached. */
  limit?: number;
  page?: number;
  /** encoded team id to list stars in, required if org token is used */
  team_id?: string;
}
export const ListStarsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number.pipe(T.Query())),
    cursor: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    page: S.optional(S.Number.pipe(T.Query())),
    team_id: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/stars.list", code: 200 })),
).annotate({ identifier: "ListStarsRequest" }) as any as S.Schema<ListStarsRequest>;

export type ListStarsResponseItemsItemCase0Type = "message";
export const ListStarsResponseItemsItemCase0Type = S.String;

export interface ListStarsResponseItemsItemCase0 {
  type: ListStarsResponseItemsItemCase0Type;
  channel: string;
  message: unknown;
  date_create: number;
}
export const ListStarsResponseItemsItemCase0 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: ListStarsResponseItemsItemCase0Type,
    channel: S.String,
    message: S.Unknown,
    date_create: S.Number,
  }),
).annotate({
  identifier: "ListStarsResponseItemsItemCase0",
}) as any as S.Schema<ListStarsResponseItemsItemCase0>;

export type ListStarsResponseItemsItemCase1Type = "file";
export const ListStarsResponseItemsItemCase1Type = S.String;

export interface ListStarsResponseItemsItemCase1 {
  type: ListStarsResponseItemsItemCase1Type;
  file: unknown;
  date_create: number;
}
export const ListStarsResponseItemsItemCase1 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: ListStarsResponseItemsItemCase1Type,
    file: S.Unknown,
    date_create: S.Number,
  }),
).annotate({
  identifier: "ListStarsResponseItemsItemCase1",
}) as any as S.Schema<ListStarsResponseItemsItemCase1>;

export type ListStarsResponseItemsItemCase2Type = "file_comment";
export const ListStarsResponseItemsItemCase2Type = S.String;

export interface ListStarsResponseItemsItemCase2 {
  type: ListStarsResponseItemsItemCase2Type;
  file: unknown;
  comment: unknown;
  date_create: number;
}
export const ListStarsResponseItemsItemCase2 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: ListStarsResponseItemsItemCase2Type,
    file: S.Unknown,
    comment: S.Unknown,
    date_create: S.Number,
  }),
).annotate({
  identifier: "ListStarsResponseItemsItemCase2",
}) as any as S.Schema<ListStarsResponseItemsItemCase2>;

export type ListStarsResponseItemsItemCase3Type = "channel";
export const ListStarsResponseItemsItemCase3Type = S.String;

export interface ListStarsResponseItemsItemCase3 {
  type: ListStarsResponseItemsItemCase3Type;
  channel: string;
  date_create: number;
}
export const ListStarsResponseItemsItemCase3 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: ListStarsResponseItemsItemCase3Type,
    channel: S.String,
    date_create: S.Number,
  }),
).annotate({
  identifier: "ListStarsResponseItemsItemCase3",
}) as any as S.Schema<ListStarsResponseItemsItemCase3>;

export type ListStarsResponseItemsItemCase4Type = "im";
export const ListStarsResponseItemsItemCase4Type = S.String;

export interface ListStarsResponseItemsItemCase4 {
  type: ListStarsResponseItemsItemCase4Type;
  channel: string;
  date_create: number;
}
export const ListStarsResponseItemsItemCase4 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: ListStarsResponseItemsItemCase4Type,
    channel: S.String,
    date_create: S.Number,
  }),
).annotate({
  identifier: "ListStarsResponseItemsItemCase4",
}) as any as S.Schema<ListStarsResponseItemsItemCase4>;

export type ListStarsResponseItemsItemCase5Type = "group";
export const ListStarsResponseItemsItemCase5Type = S.String;

export interface ListStarsResponseItemsItemCase5 {
  type: ListStarsResponseItemsItemCase5Type;
  channel: string;
  date_create: number;
}
export const ListStarsResponseItemsItemCase5 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: ListStarsResponseItemsItemCase5Type,
    channel: S.String,
    date_create: S.Number,
  }),
).annotate({
  identifier: "ListStarsResponseItemsItemCase5",
}) as any as S.Schema<ListStarsResponseItemsItemCase5>;

export type ListStarsResponseItemsItem =
  | ListStarsResponseItemsItemCase0
  | ListStarsResponseItemsItemCase1
  | ListStarsResponseItemsItemCase2
  | ListStarsResponseItemsItemCase3
  | ListStarsResponseItemsItemCase4
  | ListStarsResponseItemsItemCase5;
export const ListStarsResponseItemsItem = /*@__PURE__*/ S.Unknown.pipe(
  T.UnionCases(
    [
      ["type", "channel", "message", "date_create"],
      ["type", "file", "date_create"],
      ["type", "file", "comment", "date_create"],
      ["type", "channel", "date_create"],
      ["type", "channel", "date_create"],
      ["type", "channel", "date_create"],
    ],
    { key: "type", values: ["message", "file", "file_comment", "channel", "im", "group"] },
  ),
);

export type ListStarsResponseItemsList = Array<ListStarsResponseItemsItem>;
export const ListStarsResponseItemsList = /*@__PURE__*/ S.Array(
  ListStarsResponseItemsItem,
) as any as S.Schema<ListStarsResponseItemsList>;

/** Pagination metadata. An empty `next_cursor` means the last page. */
export interface ListStarsResponseResponseMetadata {
  /** Cursor for the next page — pass as `cursor` on the next call. */
  next_cursor?: string;
}
export const ListStarsResponseResponseMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    next_cursor: S.optional(S.String),
  }),
).annotate({
  identifier: "ListStarsResponseResponseMetadata",
}) as any as S.Schema<ListStarsResponseResponseMetadata>;

export interface ListStarsResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  items: ListStarsResponseItemsList;
  paging?: unknown;
  /** Pagination metadata. An empty `next_cursor` means the last page. */
  response_metadata?: ListStarsResponseResponseMetadata;
}
export const ListStarsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    items: ListStarsResponseItemsList,
    paging: S.optional(S.Unknown),
    response_metadata: S.optional(ListStarsResponseResponseMetadata),
  }),
).annotate({ identifier: "ListStarsResponse" }) as any as S.Schema<ListStarsResponse>;

export interface RemoveStarRequest {
  /** Channel to remove star from, or channel where the message to remove star from was posted (used with `timestamp`). */
  channel?: string;
  /** File to remove star from. */
  file?: string;
  /** File comment to remove star from. */
  file_comment?: string;
  /** Timestamp of the message to remove star from. */
  timestamp?: string;
}
export const RemoveStarRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    channel: S.optional(S.String),
    file: S.optional(S.String),
    file_comment: S.optional(S.String),
    timestamp: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/stars.remove", code: 200 })),
).annotate({ identifier: "RemoveStarRequest" }) as any as S.Schema<RemoveStarRequest>;

export interface RemoveStarResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
}
export const RemoveStarResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
  }),
).annotate({ identifier: "RemoveStarResponse" }) as any as S.Schema<RemoveStarResponse>;

export type AddStarError = SlackOpError;
/** Save an item for later. Formerly known as adding a star. Required scopes — user: `stars:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `already_starred` — The specified item has already been starred by the authenticated user. - `bad_timestamp` — Value passed for `timestamp` was invalid. - `channel_not_found` — Channel, private group, or DM specified by `channel` does not exist - `external_channel_migrating` — Channel is undergoing active migration - `file_comment_not_found` — File comment specified by `file_comment` does not exist. - `file_not_found` — File specified by `file` does not exist. - `message_not_found` — Message specified by `channel` and `timestamp` does not exist. - `no_item_specified` — `file`, `file_comment`, `channel` and `timestamp` was not specified. See https://docs.slack.dev/reference/methods/stars.add */
export const addStar: API.OperationMethod<
  AddStarRequest,
  AddStarResponse,
  AddStarError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AddStarRequest,
  output: AddStarResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type ListStarsError = SlackOpError;
/** (Deprecated) Listed a user's saved items, formerly known as stars. Required scopes — user: `stars:read` Rate limit tier: 3 Method-specific errors (the `error` slug on the SlackError): - `missing_argument` — A required argument is missing. See https://docs.slack.dev/reference/methods/stars.list */
export const listStars: API.PaginatedOperationMethod<
  ListStarsRequest,
  ListStarsResponse,
  ListStarsError,
  SlackOpContext,
  ListStarsResponseItemsItem
> = /*@__PURE__*/ API.makePaginated(
  () => ({
    input: ListStarsRequest,
    output: ListStarsResponse,
    errors: [SlackError, SlackRateLimited],
    protocol: SlackProtocol,
    retry: Retry.Retry,
    pagination: {
      mode: "cursor",
      inputToken: "cursor",
      outputToken: "response_metadata.next_cursor",
      items: "items",
      pageSize: "limit",
    } as const,
  }),
  slackPaginate,
) as any;

export type RemoveStarError = SlackOpError;
/** Removes a saved item (star) from an item. Required scopes — user: `stars:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `bad_timestamp` — Value passed for `timestamp` was invalid. - `channel_not_found` — Channel, private group, or DM specified by `channel` does not exist - `file_comment_not_found` — File comment specified by `file_comment` does not exist. - `file_not_found` — File specified by `file` does not exist. - `message_not_found` — Message specified by `channel` and `timestamp` does not exist. - `no_item_specified` — `file`, `file_comment`, `channel` and `timestamp` was not specified. - `not_starred` — The specified item is not currently starred by the authenticated user. See https://docs.slack.dev/reference/methods/stars.remove */
export const removeStar: API.OperationMethod<
  RemoveStarRequest,
  RemoveStarResponse,
  RemoveStarError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RemoveStarRequest,
  output: RemoveStarResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));
