import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (docs.slack.dev JSON twins). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { SlackError, SlackRateLimited } from "../errors.ts";
import { SlackProtocol, type SlackOpError, type SlackOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { SlackOpError, SlackOpContext };

/** A comma separated string of encoded channel IDs for which the User Group uses as a default. */
export type CreateUsergroupRequestChannelsList = Array<string>;
export const CreateUsergroupRequestChannelsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateUsergroupRequestChannelsList>;

/** A comma separated string of encoded channel IDs for which the User Group can custom add usergroup members too. */
export type CreateUsergroupRequestAdditionalChannelsList = Array<string>;
export const CreateUsergroupRequestAdditionalChannelsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateUsergroupRequestAdditionalChannelsList>;

export interface CreateUsergroupRequest {
  /** A comma separated string of encoded channel IDs for which the User Group uses as a default. */
  channels?: CreateUsergroupRequestChannelsList;
  /** A comma separated string of encoded channel IDs for which the User Group can custom add usergroup members too. */
  additional_channels?: CreateUsergroupRequestAdditionalChannelsList;
  /** A short description of the User Group. */
  description?: string;
  /** A mention handle. Must be unique among channels, users and User Groups. */
  handle?: string;
  /** Include the number of users in each User Group. */
  include_count?: boolean;
  /** A name for the User Group. Must be unique among User Groups. */
  name: string;
  /** Encoded team id where the user group has to be created, required if org token is used. */
  team_id?: string;
  /** Configure this user group to show as a sidebar section for all group members. Note: Only relevant if group has 1 or more default channels added. */
  enable_section?: boolean;
}
export const CreateUsergroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    channels: S.optional(CreateUsergroupRequestChannelsList),
    additional_channels: S.optional(CreateUsergroupRequestAdditionalChannelsList),
    description: S.optional(S.String),
    handle: S.optional(S.String),
    include_count: S.optional(S.Boolean),
    name: S.String,
    team_id: S.optional(S.String),
    enable_section: S.optional(S.Boolean),
  }).pipe(T.Http({ method: "POST", uri: "/usergroups.create", code: 200 })),
).annotate({ identifier: "CreateUsergroupRequest" }) as any as S.Schema<CreateUsergroupRequest>;

export interface CreateUsergroupResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  usergroup: unknown;
}
export const CreateUsergroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    usergroup: S.Unknown,
  }),
).annotate({ identifier: "CreateUsergroupResponse" }) as any as S.Schema<CreateUsergroupResponse>;

export interface DisableUsergroupRequest {
  /** Include the number of users in the User Group. */
  include_count?: boolean;
  /** Encoded target team id where the user group is, required if org token is used. */
  team_id?: string;
  /** The encoded ID of the User Group to disable. */
  usergroup: string;
}
export const DisableUsergroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    include_count: S.optional(S.Boolean),
    team_id: S.optional(S.String),
    usergroup: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/usergroups.disable", code: 200 })),
).annotate({ identifier: "DisableUsergroupRequest" }) as any as S.Schema<DisableUsergroupRequest>;

export interface DisableUsergroupResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  usergroup: unknown;
}
export const DisableUsergroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    usergroup: S.Unknown,
  }),
).annotate({ identifier: "DisableUsergroupResponse" }) as any as S.Schema<DisableUsergroupResponse>;

export interface EnableUsergroupRequest {
  /** Include the number of users in the User Group. */
  include_count?: boolean;
  /** Encoded team id where the user group is, required if org token is used. */
  team_id?: string;
  /** The encoded ID of the User Group to enable. */
  usergroup: string;
}
export const EnableUsergroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    include_count: S.optional(S.Boolean),
    team_id: S.optional(S.String),
    usergroup: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/usergroups.enable", code: 200 })),
).annotate({ identifier: "EnableUsergroupRequest" }) as any as S.Schema<EnableUsergroupRequest>;

export interface EnableUsergroupResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  usergroup: unknown;
}
export const EnableUsergroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    usergroup: S.Unknown,
  }),
).annotate({ identifier: "EnableUsergroupResponse" }) as any as S.Schema<EnableUsergroupResponse>;

export interface ListUsergroupsRequest {
  /** Include the number of users in each User Group. */
  include_count?: boolean;
  /** Include results for disabled User Groups. */
  include_disabled?: boolean;
  /** Include the list of users for each User Group. */
  include_users?: boolean;
  /** The user group's encoded team ID. Required if org token is used. */
  team_id?: string;
}
export const ListUsergroupsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    include_count: S.optional(S.Boolean.pipe(T.Query())),
    include_disabled: S.optional(S.Boolean.pipe(T.Query())),
    include_users: S.optional(S.Boolean.pipe(T.Query())),
    team_id: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/usergroups.list", code: 200 })),
).annotate({ identifier: "ListUsergroupsRequest" }) as any as S.Schema<ListUsergroupsRequest>;

export type ListUsergroupsResponseUsergroupsList = Array<unknown>;
export const ListUsergroupsResponseUsergroupsList = /*@__PURE__*/ S.Array(
  S.Unknown,
) as any as S.Schema<ListUsergroupsResponseUsergroupsList>;

export interface ListUsergroupsResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  usergroups: ListUsergroupsResponseUsergroupsList;
}
export const ListUsergroupsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    usergroups: ListUsergroupsResponseUsergroupsList,
  }),
).annotate({ identifier: "ListUsergroupsResponse" }) as any as S.Schema<ListUsergroupsResponse>;

export interface ListUsersRequest {
  /** Include results for disabled User Groups. */
  include_disabled?: boolean;
  /** The encoded ID of the User Group. */
  usergroup: string;
  /** The user group's encoded team ID. Required if org token is used. */
  team_id?: string;
}
export const ListUsersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    include_disabled: S.optional(S.Boolean.pipe(T.Query())),
    usergroup: S.String.pipe(T.Query()),
    team_id: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/usergroups.users.list", code: 200 })),
).annotate({ identifier: "ListUsersRequest" }) as any as S.Schema<ListUsersRequest>;

export type ListUsersResponseUsersList = Array<unknown>;
export const ListUsersResponseUsersList = /*@__PURE__*/ S.Array(
  S.Unknown,
) as any as S.Schema<ListUsersResponseUsersList>;

export interface ListUsersResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  users: ListUsersResponseUsersList;
}
export const ListUsersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    users: ListUsersResponseUsersList,
  }),
).annotate({ identifier: "ListUsersResponse" }) as any as S.Schema<ListUsersResponse>;

/** A comma separated string of encoded user IDs that represent the entire list of users for the user group. */
export type UpdateUserRequestUsersList = Array<string>;
export const UpdateUserRequestUsersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateUserRequestUsersList>;

/** A comma separated string of encoded channel IDs for which the User Group can custom add usergroup members too. */
export type UpdateUserRequestAdditionalChannelsList = Array<string>;
export const UpdateUserRequestAdditionalChannelsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateUserRequestAdditionalChannelsList>;

export interface UpdateUserRequest {
  /** Include the number of users in the user group. */
  include_count?: boolean;
  /** encoded team id where the user group exists, required if org token is used */
  team_id?: string;
  /** The encoded ID of the user group to update. */
  usergroup: string;
  /** A comma separated string of encoded user IDs that represent the entire list of users for the user group. */
  users: UpdateUserRequestUsersList;
  /** A comma separated string of encoded channel IDs for which the User Group can custom add usergroup members too. */
  additional_channels?: UpdateUserRequestAdditionalChannelsList;
  /** Boolean to identify if the API is getting called when a shared section is getting shared */
  is_shared?: boolean;
}
export const UpdateUserRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    include_count: S.optional(S.Boolean),
    team_id: S.optional(S.String),
    usergroup: S.String,
    users: UpdateUserRequestUsersList,
    additional_channels: S.optional(UpdateUserRequestAdditionalChannelsList),
    is_shared: S.optional(S.Boolean),
  }).pipe(T.Http({ method: "POST", uri: "/usergroups.users.update", code: 200 })),
).annotate({ identifier: "UpdateUserRequest" }) as any as S.Schema<UpdateUserRequest>;

export interface UpdateUserResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  usergroup: unknown;
}
export const UpdateUserResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    usergroup: S.Unknown,
  }),
).annotate({ identifier: "UpdateUserResponse" }) as any as S.Schema<UpdateUserResponse>;

/** A comma separated string of encoded channel IDs for which the User Group uses as a default. */
export type UpdateUsergroupRequestChannelsList = Array<string>;
export const UpdateUsergroupRequestChannelsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateUsergroupRequestChannelsList>;

/** A comma separated string of encoded channel IDs for which the User Group can custom add usergroup members too. */
export type UpdateUsergroupRequestAdditionalChannelsList = Array<string>;
export const UpdateUsergroupRequestAdditionalChannelsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateUsergroupRequestAdditionalChannelsList>;

export interface UpdateUsergroupRequest {
  /** A comma separated string of encoded channel IDs for which the User Group uses as a default. */
  channels?: UpdateUsergroupRequestChannelsList;
  /** A comma separated string of encoded channel IDs for which the User Group can custom add usergroup members too. */
  additional_channels?: UpdateUsergroupRequestAdditionalChannelsList;
  /** A short description of the User Group. */
  description?: string;
  /** A mention handle. Must be unique among channels, users and User Groups. */
  handle?: string;
  /** Include the number of users in the User Group. */
  include_count?: boolean;
  /** A name for the User Group. Must be unique among User Groups. */
  name?: string;
  /** encoded team id where the user group exists, required if org token is used */
  team_id?: string;
  /** The encoded ID of the User Group to update. */
  usergroup: string;
  /** Configure this user group to show as a sidebar section for all group members. Note: Only relevant if group has 1 or more default channels added. */
  enable_section?: boolean;
}
export const UpdateUsergroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    channels: S.optional(UpdateUsergroupRequestChannelsList),
    additional_channels: S.optional(UpdateUsergroupRequestAdditionalChannelsList),
    description: S.optional(S.String),
    handle: S.optional(S.String),
    include_count: S.optional(S.Boolean),
    name: S.optional(S.String),
    team_id: S.optional(S.String),
    usergroup: S.String,
    enable_section: S.optional(S.Boolean),
  }).pipe(T.Http({ method: "POST", uri: "/usergroups.update", code: 200 })),
).annotate({ identifier: "UpdateUsergroupRequest" }) as any as S.Schema<UpdateUsergroupRequest>;

/** List of user IDs who would exceed their channel limit */
export type UpdateUsergroupResponseChannelLimitUserIdsList = Array<string>;
export const UpdateUsergroupResponseChannelLimitUserIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateUsergroupResponseChannelLimitUserIdsList>;

export interface UpdateUsergroupResponse {
  /** Always `true` (a failed call raises a typed error instead). */
  ok: boolean;
  usergroup: unknown;
  /** List of user IDs who would exceed their channel limit */
  channel_limit_user_ids?: UpdateUsergroupResponseChannelLimitUserIdsList;
}
export const UpdateUsergroupResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
    usergroup: S.Unknown,
    channel_limit_user_ids: S.optional(UpdateUsergroupResponseChannelLimitUserIdsList),
  }),
).annotate({ identifier: "UpdateUsergroupResponse" }) as any as S.Schema<UpdateUsergroupResponse>;

export type CreateUsergroupError = SlackOpError;
/** Create a User Group. Required scopes — bot: `usergroups:write`; user: `usergroups:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `bad_handle` — Handle is invalid - `description_too_long` — Given usergroup description is too long - `forbidden_handle` — Handle is invalid - `handle_already_exists` — Handle is already in use on this workspace - `invalid_channel_provided` — An invalid channel ID was provided - `invalid_group_provided` — An invalid group ID was provided - `missing_argument` — A required argument is missing. - `missing_subteam_name` — Subteam name is required - `name_already_exists` — Name is already in use on this workspace - `name_too_long` — Name too long. - `paid_teams_only` — Usergroups can only be used on paid Slack teams - `permission_denied` — The user does not have permission to create a User Group. - `plan_upgrade_required` — This workspace does not have access to User Groups, as that feature is only available on Standard and above plans. - `target_team_not_on_org` — Target team specified is not on the org in context - `target_team_must_be_specified_in_org_context` — No target team was specified but the team in context is an org See https://docs.slack.dev/reference/methods/usergroups.create */
export const createUsergroup: API.OperationMethod<
  CreateUsergroupRequest,
  CreateUsergroupResponse,
  CreateUsergroupError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateUsergroupRequest,
  output: CreateUsergroupResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type DisableUsergroupError = SlackOpError;
/** Disable an existing User Group. Required scopes — bot: `usergroups:write`; user: `usergroups:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `missing_argument` — A required argument is missing. - `permission_denied` — The user does not have permission to disable the User Group. - `plan_upgrade_required` — This workspace does not have access to User Groups, as that feature is only available on Standard and above plans. - `target_team_not_on_org` — Target team specified is not on the org in context - `target_team_must_be_specified_in_org_context` — No target team was specified but the team in context is an org See https://docs.slack.dev/reference/methods/usergroups.disable */
export const disableUsergroup: API.OperationMethod<
  DisableUsergroupRequest,
  DisableUsergroupResponse,
  DisableUsergroupError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DisableUsergroupRequest,
  output: DisableUsergroupResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type EnableUsergroupError = SlackOpError;
/** Enable a User Group. Required scopes — bot: `usergroups:write`; user: `usergroups:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `missing_argument` — A required argument is missing. - `permission_denied` — The user does not have permission to enables the User Group. - `plan_upgrade_required` — This workspace does not have access to User Groups, as that feature is only available on Standard and above plans. See https://docs.slack.dev/reference/methods/usergroups.enable */
export const enableUsergroup: API.OperationMethod<
  EnableUsergroupRequest,
  EnableUsergroupResponse,
  EnableUsergroupError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EnableUsergroupRequest,
  output: EnableUsergroupResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type ListUsergroupsError = SlackOpError;
/** List all User Groups for a team. Required scopes — bot: `usergroups:read`; user: `usergroups:read` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `missing_argument` — A required argument is missing. - `plan_upgrade_required` — This workspace does not have access to User Groups, as that feature is only available on Standard and above plans. - `invalid_cursor` — Value passed for `cursor` was not valid or is no longer valid. - `users_not_found` — Cannot find users on subteam. - `invalid_team` — Cannot find subteam team. See https://docs.slack.dev/reference/methods/usergroups.list */
export const listUsergroups: API.OperationMethod<
  ListUsergroupsRequest,
  ListUsergroupsResponse,
  ListUsergroupsError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListUsergroupsRequest,
  output: ListUsergroupsResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type ListUsersError = SlackOpError;
/** List all users in a User Group. Required scopes — bot: `usergroups:read`; user: `usergroups:read` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `no_such_subteam` — No usergroup found with the given ID. - `plan_upgrade_required` — This workspace does not have access to User Groups, as that feature is only available on Standard and above plans. - `invalid_cursor` — Value passed for `cursor` was not valid or is no longer valid. See https://docs.slack.dev/reference/methods/usergroups.users.list */
export const listUsers: API.OperationMethod<
  ListUsersRequest,
  ListUsersResponse,
  ListUsersError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListUsersRequest,
  output: ListUsersResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type UpdateUserError = SlackOpError;
/** Update the list of users for a user group. Required scopes — bot: `usergroups:write`; user: `usergroups:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `invalid_users` — Value passed for `users` was empty or invalid. - `failed_for_some_users` — User(s) are not in the workspace where this usergroup exists - `missing_argument` — A required argument is missing. - `no_users_provided` — Either the `users` field wasn't provided or an empty value was passed. - `permission_denied` — The user does not have permission to update the list of users for a user group. Check workspace settings to confirm whether the calling user has permission. - `plan_upgrade_required` — This workspace does not have access to user groups, as that feature is only available on Standard and above plans. - `subteam_max_users_exceeded` — Exceeds maximum supported number of users per subteam. - `cannot_modify_role_admin` — The user does not have permission to modify the roles admin role. See https://docs.slack.dev/reference/methods/usergroups.users.update */
export const updateUser: API.OperationMethod<
  UpdateUserRequest,
  UpdateUserResponse,
  UpdateUserError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateUserRequest,
  output: UpdateUserResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));

export type UpdateUsergroupError = SlackOpError;
/** Update an existing User Group. Required scopes — bot: `usergroups:write`; user: `usergroups:write` Rate limit tier: 2 Method-specific errors (the `error` slug on the SlackError): - `missing_argument` — A required argument is missing. - `paid_teams_only` — This workspace does not have access to User Groups, as that feature is only available on Standard and above plans. - `permission_denied` — The user does not have permission to update the User Group. - `too_many_linked_channels` — This request exceeds the number of channels we supporting linking to a single usergroup. - `user_channel_limit_exceeded` — Adding these channels would cause one or more members to exceed their channel limit. See https://docs.slack.dev/reference/methods/usergroups.update */
export const updateUsergroup: API.OperationMethod<
  UpdateUsergroupRequest,
  UpdateUsergroupResponse,
  UpdateUsergroupError,
  SlackOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateUsergroupRequest,
  output: UpdateUsergroupResponse,
  errors: [SlackError, SlackRateLimited],
  protocol: SlackProtocol,
  retry: Retry.Retry,
}));
