import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-ovh). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownOvhError } from "../errors.ts";
import { OvhProtocol, type OvhOpError, type OvhOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { OvhOpError, OvhOpContext };

/** All future uses you can provide for a service termination */
export type ServiceTerminationFutureUseEnum =
  | "NOT_REPLACING_SERVICE"
  | "OTHER"
  | "SUBSCRIBE_AN_OTHER_SERVICE"
  | "SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR"
  | "SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR";
export const ServiceTerminationFutureUseEnum = S.String;

/** All reasons you can provide for a service termination */
export type ServiceTerminationReasonEnum =
  | "FEATURES_DONT_SUIT_ME"
  | "LACK_OF_PERFORMANCES"
  | "MIGRATED_TO_ANOTHER_OVH_PRODUCT"
  | "MIGRATED_TO_COMPETITOR"
  | "NOT_ENOUGH_RECOGNITION"
  | "NOT_NEEDED_ANYMORE"
  | "NOT_RELIABLE"
  | "NO_ANSWER"
  | "OTHER"
  | "PRODUCT_DIMENSION_DONT_SUIT_ME"
  | "PRODUCT_TOOLS_DONT_SUIT_ME"
  | "TOO_EXPENSIVE"
  | "TOO_HARD_TO_USE"
  | "UNSATIFIED_BY_CUSTOMER_SUPPORT";
export const ServiceTerminationReasonEnum = S.String;

export interface ConfirmStorageNetappTerminationRequest {
  /** Service name */
  serviceName: string;
  /** Commentary about your termination request */
  commentary?: string;
  /** All future uses you can provide for a service termination */
  futureUse?: ServiceTerminationFutureUseEnum | (string & {});
  /** All reasons you can provide for a service termination */
  reason?: ServiceTerminationReasonEnum | (string & {});
  /** The termination token sent by email to the admin contact */
  token: string;
}
export const ConfirmStorageNetappTerminationRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    commentary: S.optional(S.String),
    futureUse: S.optional(ServiceTerminationFutureUseEnum),
    reason: S.optional(ServiceTerminationReasonEnum),
    token: S.String,
  }).pipe(
    T.Http({ method: "POST", uri: "/storage/netapp/{serviceName}/confirmTermination", code: 200 }),
  ),
).annotate({
  identifier: "ConfirmStorageNetappTerminationRequest",
}) as any as S.Schema<ConfirmStorageNetappTerminationRequest>;

export type ConfirmStorageNetappTerminationResponse = string;
export const ConfirmStorageNetappTerminationResponse = /*@__PURE__*/ S.suspend(() =>
  S.String.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ConfirmStorageNetappTerminationResponse",
}) as any as S.Schema<ConfirmStorageNetappTerminationResponse>;

export interface CreateStorageNetappChangeContactRequest {
  /** Service name */
  serviceName: string;
  /** The contact to set as admin contact */
  contactAdmin?: string;
  /** The contact to set as billing contact */
  contactBilling?: string;
  /** The contact to set as tech contact */
  contactTech?: string;
}
export const CreateStorageNetappChangeContactRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    contactAdmin: S.optional(S.String),
    contactBilling: S.optional(S.String),
    contactTech: S.optional(S.String),
  }).pipe(
    T.Http({ method: "POST", uri: "/storage/netapp/{serviceName}/changeContact", code: 200 }),
  ),
).annotate({
  identifier: "CreateStorageNetappChangeContactRequest",
}) as any as S.Schema<CreateStorageNetappChangeContactRequest>;

export type CreateStorageNetappChangeContactResponseBodyList = Array<number>;
export const CreateStorageNetappChangeContactResponseBodyList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<CreateStorageNetappChangeContactResponseBodyList>;

export type CreateStorageNetappChangeContactResponse =
  CreateStorageNetappChangeContactResponseBodyList;
export const CreateStorageNetappChangeContactResponse = /*@__PURE__*/ S.suspend(() =>
  CreateStorageNetappChangeContactResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "CreateStorageNetappChangeContactResponse",
}) as any as S.Schema<CreateStorageNetappChangeContactResponse>;

/** ACL permission */
export type StorageNetAppShareACLPermissionEnum = "ro" | "rw";
export const StorageNetAppShareACLPermissionEnum = S.String;

export interface CreateStorageNetappShareAclRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Rule access level */
  accessLevel: StorageNetAppShareACLPermissionEnum | (string & {}) | null;
  /** Rule destination */
  accessTo: string | null;
}
export const CreateStorageNetappShareAclRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    accessLevel: S.NullOr(StorageNetAppShareACLPermissionEnum),
    accessTo: S.NullOr(S.String),
  }).pipe(
    T.Http({ method: "POST", uri: "/storage/netapp/{serviceName}/share/{shareId}/acl", code: 200 }),
  ),
).annotate({
  identifier: "CreateStorageNetappShareAclRequest",
}) as any as S.Schema<CreateStorageNetappShareAclRequest>;

/** ACL type */
export type StorageNetAppShareACLTypeEnum = "ip";
export const StorageNetAppShareACLTypeEnum = S.String;

/** ACL status */
export type StorageNetAppShareACLStatusEnum =
  | "active"
  | "applying"
  | "denying"
  | "error"
  | "queued_to_apply"
  | "queued_to_deny";
export const StorageNetAppShareACLStatusEnum = S.String;

/** A share ACL rule */
export interface StorageNetAppShareACLRule {
  /** Rule access level */
  accessLevel: StorageNetAppShareACLPermissionEnum | null;
  /** Rule destination */
  accessTo: string | null;
  /** Rule access type */
  accessType?: StorageNetAppShareACLTypeEnum | null;
  /** Rule creation date */
  createdAt?: string | null;
  /** Rule ID */
  id?: string;
  /** Rule status */
  status?: StorageNetAppShareACLStatusEnum | null;
}
export const StorageNetAppShareACLRule = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessLevel: S.NullOr(StorageNetAppShareACLPermissionEnum),
    accessTo: S.NullOr(S.String),
    accessType: S.optional(S.NullOr(StorageNetAppShareACLTypeEnum)),
    createdAt: S.optional(S.NullOr(S.String)),
    id: S.optional(S.String),
    status: S.optional(S.NullOr(StorageNetAppShareACLStatusEnum)),
  }),
).annotate({
  identifier: "StorageNetAppShareACLRule",
}) as any as S.Schema<StorageNetAppShareACLRule>;

export interface CreateStorageNetappShareRevertRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Latest share snapshot */
  snapshotID: string;
}
export const CreateStorageNetappShareRevertRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    snapshotID: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/revert",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateStorageNetappShareRevertRequest",
}) as any as S.Schema<CreateStorageNetappShareRevertRequest>;

export interface CreateStorageNetappShareRevertResponse {}
export const CreateStorageNetappShareRevertResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "CreateStorageNetappShareRevertResponse",
}) as any as S.Schema<CreateStorageNetappShareRevertResponse>;

export interface CreateStorageNetappShareShrinkRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Share size in Gigabytes */
  size: number | null;
}
export const CreateStorageNetappShareShrinkRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    size: S.NullOr(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/shrink",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateStorageNetappShareShrinkRequest",
}) as any as S.Schema<CreateStorageNetappShareShrinkRequest>;

export interface CreateStorageNetappShareShrinkResponse {}
export const CreateStorageNetappShareShrinkResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "CreateStorageNetappShareShrinkResponse",
}) as any as S.Schema<CreateStorageNetappShareShrinkResponse>;

export interface CreateStorageNetappShareSnapshotRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Snapshot description */
  description?: string | null;
  /** Snapshot name */
  name?: string | null;
}
export const CreateStorageNetappShareSnapshotRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    description: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshot",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateStorageNetappShareSnapshotRequest",
}) as any as S.Schema<CreateStorageNetappShareSnapshotRequest>;

/** Snapshot status */
export type StorageNetAppSnapshotStatusEnum =
  | "available"
  | "creating"
  | "deleting"
  | "error"
  | "error_deleting"
  | "manage_error"
  | "manage_starting"
  | "restoring"
  | "unmanage_error"
  | "unmanage_starting";
export const StorageNetAppSnapshotStatusEnum = S.String;

/** Snapshot type */
export type StorageNetAppSnapshotTypeEnum = "automatic" | "manual" | "system";
export const StorageNetAppSnapshotTypeEnum = S.String;

/** A share snapshot */
export interface StorageNetAppShareSnapshot {
  /** Snapshot creation date */
  createdAt?: string | null;
  /** Snapshot description */
  description?: string | null;
  /** Snapshot ID */
  id?: string;
  /** Snapshot name */
  name?: string | null;
  /** Snapshot path */
  path?: string | null;
  /** Snapshot status */
  status?: StorageNetAppSnapshotStatusEnum | null;
  /** Snapshot type */
  type?: StorageNetAppSnapshotTypeEnum | null;
}
export const StorageNetAppShareSnapshot = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.NullOr(S.String)),
    description: S.optional(S.NullOr(S.String)),
    id: S.optional(S.String),
    name: S.optional(S.NullOr(S.String)),
    path: S.optional(S.NullOr(S.String)),
    status: S.optional(S.NullOr(StorageNetAppSnapshotStatusEnum)),
    type: S.optional(S.NullOr(StorageNetAppSnapshotTypeEnum)),
  }),
).annotate({
  identifier: "StorageNetAppShareSnapshot",
}) as any as S.Schema<StorageNetAppShareSnapshot>;

export interface CreateStorageNetappShareSnapshotHoldRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Snapshot ID */
  snapshotId: string;
}
export const CreateStorageNetappShareSnapshotHoldRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    snapshotId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshot/{snapshotId}/hold",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateStorageNetappShareSnapshotHoldRequest",
}) as any as S.Schema<CreateStorageNetappShareSnapshotHoldRequest>;

/** The days of the month the schedule runs (1 through 31). Empty for all. */
export type StorageNetAppSnapshotPolicyScheduleDaysList = Array<number>;
export const StorageNetAppSnapshotPolicyScheduleDaysList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<StorageNetAppSnapshotPolicyScheduleDaysList>;

/** The hours of the day the schedule runs (0 through 23). Empty for all. */
export type StorageNetAppSnapshotPolicyScheduleHoursList = Array<number>;
export const StorageNetAppSnapshotPolicyScheduleHoursList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<StorageNetAppSnapshotPolicyScheduleHoursList>;

/** The minutes the schedule runs (0 through 59). Required to have at least one value. */
export type StorageNetAppSnapshotPolicyScheduleMinutesList = Array<number>;
export const StorageNetAppSnapshotPolicyScheduleMinutesList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<StorageNetAppSnapshotPolicyScheduleMinutesList>;

/** The months of the year the schedule runs (1 through 12). Empty for all. */
export type StorageNetAppSnapshotPolicyScheduleMonthsList = Array<number>;
export const StorageNetAppSnapshotPolicyScheduleMonthsList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<StorageNetAppSnapshotPolicyScheduleMonthsList>;

/** The days of the week the schedule runs (0 through 6, where 0 is Sunday and 6 is Saturday). Empty for all. */
export type StorageNetAppSnapshotPolicyScheduleWeekdaysList = Array<number>;
export const StorageNetAppSnapshotPolicyScheduleWeekdaysList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<StorageNetAppSnapshotPolicyScheduleWeekdaysList>;

/** A snapshot policy schedule */
export interface StorageNetAppSnapshotPolicySchedule {
  /** The days of the month the schedule runs (1 through 31). Empty for all. */
  days?: StorageNetAppSnapshotPolicyScheduleDaysList | null;
  /** The hours of the day the schedule runs (0 through 23). Empty for all. */
  hours?: StorageNetAppSnapshotPolicyScheduleHoursList | null;
  /** The minutes the schedule runs (0 through 59). Required to have at least one value. */
  minutes: StorageNetAppSnapshotPolicyScheduleMinutesList;
  /** The months of the year the schedule runs (1 through 12). Empty for all. */
  months?: StorageNetAppSnapshotPolicyScheduleMonthsList | null;
  /** The days of the week the schedule runs (0 through 6, where 0 is Sunday and 6 is Saturday). Empty for all. */
  weekdays?: StorageNetAppSnapshotPolicyScheduleWeekdaysList | null;
}
export const StorageNetAppSnapshotPolicySchedule = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    days: S.optional(S.NullOr(StorageNetAppSnapshotPolicyScheduleDaysList)),
    hours: S.optional(S.NullOr(StorageNetAppSnapshotPolicyScheduleHoursList)),
    minutes: StorageNetAppSnapshotPolicyScheduleMinutesList,
    months: S.optional(S.NullOr(StorageNetAppSnapshotPolicyScheduleMonthsList)),
    weekdays: S.optional(S.NullOr(StorageNetAppSnapshotPolicyScheduleWeekdaysList)),
  }),
).annotate({
  identifier: "StorageNetAppSnapshotPolicySchedule",
}) as any as S.Schema<StorageNetAppSnapshotPolicySchedule>;

/** A snapshot policy rule */
export interface StorageNetAppSnapshotPolicyRule {
  /** Number of snapshot copies to keep */
  copies: number | null;
  /** Prefix to use for snapshots */
  prefix: string | null;
  /** Snapshot policy schedule */
  schedule: StorageNetAppSnapshotPolicySchedule | null;
}
export const StorageNetAppSnapshotPolicyRule = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    copies: S.NullOr(S.Number),
    prefix: S.NullOr(S.String),
    schedule: S.NullOr(StorageNetAppSnapshotPolicySchedule),
  }),
).annotate({
  identifier: "StorageNetAppSnapshotPolicyRule",
}) as any as S.Schema<StorageNetAppSnapshotPolicyRule>;

/** Snapshot policy rules */
export type CreateStorageNetappSnapshotPolicyRequestRulesList =
  Array<StorageNetAppSnapshotPolicyRule>;
export const CreateStorageNetappSnapshotPolicyRequestRulesList = /*@__PURE__*/ S.Array(
  StorageNetAppSnapshotPolicyRule,
) as any as S.Schema<CreateStorageNetappSnapshotPolicyRequestRulesList>;

export interface CreateStorageNetappSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
  /** Snapshot policy description */
  description?: string | null;
  /** Snapshot policy name */
  name?: string | null;
  /** Snapshot policy rules */
  rules: CreateStorageNetappSnapshotPolicyRequestRulesList | null;
}
export const CreateStorageNetappSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    description: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
    rules: S.NullOr(CreateStorageNetappSnapshotPolicyRequestRulesList),
  }).pipe(
    T.Http({ method: "POST", uri: "/storage/netapp/{serviceName}/snapshotPolicy", code: 200 }),
  ),
).annotate({
  identifier: "CreateStorageNetappSnapshotPolicyRequest",
}) as any as S.Schema<CreateStorageNetappSnapshotPolicyRequest>;

/** Snapshot policy rules */
export type StorageNetAppSnapshotPolicyRulesList = Array<StorageNetAppSnapshotPolicyRule>;
export const StorageNetAppSnapshotPolicyRulesList = /*@__PURE__*/ S.Array(
  StorageNetAppSnapshotPolicyRule,
) as any as S.Schema<StorageNetAppSnapshotPolicyRulesList>;

/** Snapshot policy status */
export type StorageNetAppSnapshotPolicyStatusEnum =
  | "available"
  | "creating"
  | "deleting"
  | "error"
  | "updating";
export const StorageNetAppSnapshotPolicyStatusEnum = S.String;

/** A snapshot policy */
export interface StorageNetAppSnapshotPolicy {
  /** Snapshot policy creation date */
  createdAt?: string | null;
  /** Snapshot policy description */
  description?: string | null;
  /** Snapshot policy ID */
  id?: string;
  /** Is this the default snapshot policy? */
  isDefault?: boolean | null;
  /** Snapshot policy name */
  name?: string | null;
  /** Snapshot policy rules */
  rules: StorageNetAppSnapshotPolicyRulesList | null;
  /** Snapshot policy status */
  status?: StorageNetAppSnapshotPolicyStatusEnum | null;
}
export const StorageNetAppSnapshotPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.NullOr(S.String)),
    description: S.optional(S.NullOr(S.String)),
    id: S.optional(S.String),
    isDefault: S.optional(S.NullOr(S.Boolean)),
    name: S.optional(S.NullOr(S.String)),
    rules: S.NullOr(StorageNetAppSnapshotPolicyRulesList),
    status: S.optional(S.NullOr(StorageNetAppSnapshotPolicyStatusEnum)),
  }),
).annotate({
  identifier: "StorageNetAppSnapshotPolicy",
}) as any as S.Schema<StorageNetAppSnapshotPolicy>;

export interface DeleteStorageNetappShareRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
}
export const DeleteStorageNetappShareRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "DELETE", uri: "/storage/netapp/{serviceName}/share/{shareId}", code: 200 }),
  ),
).annotate({
  identifier: "DeleteStorageNetappShareRequest",
}) as any as S.Schema<DeleteStorageNetappShareRequest>;

export interface DeleteStorageNetappShareResponse {}
export const DeleteStorageNetappShareResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteStorageNetappShareResponse",
}) as any as S.Schema<DeleteStorageNetappShareResponse>;

export interface DeleteStorageNetappShareAclRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Acl rule ID */
  aclRuleId: string;
}
export const DeleteStorageNetappShareAclRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    aclRuleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/acl/{aclRuleId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteStorageNetappShareAclRequest",
}) as any as S.Schema<DeleteStorageNetappShareAclRequest>;

export interface DeleteStorageNetappShareAclResponse {}
export const DeleteStorageNetappShareAclResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteStorageNetappShareAclResponse",
}) as any as S.Schema<DeleteStorageNetappShareAclResponse>;

export interface DeleteStorageNetappShareSnapshotRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Snapshot ID */
  snapshotId: string;
}
export const DeleteStorageNetappShareSnapshotRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    snapshotId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshot/{snapshotId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteStorageNetappShareSnapshotRequest",
}) as any as S.Schema<DeleteStorageNetappShareSnapshotRequest>;

export interface DeleteStorageNetappShareSnapshotResponse {}
export const DeleteStorageNetappShareSnapshotResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteStorageNetappShareSnapshotResponse",
}) as any as S.Schema<DeleteStorageNetappShareSnapshotResponse>;

export interface DeleteStorageNetappSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
  /** Snapshot policy ID */
  snapshotPolicyId: string;
}
export const DeleteStorageNetappSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    snapshotPolicyId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/storage/netapp/{serviceName}/snapshotPolicy/{snapshotPolicyId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteStorageNetappSnapshotPolicyRequest",
}) as any as S.Schema<DeleteStorageNetappSnapshotPolicyRequest>;

export interface DeleteStorageNetappSnapshotPolicyResponse {}
export const DeleteStorageNetappSnapshotPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteStorageNetappSnapshotPolicyResponse",
}) as any as S.Schema<DeleteStorageNetappSnapshotPolicyResponse>;

export interface ExtendStorageNetappShareRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Share size in Gigabytes */
  size: number | null;
}
export const ExtendStorageNetappShareRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    size: S.NullOr(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/extend",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ExtendStorageNetappShareRequest",
}) as any as S.Schema<ExtendStorageNetappShareRequest>;

export interface ExtendStorageNetappShareResponse {}
export const ExtendStorageNetappShareResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "ExtendStorageNetappShareResponse",
}) as any as S.Schema<ExtendStorageNetappShareResponse>;

export interface GetStorageNetappRequest {
  /** Service name */
  serviceName: string;
}
export const GetStorageNetappRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}", code: 200 })),
).annotate({ identifier: "GetStorageNetappRequest" }) as any as S.Schema<GetStorageNetappRequest>;

/** Resource tags. Tags that were internally computed are prefixed with ovh: */
export type IamResourceMetadataTagsMap = { [key: string]: string | undefined };
export const IamResourceMetadataTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<IamResourceMetadataTagsMap>;

/** IAM resource metadata embedded in services models */
export interface IamResourceMetadata {
  /** Resource display name */
  displayName?: string | null;
  /** Unique identifier of the resource */
  id?: string;
  /** Resource tags. Tags that were internally computed are prefixed with ovh: */
  tags?: IamResourceMetadataTagsMap | null;
  /** Unique resource name used in policies */
  urn?: string;
}
export const IamResourceMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    displayName: S.optional(S.NullOr(S.String)),
    id: S.optional(S.String),
    tags: S.optional(S.NullOr(IamResourceMetadataTagsMap)),
    urn: S.optional(S.String),
  }),
).annotate({ identifier: "IamResourceMetadata" }) as any as S.Schema<IamResourceMetadata>;

/** Service performance level */
export type StorageNetAppServicePerformanceLevelEnum = "premium";
export const StorageNetAppServicePerformanceLevelEnum = S.String;

/** Region of customer's service */
export type StorageRegionEnum =
  | "ca-east-bhs"
  | "eu-west-gra"
  | "eu-west-lim"
  | "eu-west-rbx"
  | "eu-west-sbg";
export const StorageRegionEnum = S.String;

/** Service status */
export type StorageNetAppServiceStatusEnum =
  | "creating"
  | "deleted"
  | "deleting"
  | "reopening"
  | "running"
  | "suspended"
  | "suspending";
export const StorageNetAppServiceStatusEnum = S.String;

/** A service */
export interface StorageNetAppServiceWithIAM {
  /** Service creation date */
  createdAt?: string;
  /** IAM resource metadata */
  iam?: IamResourceMetadata | null;
  /** Service ID */
  id?: string;
  /** Service name */
  name?: string;
  /** Service performance level */
  performanceLevel?: StorageNetAppServicePerformanceLevelEnum;
  /** Product name */
  product?: string;
  /** Service quota */
  quota?: number;
  /** Service region */
  region?: StorageRegionEnum;
  /** Service status */
  status?: StorageNetAppServiceStatusEnum;
}
export const StorageNetAppServiceWithIAM = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.String),
    iam: S.optional(S.NullOr(IamResourceMetadata)),
    id: S.optional(S.String),
    name: S.optional(S.String),
    performanceLevel: S.optional(StorageNetAppServicePerformanceLevelEnum),
    product: S.optional(S.String),
    quota: S.optional(S.Number),
    region: S.optional(StorageRegionEnum),
    status: S.optional(StorageNetAppServiceStatusEnum),
  }),
).annotate({
  identifier: "StorageNetAppServiceWithIAM",
}) as any as S.Schema<StorageNetAppServiceWithIAM>;

export interface GetStorageNetappMetricsTokenRequest {
  /** Service name */
  serviceName: string;
}
export const GetStorageNetappMetricsTokenRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/metricsToken", code: 200 })),
).annotate({
  identifier: "GetStorageNetappMetricsTokenRequest",
}) as any as S.Schema<GetStorageNetappMetricsTokenRequest>;

/** Metrics token */
export interface StorageMetricsToken {
  /** Backend url */
  endpoint?: string;
  /** Token expiration date */
  expiry?: string;
  /** Generated token */
  token?: string;
}
export const StorageMetricsToken = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpoint: S.optional(S.String),
    expiry: S.optional(S.String),
    token: S.optional(S.String),
  }),
).annotate({ identifier: "StorageMetricsToken" }) as any as S.Schema<StorageMetricsToken>;

export interface GetStorageNetappNetworkRequest {
  /** Service name */
  serviceName: string;
  /** Network ID */
  networkId: string;
}
export const GetStorageNetappNetworkRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    networkId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/network/{networkId}", code: 200 }),
  ),
).annotate({
  identifier: "GetStorageNetappNetworkRequest",
}) as any as S.Schema<GetStorageNetappNetworkRequest>;

/** Network status */
export type StorageNetAppNetworkStatusEnum =
  | "associated"
  | "associating"
  | "dissociating"
  | "to_configure";
export const StorageNetAppNetworkStatusEnum = S.String;

/** A network */
export interface StorageNetAppNetwork {
  /** Network ID */
  id?: string;
  /** Network status */
  status?: StorageNetAppNetworkStatusEnum | null;
  /** vRack Services URN the network is attached to */
  vRackServicesURN?: string | null;
}
export const StorageNetAppNetwork = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    status: S.optional(S.NullOr(StorageNetAppNetworkStatusEnum)),
    vRackServicesURN: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "StorageNetAppNetwork" }) as any as S.Schema<StorageNetAppNetwork>;

export interface GetStorageNetappServiceInfosRequest {
  /** Service name */
  serviceName: string;
}
export const GetStorageNetappServiceInfosRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/serviceInfos", code: 200 })),
).annotate({
  identifier: "GetStorageNetappServiceInfosRequest",
}) as any as S.Schema<GetStorageNetappServiceInfosRequest>;

/** All the possible renew period of your service in month */
export type ServicesServicePossibleRenewPeriodList = Array<number>;
export const ServicesServicePossibleRenewPeriodList = /*@__PURE__*/ S.Array(
  S.Number,
) as any as S.Schema<ServicesServicePossibleRenewPeriodList>;

/** Map a possible renew for a specific service */
export interface ServiceRenewType {
  /** The service is automatically renewed */
  automatic?: boolean;
  /** The service will be deleted at expiration */
  deleteAtExpiration?: boolean;
  /** The service forced to be renewed */
  forced?: boolean;
  /** The service needs to be manually renewed and paid */
  manualPayment?: boolean | null;
  /** period of renew in month */
  period?: number | null;
}
export const ServiceRenewType = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    automatic: S.optional(S.Boolean),
    deleteAtExpiration: S.optional(S.Boolean),
    forced: S.optional(S.Boolean),
    manualPayment: S.optional(S.NullOr(S.Boolean)),
    period: S.optional(S.NullOr(S.Number)),
  }),
).annotate({ identifier: "ServiceRenewType" }) as any as S.Schema<ServiceRenewType>;

/** Detailed renewal type of a service */
export type ServiceRenewalTypeEnum =
  | "automaticForcedProduct"
  | "automaticV2012"
  | "automaticV2014"
  | "automaticV2016"
  | "manual"
  | "oneShot"
  | "option";
export const ServiceRenewalTypeEnum = S.String;

/** service.StateEnum */
export type ServiceStateEnum =
  | "autorenewInProgress"
  | "expired"
  | "inCreation"
  | "ok"
  | "pendingDebt"
  | "unPaid";
export const ServiceStateEnum = S.String;

/** Details about a Service */
export interface ServicesService {
  /** Indicates that the service can be set up to be deleted at expiration */
  canDeleteAtExpiration?: boolean;
  contactAdmin?: string;
  contactBilling?: string;
  contactTech?: string;
  creation?: string;
  domain?: string;
  engagedUpTo?: string | null;
  expiration?: string;
  /** All the possible renew period of your service in month */
  possibleRenewPeriod?: ServicesServicePossibleRenewPeriodList | null;
  /** Way of handling the renew */
  renew?: ServiceRenewType | null;
  renewalType?: ServiceRenewalTypeEnum;
  serviceId?: number;
  status?: ServiceStateEnum;
}
export const ServicesService = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    canDeleteAtExpiration: S.optional(S.Boolean),
    contactAdmin: S.optional(S.String),
    contactBilling: S.optional(S.String),
    contactTech: S.optional(S.String),
    creation: S.optional(S.String),
    domain: S.optional(S.String),
    engagedUpTo: S.optional(S.NullOr(S.String)),
    expiration: S.optional(S.String),
    possibleRenewPeriod: S.optional(S.NullOr(ServicesServicePossibleRenewPeriodList)),
    renew: S.optional(S.NullOr(ServiceRenewType)),
    renewalType: S.optional(ServiceRenewalTypeEnum),
    serviceId: S.optional(S.Number),
    status: S.optional(ServiceStateEnum),
  }),
).annotate({ identifier: "ServicesService" }) as any as S.Schema<ServicesService>;

export interface GetStorageNetappShareRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
}
export const GetStorageNetappShareRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/share/{shareId}", code: 200 }),
  ),
).annotate({
  identifier: "GetStorageNetappShareRequest",
}) as any as S.Schema<GetStorageNetappShareRequest>;

/** Storage protocol */
export type StorageProtocolEnum = "NFS";
export const StorageProtocolEnum = S.String;

/** Share status */
export type StorageNetAppShareStatusEnum =
  | "available"
  | "creating"
  | "creating_from_snapshot"
  | "deleted"
  | "deleting"
  | "error"
  | "error_deleting"
  | "extending"
  | "extending_error"
  | "inactive"
  | "manage_error"
  | "manage_starting"
  | "migrating"
  | "migrating_to"
  | "replication_change"
  | "reverting"
  | "reverting_error"
  | "shrinking"
  | "shrinking_error"
  | "shrinking_possible_data_loss_error"
  | "unmanage_error"
  | "unmanage_starting"
  | "unmanaged";
export const StorageNetAppShareStatusEnum = S.String;

/** A share */
export interface StorageNetAppShare {
  /** Share creation date */
  createdAt?: string | null;
  /** Share description */
  description?: string | null;
  /** Share ID */
  id?: string;
  /** User-defined name used to generate human readable access path for the share */
  mountPointName?: string | null;
  /** Share name */
  name?: string | null;
  /** Share protocol */
  protocol: StorageProtocolEnum | null;
  /** Share size in Gigabytes */
  size: number | null;
  /** Snapshot ID used to create the share */
  snapshotID?: string | null;
  /** Share status */
  status?: StorageNetAppShareStatusEnum | null;
}
export const StorageNetAppShare = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.NullOr(S.String)),
    description: S.optional(S.NullOr(S.String)),
    id: S.optional(S.String),
    mountPointName: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
    protocol: S.NullOr(StorageProtocolEnum),
    size: S.NullOr(S.Number),
    snapshotID: S.optional(S.NullOr(S.String)),
    status: S.optional(S.NullOr(StorageNetAppShareStatusEnum)),
  }),
).annotate({ identifier: "StorageNetAppShare" }) as any as S.Schema<StorageNetAppShare>;

export interface GetStorageNetappShareAccessPathRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Access path ID */
  accessPathId: string;
}
export const GetStorageNetappShareAccessPathRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    accessPathId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/accessPath/{accessPathId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStorageNetappShareAccessPathRequest",
}) as any as S.Schema<GetStorageNetappShareAccessPathRequest>;

/** A share access path */
export interface StorageNetAppShareAccessPath {
  /** Access path ID */
  id?: string;
  /** Access path */
  path?: string;
  /** Is this the preferred access path? */
  preferred?: boolean;
}
export const StorageNetAppShareAccessPath = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    path: S.optional(S.String),
    preferred: S.optional(S.Boolean),
  }),
).annotate({
  identifier: "StorageNetAppShareAccessPath",
}) as any as S.Schema<StorageNetAppShareAccessPath>;

export interface GetStorageNetappShareAclRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Acl rule ID */
  aclRuleId: string;
}
export const GetStorageNetappShareAclRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    aclRuleId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/acl/{aclRuleId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStorageNetappShareAclRequest",
}) as any as S.Schema<GetStorageNetappShareAclRequest>;

export interface GetStorageNetappShareSnapshotRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Snapshot ID */
  snapshotId: string;
}
export const GetStorageNetappShareSnapshotRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    snapshotId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshot/{snapshotId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStorageNetappShareSnapshotRequest",
}) as any as S.Schema<GetStorageNetappShareSnapshotRequest>;

export interface GetStorageNetappShareSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
}
export const GetStorageNetappShareSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshotPolicy",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStorageNetappShareSnapshotPolicyRequest",
}) as any as S.Schema<GetStorageNetappShareSnapshotPolicyRequest>;

/** Association status between the share and the snapshot policy */
export type StorageNetAppShareSnapshotPolicyStatusEnum = "active" | "error" | "updating";
export const StorageNetAppShareSnapshotPolicyStatusEnum = S.String;

/** A snapshot policy */
export interface StorageNetAppShareSnapshotPolicy {
  /** Snapshot policy ID */
  id?: string;
  /** Association status between the share and the snapshot policy */
  status?: StorageNetAppShareSnapshotPolicyStatusEnum;
}
export const StorageNetAppShareSnapshotPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    status: S.optional(StorageNetAppShareSnapshotPolicyStatusEnum),
  }),
).annotate({
  identifier: "StorageNetAppShareSnapshotPolicy",
}) as any as S.Schema<StorageNetAppShareSnapshotPolicy>;

export interface GetStorageNetappShareSnapshotReserveRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
}
export const GetStorageNetappShareSnapshotReserveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshotReserve",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStorageNetappShareSnapshotReserveRequest",
}) as any as S.Schema<GetStorageNetappShareSnapshotReserveRequest>;

/** Snapshot reserve properties status */
export type StorageNetAppShareSnapshotReserveStatusEnum = "active" | "error" | "updating";
export const StorageNetAppShareSnapshotReserveStatusEnum = S.String;

/** Snapshot reserve properties */
export interface StorageNetAppShareSnapshotReserve {
  /** Share space percentage reserved for snapshots */
  percent?: number;
  /** Status */
  status?: StorageNetAppShareSnapshotReserveStatusEnum;
}
export const StorageNetAppShareSnapshotReserve = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    percent: S.optional(S.Number),
    status: S.optional(StorageNetAppShareSnapshotReserveStatusEnum),
  }),
).annotate({
  identifier: "StorageNetAppShareSnapshotReserve",
}) as any as S.Schema<StorageNetAppShareSnapshotReserve>;

export interface GetStorageNetappSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
  /** Snapshot policy ID */
  snapshotPolicyId: string;
}
export const GetStorageNetappSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    snapshotPolicyId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/snapshotPolicy/{snapshotPolicyId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStorageNetappSnapshotPolicyRequest",
}) as any as S.Schema<GetStorageNetappSnapshotPolicyRequest>;

/** Resource tag filter */
export interface IamResourceTagFilterInput {}
export const IamResourceTagFilterInput = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "IamResourceTagFilterInput",
}) as any as S.Schema<IamResourceTagFilterInput>;

export type ListStorageNetappRequestIamTagsValueList = Array<IamResourceTagFilterInput>;
export const ListStorageNetappRequestIamTagsValueList = /*@__PURE__*/ S.Array(
  IamResourceTagFilterInput,
) as any as S.Schema<ListStorageNetappRequestIamTagsValueList>;

export type ListStorageNetappRequestIamTagsMap = {
  [key: string]: ListStorageNetappRequestIamTagsValueList | undefined;
};
export const ListStorageNetappRequestIamTagsMap = /*@__PURE__*/ S.Record(
  S.String,
  ListStorageNetappRequestIamTagsValueList,
) as any as S.Schema<ListStorageNetappRequestIamTagsMap>;

export interface ListStorageNetappRequest {
  /** Filter resources on IAM tags */
  iamTags?: ListStorageNetappRequestIamTagsMap;
}
export const ListStorageNetappRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    iamTags: S.optional(ListStorageNetappRequestIamTagsMap.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/storage/netapp", code: 200 })),
).annotate({ identifier: "ListStorageNetappRequest" }) as any as S.Schema<ListStorageNetappRequest>;

export type ListStorageNetappResponseBodyList = Array<StorageNetAppServiceWithIAM>;
export const ListStorageNetappResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppServiceWithIAM,
) as any as S.Schema<ListStorageNetappResponseBodyList>;

export type ListStorageNetappResponse = ListStorageNetappResponseBodyList;
export const ListStorageNetappResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappResponse",
}) as any as S.Schema<ListStorageNetappResponse>;

export interface ListStorageNetappNetworkRequest {
  /** Service name */
  serviceName: string;
  /** Get detailed information about each network */
  detail?: boolean;
}
export const ListStorageNetappNetworkRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    detail: S.optional(S.Boolean.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/network", code: 200 })),
).annotate({
  identifier: "ListStorageNetappNetworkRequest",
}) as any as S.Schema<ListStorageNetappNetworkRequest>;

export type ListStorageNetappNetworkResponseBodyList = Array<StorageNetAppNetwork>;
export const ListStorageNetappNetworkResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppNetwork,
) as any as S.Schema<ListStorageNetappNetworkResponseBodyList>;

export type ListStorageNetappNetworkResponse = ListStorageNetappNetworkResponseBodyList;
export const ListStorageNetappNetworkResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappNetworkResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappNetworkResponse",
}) as any as S.Schema<ListStorageNetappNetworkResponse>;

export interface ListStorageNetappShareRequest {
  /** Service name */
  serviceName: string;
  /** Get detailed information about each share */
  detail?: boolean;
  /** If specified, returns only shares with given mount point name */
  mountPointName?: string;
}
export const ListStorageNetappShareRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    detail: S.optional(S.Boolean.pipe(T.Query())),
    mountPointName: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/share", code: 200 })),
).annotate({
  identifier: "ListStorageNetappShareRequest",
}) as any as S.Schema<ListStorageNetappShareRequest>;

export type ListStorageNetappShareResponseBodyList = Array<StorageNetAppShare>;
export const ListStorageNetappShareResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppShare,
) as any as S.Schema<ListStorageNetappShareResponseBodyList>;

export type ListStorageNetappShareResponse = ListStorageNetappShareResponseBodyList;
export const ListStorageNetappShareResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappShareResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappShareResponse",
}) as any as S.Schema<ListStorageNetappShareResponse>;

export interface ListStorageNetappShareAccessPathRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
}
export const ListStorageNetappShareAccessPathRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/accessPath",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListStorageNetappShareAccessPathRequest",
}) as any as S.Schema<ListStorageNetappShareAccessPathRequest>;

export type ListStorageNetappShareAccessPathResponseBodyList = Array<StorageNetAppShareAccessPath>;
export const ListStorageNetappShareAccessPathResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppShareAccessPath,
) as any as S.Schema<ListStorageNetappShareAccessPathResponseBodyList>;

export type ListStorageNetappShareAccessPathResponse =
  ListStorageNetappShareAccessPathResponseBodyList;
export const ListStorageNetappShareAccessPathResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappShareAccessPathResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappShareAccessPathResponse",
}) as any as S.Schema<ListStorageNetappShareAccessPathResponse>;

export interface ListStorageNetappShareAclRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
}
export const ListStorageNetappShareAclRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/share/{shareId}/acl", code: 200 }),
  ),
).annotate({
  identifier: "ListStorageNetappShareAclRequest",
}) as any as S.Schema<ListStorageNetappShareAclRequest>;

export type ListStorageNetappShareAclResponseBodyList = Array<StorageNetAppShareACLRule>;
export const ListStorageNetappShareAclResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppShareACLRule,
) as any as S.Schema<ListStorageNetappShareAclResponseBodyList>;

export type ListStorageNetappShareAclResponse = ListStorageNetappShareAclResponseBodyList;
export const ListStorageNetappShareAclResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappShareAclResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappShareAclResponse",
}) as any as S.Schema<ListStorageNetappShareAclResponse>;

export interface ListStorageNetappShareSnapshotRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Get detailed information about each snapshot */
  detail?: boolean;
}
export const ListStorageNetappShareSnapshotRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    detail: S.optional(S.Boolean.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshot",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListStorageNetappShareSnapshotRequest",
}) as any as S.Schema<ListStorageNetappShareSnapshotRequest>;

export type ListStorageNetappShareSnapshotResponseBodyList = Array<StorageNetAppShareSnapshot>;
export const ListStorageNetappShareSnapshotResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppShareSnapshot,
) as any as S.Schema<ListStorageNetappShareSnapshotResponseBodyList>;

export type ListStorageNetappShareSnapshotResponse = ListStorageNetappShareSnapshotResponseBodyList;
export const ListStorageNetappShareSnapshotResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappShareSnapshotResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappShareSnapshotResponse",
}) as any as S.Schema<ListStorageNetappShareSnapshotResponse>;

export interface ListStorageNetappSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
}
export const ListStorageNetappSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/storage/netapp/{serviceName}/snapshotPolicy", code: 200 }),
  ),
).annotate({
  identifier: "ListStorageNetappSnapshotPolicyRequest",
}) as any as S.Schema<ListStorageNetappSnapshotPolicyRequest>;

export type ListStorageNetappSnapshotPolicyResponseBodyList = Array<StorageNetAppSnapshotPolicy>;
export const ListStorageNetappSnapshotPolicyResponseBodyList = /*@__PURE__*/ S.Array(
  StorageNetAppSnapshotPolicy,
) as any as S.Schema<ListStorageNetappSnapshotPolicyResponseBodyList>;

export type ListStorageNetappSnapshotPolicyResponse =
  ListStorageNetappSnapshotPolicyResponseBodyList;
export const ListStorageNetappSnapshotPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  ListStorageNetappSnapshotPolicyResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListStorageNetappSnapshotPolicyResponse",
}) as any as S.Schema<ListStorageNetappSnapshotPolicyResponse>;

export interface PutStorageNetappRequest {
  /** Service name */
  serviceName: string;
  /** New service name */
  name: string;
}
export const PutStorageNetappRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    name: S.String,
  }).pipe(T.Http({ method: "PUT", uri: "/storage/netapp/{serviceName}", code: 200 })),
).annotate({ identifier: "PutStorageNetappRequest" }) as any as S.Schema<PutStorageNetappRequest>;

/** A service */
export interface StorageNetAppService {
  /** Service creation date */
  createdAt?: string;
  /** Service ID */
  id?: string;
  /** Service name */
  name?: string;
  /** Service performance level */
  performanceLevel?: StorageNetAppServicePerformanceLevelEnum;
  /** Product name */
  product?: string;
  /** Service quota */
  quota?: number;
  /** Service region */
  region?: StorageRegionEnum;
  /** Service status */
  status?: StorageNetAppServiceStatusEnum;
}
export const StorageNetAppService = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.String),
    id: S.optional(S.String),
    name: S.optional(S.String),
    performanceLevel: S.optional(StorageNetAppServicePerformanceLevelEnum),
    product: S.optional(S.String),
    quota: S.optional(S.Number),
    region: S.optional(StorageRegionEnum),
    status: S.optional(StorageNetAppServiceStatusEnum),
  }),
).annotate({ identifier: "StorageNetAppService" }) as any as S.Schema<StorageNetAppService>;

export interface PutStorageNetappServiceInfosRequest {
  /** Service name */
  serviceName: string;
  /** Way of handling the renew */
  renew?: ServiceRenewType | null;
}
export const PutStorageNetappServiceInfosRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    renew: S.optional(S.NullOr(ServiceRenewType)),
  }).pipe(T.Http({ method: "PUT", uri: "/storage/netapp/{serviceName}/serviceInfos", code: 200 })),
).annotate({
  identifier: "PutStorageNetappServiceInfosRequest",
}) as any as S.Schema<PutStorageNetappServiceInfosRequest>;

export interface PutStorageNetappServiceInfosResponse {}
export const PutStorageNetappServiceInfosResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PutStorageNetappServiceInfosResponse",
}) as any as S.Schema<PutStorageNetappServiceInfosResponse>;

export interface PutStorageNetappShareRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** New share description */
  description?: string | null;
  /** New share name */
  name?: string | null;
}
export const PutStorageNetappShareRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    description: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({ method: "PUT", uri: "/storage/netapp/{serviceName}/share/{shareId}", code: 200 }),
  ),
).annotate({
  identifier: "PutStorageNetappShareRequest",
}) as any as S.Schema<PutStorageNetappShareRequest>;

export interface PutStorageNetappShareSnapshotRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Snapshot ID */
  snapshotId: string;
  /** New snapshot description */
  description?: string | null;
  /** New snapshot name */
  name?: string | null;
}
export const PutStorageNetappShareSnapshotRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    snapshotId: S.String.pipe(T.Label()),
    description: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshot/{snapshotId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PutStorageNetappShareSnapshotRequest",
}) as any as S.Schema<PutStorageNetappShareSnapshotRequest>;

export interface PutStorageNetappShareSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Snapshot policy ID */
  snapshotPolicyID: string;
}
export const PutStorageNetappShareSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    snapshotPolicyID: S.String,
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshotPolicy",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PutStorageNetappShareSnapshotPolicyRequest",
}) as any as S.Schema<PutStorageNetappShareSnapshotPolicyRequest>;

export interface PutStorageNetappShareSnapshotPolicyResponse {}
export const PutStorageNetappShareSnapshotPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PutStorageNetappShareSnapshotPolicyResponse",
}) as any as S.Schema<PutStorageNetappShareSnapshotPolicyResponse>;

export interface PutStorageNetappShareSnapshotReserveRequest {
  /** Service name */
  serviceName: string;
  /** Share ID */
  shareId: string;
  /** Share space percentage reserved for snapshots */
  percent: number;
}
export const PutStorageNetappShareSnapshotReserveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    shareId: S.String.pipe(T.Label()),
    percent: S.Number,
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/storage/netapp/{serviceName}/share/{shareId}/snapshotReserve",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PutStorageNetappShareSnapshotReserveRequest",
}) as any as S.Schema<PutStorageNetappShareSnapshotReserveRequest>;

export interface PutStorageNetappShareSnapshotReserveResponse {}
export const PutStorageNetappShareSnapshotReserveResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PutStorageNetappShareSnapshotReserveResponse",
}) as any as S.Schema<PutStorageNetappShareSnapshotReserveResponse>;

export interface PutStorageNetappSnapshotPolicyRequest {
  /** Service name */
  serviceName: string;
  /** Snapshot policy ID */
  snapshotPolicyId: string;
  /** New snapshot policy description */
  description?: string | null;
  /** New snapshot policy name */
  name?: string | null;
}
export const PutStorageNetappSnapshotPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    snapshotPolicyId: S.String.pipe(T.Label()),
    description: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/storage/netapp/{serviceName}/snapshotPolicy/{snapshotPolicyId}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PutStorageNetappSnapshotPolicyRequest",
}) as any as S.Schema<PutStorageNetappSnapshotPolicyRequest>;

export interface PutStorageNetappSnapshotPolicyResponse {}
export const PutStorageNetappSnapshotPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PutStorageNetappSnapshotPolicyResponse",
}) as any as S.Schema<PutStorageNetappSnapshotPolicyResponse>;

export interface ShareStorageNetappRequest {
  /** Service name */
  serviceName: string;
  /** Share description */
  description?: string | null;
  /** User-defined name used to generate human readable access path for the share */
  mountPointName?: string | null;
  /** Share name */
  name?: string | null;
  /** Share protocol */
  protocol: StorageProtocolEnum | (string & {}) | null;
  /** Share size in Gigabytes */
  size: number | null;
  /** Snapshot ID used to create the share */
  snapshotID?: string | null;
}
export const ShareStorageNetappRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
    description: S.optional(S.NullOr(S.String)),
    mountPointName: S.optional(S.NullOr(S.String)),
    name: S.optional(S.NullOr(S.String)),
    protocol: S.NullOr(StorageProtocolEnum),
    size: S.NullOr(S.Number),
    snapshotID: S.optional(S.NullOr(S.String)),
  }).pipe(T.Http({ method: "POST", uri: "/storage/netapp/{serviceName}/share", code: 200 })),
).annotate({
  identifier: "ShareStorageNetappRequest",
}) as any as S.Schema<ShareStorageNetappRequest>;

export interface TerminateStorageNetappRequest {
  /** Service name */
  serviceName: string;
}
export const TerminateStorageNetappRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    serviceName: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "POST", uri: "/storage/netapp/{serviceName}/terminate", code: 200 })),
).annotate({
  identifier: "TerminateStorageNetappRequest",
}) as any as S.Schema<TerminateStorageNetappRequest>;

export type TerminateStorageNetappResponse = string;
export const TerminateStorageNetappResponse = /*@__PURE__*/ S.suspend(() =>
  S.String.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "TerminateStorageNetappResponse",
}) as any as S.Schema<TerminateStorageNetappResponse>;

export type ConfirmStorageNetappTerminationError = OvhOpError;
/** Confirm service termination */
export const confirmStorageNetappTermination: API.OperationMethod<
  ConfirmStorageNetappTerminationRequest,
  ConfirmStorageNetappTerminationResponse,
  ConfirmStorageNetappTerminationError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ConfirmStorageNetappTerminationRequest,
  output: ConfirmStorageNetappTerminationResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappChangeContactError = OvhOpError;
/** Launch a contact change procedure */
export const createStorageNetappChangeContact: API.OperationMethod<
  CreateStorageNetappChangeContactRequest,
  CreateStorageNetappChangeContactResponse,
  CreateStorageNetappChangeContactError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappChangeContactRequest,
  output: CreateStorageNetappChangeContactResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappShareAclError = OvhOpError;
/** Create an ACL */
export const createStorageNetappShareAcl: API.OperationMethod<
  CreateStorageNetappShareAclRequest,
  StorageNetAppShareACLRule,
  CreateStorageNetappShareAclError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappShareAclRequest,
  output: StorageNetAppShareACLRule,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappShareRevertError = OvhOpError;
/** Revert a share to it's latest snapshot */
export const createStorageNetappShareRevert: API.OperationMethod<
  CreateStorageNetappShareRevertRequest,
  CreateStorageNetappShareRevertResponse,
  CreateStorageNetappShareRevertError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappShareRevertRequest,
  output: CreateStorageNetappShareRevertResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappShareShrinkError = OvhOpError;
/** Shrink share size */
export const createStorageNetappShareShrink: API.OperationMethod<
  CreateStorageNetappShareShrinkRequest,
  CreateStorageNetappShareShrinkResponse,
  CreateStorageNetappShareShrinkError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappShareShrinkRequest,
  output: CreateStorageNetappShareShrinkResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappShareSnapshotError = OvhOpError;
/** Create a snapshot */
export const createStorageNetappShareSnapshot: API.OperationMethod<
  CreateStorageNetappShareSnapshotRequest,
  StorageNetAppShareSnapshot,
  CreateStorageNetappShareSnapshotError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappShareSnapshotRequest,
  output: StorageNetAppShareSnapshot,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappShareSnapshotHoldError = OvhOpError;
/** Hold an automatic share snapshot */
export const createStorageNetappShareSnapshotHold: API.OperationMethod<
  CreateStorageNetappShareSnapshotHoldRequest,
  StorageNetAppShareSnapshot,
  CreateStorageNetappShareSnapshotHoldError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappShareSnapshotHoldRequest,
  output: StorageNetAppShareSnapshot,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type CreateStorageNetappSnapshotPolicyError = OvhOpError;
/** Create a snapshot policy */
export const createStorageNetappSnapshotPolicy: API.OperationMethod<
  CreateStorageNetappSnapshotPolicyRequest,
  StorageNetAppSnapshotPolicy,
  CreateStorageNetappSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStorageNetappSnapshotPolicyRequest,
  output: StorageNetAppSnapshotPolicy,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type DeleteStorageNetappShareError = OvhOpError;
/** Delete a share */
export const deleteStorageNetappShare: API.OperationMethod<
  DeleteStorageNetappShareRequest,
  DeleteStorageNetappShareResponse,
  DeleteStorageNetappShareError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteStorageNetappShareRequest,
  output: DeleteStorageNetappShareResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type DeleteStorageNetappShareAclError = OvhOpError;
/** Delete an ACL */
export const deleteStorageNetappShareAcl: API.OperationMethod<
  DeleteStorageNetappShareAclRequest,
  DeleteStorageNetappShareAclResponse,
  DeleteStorageNetappShareAclError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteStorageNetappShareAclRequest,
  output: DeleteStorageNetappShareAclResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type DeleteStorageNetappShareSnapshotError = OvhOpError;
/** Delete a snapshot */
export const deleteStorageNetappShareSnapshot: API.OperationMethod<
  DeleteStorageNetappShareSnapshotRequest,
  DeleteStorageNetappShareSnapshotResponse,
  DeleteStorageNetappShareSnapshotError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteStorageNetappShareSnapshotRequest,
  output: DeleteStorageNetappShareSnapshotResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type DeleteStorageNetappSnapshotPolicyError = OvhOpError;
/** Delete a snapshot policy */
export const deleteStorageNetappSnapshotPolicy: API.OperationMethod<
  DeleteStorageNetappSnapshotPolicyRequest,
  DeleteStorageNetappSnapshotPolicyResponse,
  DeleteStorageNetappSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteStorageNetappSnapshotPolicyRequest,
  output: DeleteStorageNetappSnapshotPolicyResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ExtendStorageNetappShareError = OvhOpError;
/** Extend share size */
export const extendStorageNetappShare: API.OperationMethod<
  ExtendStorageNetappShareRequest,
  ExtendStorageNetappShareResponse,
  ExtendStorageNetappShareError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ExtendStorageNetappShareRequest,
  output: ExtendStorageNetappShareResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappError = OvhOpError;
/** Get service details */
export const getStorageNetapp: API.OperationMethod<
  GetStorageNetappRequest,
  StorageNetAppServiceWithIAM,
  GetStorageNetappError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappRequest,
  output: StorageNetAppServiceWithIAM,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappMetricsTokenError = OvhOpError;
/** Get metrics token */
export const getStorageNetappMetricsToken: API.OperationMethod<
  GetStorageNetappMetricsTokenRequest,
  StorageMetricsToken,
  GetStorageNetappMetricsTokenError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappMetricsTokenRequest,
  output: StorageMetricsToken,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappNetworkError = OvhOpError;
/** Get network details */
export const getStorageNetappNetwork: API.OperationMethod<
  GetStorageNetappNetworkRequest,
  StorageNetAppNetwork,
  GetStorageNetappNetworkError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappNetworkRequest,
  output: StorageNetAppNetwork,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappServiceInfosError = OvhOpError;
/** Get service information */
export const getStorageNetappServiceInfos: API.OperationMethod<
  GetStorageNetappServiceInfosRequest,
  ServicesService,
  GetStorageNetappServiceInfosError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappServiceInfosRequest,
  output: ServicesService,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappShareError = OvhOpError;
/** Get share details */
export const getStorageNetappShare: API.OperationMethod<
  GetStorageNetappShareRequest,
  StorageNetAppShare,
  GetStorageNetappShareError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappShareRequest,
  output: StorageNetAppShare,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappShareAccessPathError = OvhOpError;
/** Get access path details */
export const getStorageNetappShareAccessPath: API.OperationMethod<
  GetStorageNetappShareAccessPathRequest,
  StorageNetAppShareAccessPath,
  GetStorageNetappShareAccessPathError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappShareAccessPathRequest,
  output: StorageNetAppShareAccessPath,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappShareAclError = OvhOpError;
/** Get ACL details */
export const getStorageNetappShareAcl: API.OperationMethod<
  GetStorageNetappShareAclRequest,
  StorageNetAppShareACLRule,
  GetStorageNetappShareAclError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappShareAclRequest,
  output: StorageNetAppShareACLRule,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappShareSnapshotError = OvhOpError;
/** Get snapshot details */
export const getStorageNetappShareSnapshot: API.OperationMethod<
  GetStorageNetappShareSnapshotRequest,
  StorageNetAppShareSnapshot,
  GetStorageNetappShareSnapshotError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappShareSnapshotRequest,
  output: StorageNetAppShareSnapshot,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappShareSnapshotPolicyError = OvhOpError;
/** Get snapshot policy used by a share */
export const getStorageNetappShareSnapshotPolicy: API.OperationMethod<
  GetStorageNetappShareSnapshotPolicyRequest,
  StorageNetAppShareSnapshotPolicy,
  GetStorageNetappShareSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappShareSnapshotPolicyRequest,
  output: StorageNetAppShareSnapshotPolicy,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappShareSnapshotReserveError = OvhOpError;
/** Get snapshot reserve properties of a share */
export const getStorageNetappShareSnapshotReserve: API.OperationMethod<
  GetStorageNetappShareSnapshotReserveRequest,
  StorageNetAppShareSnapshotReserve,
  GetStorageNetappShareSnapshotReserveError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappShareSnapshotReserveRequest,
  output: StorageNetAppShareSnapshotReserve,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type GetStorageNetappSnapshotPolicyError = OvhOpError;
/** Get snapshot policy details */
export const getStorageNetappSnapshotPolicy: API.OperationMethod<
  GetStorageNetappSnapshotPolicyRequest,
  StorageNetAppSnapshotPolicy,
  GetStorageNetappSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStorageNetappSnapshotPolicyRequest,
  output: StorageNetAppSnapshotPolicy,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappError = OvhOpError;
/** List available services */
export const listStorageNetapp: API.OperationMethod<
  ListStorageNetappRequest,
  ListStorageNetappResponse,
  ListStorageNetappError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappRequest,
  output: ListStorageNetappResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappNetworkError = OvhOpError;
/** List networks */
export const listStorageNetappNetwork: API.OperationMethod<
  ListStorageNetappNetworkRequest,
  ListStorageNetappNetworkResponse,
  ListStorageNetappNetworkError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappNetworkRequest,
  output: ListStorageNetappNetworkResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappShareError = OvhOpError;
/** List available shares */
export const listStorageNetappShare: API.OperationMethod<
  ListStorageNetappShareRequest,
  ListStorageNetappShareResponse,
  ListStorageNetappShareError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappShareRequest,
  output: ListStorageNetappShareResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappShareAccessPathError = OvhOpError;
/** List available access paths */
export const listStorageNetappShareAccessPath: API.OperationMethod<
  ListStorageNetappShareAccessPathRequest,
  ListStorageNetappShareAccessPathResponse,
  ListStorageNetappShareAccessPathError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappShareAccessPathRequest,
  output: ListStorageNetappShareAccessPathResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappShareAclError = OvhOpError;
/** List available ACLs */
export const listStorageNetappShareAcl: API.OperationMethod<
  ListStorageNetappShareAclRequest,
  ListStorageNetappShareAclResponse,
  ListStorageNetappShareAclError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappShareAclRequest,
  output: ListStorageNetappShareAclResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappShareSnapshotError = OvhOpError;
/** List available snapshots */
export const listStorageNetappShareSnapshot: API.OperationMethod<
  ListStorageNetappShareSnapshotRequest,
  ListStorageNetappShareSnapshotResponse,
  ListStorageNetappShareSnapshotError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappShareSnapshotRequest,
  output: ListStorageNetappShareSnapshotResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ListStorageNetappSnapshotPolicyError = OvhOpError;
/** Get a list of snapshot policies */
export const listStorageNetappSnapshotPolicy: API.OperationMethod<
  ListStorageNetappSnapshotPolicyRequest,
  ListStorageNetappSnapshotPolicyResponse,
  ListStorageNetappSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStorageNetappSnapshotPolicyRequest,
  output: ListStorageNetappSnapshotPolicyResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappError = OvhOpError;
/** Update service */
export const putStorageNetapp: API.OperationMethod<
  PutStorageNetappRequest,
  StorageNetAppService,
  PutStorageNetappError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappRequest,
  output: StorageNetAppService,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappServiceInfosError = OvhOpError;
/** Update service information */
export const putStorageNetappServiceInfos: API.OperationMethod<
  PutStorageNetappServiceInfosRequest,
  PutStorageNetappServiceInfosResponse,
  PutStorageNetappServiceInfosError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappServiceInfosRequest,
  output: PutStorageNetappServiceInfosResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappShareError = OvhOpError;
/** Update a share */
export const putStorageNetappShare: API.OperationMethod<
  PutStorageNetappShareRequest,
  StorageNetAppShare,
  PutStorageNetappShareError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappShareRequest,
  output: StorageNetAppShare,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappShareSnapshotError = OvhOpError;
/** Update a snapshot */
export const putStorageNetappShareSnapshot: API.OperationMethod<
  PutStorageNetappShareSnapshotRequest,
  StorageNetAppShareSnapshot,
  PutStorageNetappShareSnapshotError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappShareSnapshotRequest,
  output: StorageNetAppShareSnapshot,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappShareSnapshotPolicyError = OvhOpError;
/** Update snapshot policy used by a share */
export const putStorageNetappShareSnapshotPolicy: API.OperationMethod<
  PutStorageNetappShareSnapshotPolicyRequest,
  PutStorageNetappShareSnapshotPolicyResponse,
  PutStorageNetappShareSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappShareSnapshotPolicyRequest,
  output: PutStorageNetappShareSnapshotPolicyResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappShareSnapshotReserveError = OvhOpError;
/** Update snapshot reserve properties of a share */
export const putStorageNetappShareSnapshotReserve: API.OperationMethod<
  PutStorageNetappShareSnapshotReserveRequest,
  PutStorageNetappShareSnapshotReserveResponse,
  PutStorageNetappShareSnapshotReserveError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappShareSnapshotReserveRequest,
  output: PutStorageNetappShareSnapshotReserveResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type PutStorageNetappSnapshotPolicyError = OvhOpError;
/** Update a snapshot policy */
export const putStorageNetappSnapshotPolicy: API.OperationMethod<
  PutStorageNetappSnapshotPolicyRequest,
  PutStorageNetappSnapshotPolicyResponse,
  PutStorageNetappSnapshotPolicyError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutStorageNetappSnapshotPolicyRequest,
  output: PutStorageNetappSnapshotPolicyResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type ShareStorageNetappError = OvhOpError;
/** Create a share */
export const shareStorageNetapp: API.OperationMethod<
  ShareStorageNetappRequest,
  StorageNetAppShare,
  ShareStorageNetappError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ShareStorageNetappRequest,
  output: StorageNetAppShare,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));

export type TerminateStorageNetappError = OvhOpError;
/** Ask for the termination of your service */
export const terminateStorageNetapp: API.OperationMethod<
  TerminateStorageNetappRequest,
  TerminateStorageNetappResponse,
  TerminateStorageNetappError,
  OvhOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TerminateStorageNetappRequest,
  output: TerminateStorageNetappResponse,
  errors: [UnknownOvhError],
  protocol: OvhProtocol,
  retry: Retry.Retry,
}));
