import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { PosthogProtocol, type PosthogOpError, type PosthogOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { PosthogOpError, PosthogOpContext };

export class Conflict
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Conflict>()("Conflict", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withConflictError),
    [{ status: 409 }],
  ) {}

/** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
export type CreateLlmSkillRequestAllowedToolsList = Array<string>;
export const CreateLlmSkillRequestAllowedToolsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateLlmSkillRequestAllowedToolsList>;

/** Arbitrary key-value metadata. */
export type CreateLlmSkillRequestMetadataMap = { [key: string]: unknown | undefined };
export const CreateLlmSkillRequestMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<CreateLlmSkillRequestMetadataMap>;

/** User UUIDs to set as the skill's owners. Each must be a member of this project. Defaults to the creating user when omitted; pass an empty list to create with no owners. */
export type CreateLlmSkillRequestOwnersList = Array<string>;
export const CreateLlmSkillRequestOwnersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateLlmSkillRequestOwnersList>;

export interface LLMSkillFileInput {
  /** File path relative to skill root, e.g. 'scripts/setup.sh' or 'references/guide.md'. */
  path?: string;
  /** Text content of the file. */
  content?: string;
  /** MIME type of the file content. */
  content_type?: string;
}
export const LLMSkillFileInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String),
    content: S.optional(S.String),
    content_type: S.optional(S.String),
  }),
).annotate({ identifier: "LLMSkillFileInput" }) as any as S.Schema<LLMSkillFileInput>;

/** Bundled files to include with the initial version (scripts, references, assets). */
export type CreateLlmSkillRequestFilesList = Array<LLMSkillFileInput>;
export const CreateLlmSkillRequestFilesList = /*@__PURE__*/ S.Array(
  LLMSkillFileInput,
) as any as S.Schema<CreateLlmSkillRequestFilesList>;

export interface CreateLlmSkillRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Unique skill name. Lowercase letters, numbers, and hyphens only. Max 64 characters. Cannot be the name of a skill PostHog ships. */
  name?: string;
  /** What this skill does and when to use it. Max 1024 characters. */
  description?: string;
  /** The SKILL.md instruction content (markdown). */
  body?: string;
  /** License name or reference to a bundled license file. */
  license?: string;
  /** Environment requirements (intended product, system packages, network access, etc.). */
  compatibility?: string;
  /** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
  allowed_tools?: CreateLlmSkillRequestAllowedToolsList;
  /** Arbitrary key-value metadata. */
  metadata?: CreateLlmSkillRequestMetadataMap;
  /** User UUIDs to set as the skill's owners. Each must be a member of this project. Defaults to the creating user when omitted; pass an empty list to create with no owners. */
  owners?: CreateLlmSkillRequestOwnersList;
  /** Bundled files to include with the initial version (scripts, references, assets). */
  files?: CreateLlmSkillRequestFilesList;
}
export const CreateLlmSkillRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    description: S.optional(S.String),
    body: S.optional(S.String),
    license: S.optional(S.String),
    compatibility: S.optional(S.String),
    allowed_tools: S.optional(CreateLlmSkillRequestAllowedToolsList),
    metadata: S.optional(CreateLlmSkillRequestMetadataMap),
    owners: S.optional(CreateLlmSkillRequestOwnersList),
    files: S.optional(CreateLlmSkillRequestFilesList),
  }).pipe(T.Http({ method: "POST", uri: "/api/projects/{project_id}/llm_skills/", code: 200 })),
).annotate({ identifier: "CreateLlmSkillRequest" }) as any as S.Schema<CreateLlmSkillRequest>;

/** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
export type LLMSkillAllowedToolsList = Array<string>;
export const LLMSkillAllowedToolsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<LLMSkillAllowedToolsList>;

/** Arbitrary key-value metadata. */
export type LLMSkillMetadataMap = { [key: string]: unknown | undefined };
export const LLMSkillMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<LLMSkillMetadataMap>;

export type UserBasicHedgehogConfigMap = { [key: string]: unknown | undefined };
export const UserBasicHedgehogConfigMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<UserBasicHedgehogConfigMap>;

/** * `engineering` - Engineering * `data` - Data * `product` - Product Management * `founder` - Founder * `leadership` - Leadership * `marketing` - Marketing * `sales` - Sales / Success * `student` - Student * `other` - Other */
export type RoleAtOrganizationEnum =
  | "engineering"
  | "data"
  | "product"
  | "founder"
  | "leadership"
  | "marketing"
  | "sales"
  | "student"
  | "other";
export const RoleAtOrganizationEnum = S.String;

export type BlankEnum = "";
export const BlankEnum = S.String;

export type UserBasicRoleAtOrganization = RoleAtOrganizationEnum | BlankEnum;
export const UserBasicRoleAtOrganization =
  S.Unknown as any as S.Schema<UserBasicRoleAtOrganization>;

export interface UserBasic {
  id?: number;
  uuid?: string;
  distinct_id?: string | null;
  first_name?: string;
  last_name?: string;
  email?: string;
  is_email_verified?: boolean | null;
  hedgehog_config?: UserBasicHedgehogConfigMap | null;
  role_at_organization?: UserBasicRoleAtOrganization | null;
}
export const UserBasic = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    uuid: S.optional(S.String),
    distinct_id: S.optional(S.NullOr(S.String)),
    first_name: S.optional(S.String),
    last_name: S.optional(S.String),
    email: S.optional(S.String),
    is_email_verified: S.optional(S.NullOr(S.Boolean)),
    hedgehog_config: S.optional(S.NullOr(UserBasicHedgehogConfigMap)),
    role_at_organization: S.optional(S.NullOr(UserBasicRoleAtOrganization)),
  }),
).annotate({ identifier: "UserBasic" }) as any as S.Schema<UserBasic>;

/** Users who own this skill, seed-creator first. Ownership is keyed on the logical skill (not a version), so it's stable across edits. Prefer this over created_by to learn who to route reviews or questions to. Set via the owners field on create/update (a list of user UUIDs). Empty for scout sandbox fetches of skills that haven't opted into the report channel. */
export type LLMSkillOwnersList = Array<UserBasic>;
export const LLMSkillOwnersList = /*@__PURE__*/ S.Array(
  UserBasic,
) as any as S.Schema<LLMSkillOwnersList>;

export interface LLMSkillFileManifest {
  path?: string;
  content_type?: string;
  /** Number of lines in the file content. */
  line_count?: number;
  /** Number of characters in the file content. */
  char_count?: number;
  /** Size of the file content in bytes. Null on rows written before digests were stamped. */
  size?: number | null;
  /** Hex SHA-256 of the file content. Null on rows written before digests were stamped. */
  sha256?: string | null;
}
export const LLMSkillFileManifest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String),
    content_type: S.optional(S.String),
    line_count: S.optional(S.Number),
    char_count: S.optional(S.Number),
    size: S.optional(S.NullOr(S.Number)),
    sha256: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "LLMSkillFileManifest" }) as any as S.Schema<LLMSkillFileManifest>;

/** Bundled files manifest. Each entry carries path, content_type, and line/char counts — no content; fetch content via /llm_skills/name/{name}/files/{path}/. */
export type LLMSkillFilesList = Array<LLMSkillFileManifest>;
export const LLMSkillFilesList = /*@__PURE__*/ S.Array(
  LLMSkillFileManifest,
) as any as S.Schema<LLMSkillFilesList>;

export interface LLMSkillOutlineEntry {
  /** Markdown heading level (1-6). */
  level?: number;
  /** Heading text. */
  text?: string;
}
export const LLMSkillOutlineEntry = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    level: S.optional(S.Number),
    text: S.optional(S.String),
  }),
).annotate({ identifier: "LLMSkillOutlineEntry" }) as any as S.Schema<LLMSkillOutlineEntry>;

/** Flat list of markdown headings parsed from the skill body. Useful as a lightweight table of contents. */
export type LLMSkillOutlineList = Array<LLMSkillOutlineEntry>;
export const LLMSkillOutlineList = /*@__PURE__*/ S.Array(
  LLMSkillOutlineEntry,
) as any as S.Schema<LLMSkillOutlineList>;

export interface LLMSkillSpecProblem {
  /** Stable machine-readable code for the problem, e.g. description_too_long or file_path_collides. */
  code: string;
  /** What is wrong and what to change, written for the skill's author. */
  message: string;
  /** The bundled file the problem is about. Null when it is about the skill itself. */
  file_path: string | null;
}
export const LLMSkillSpecProblem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    code: S.String,
    message: S.String,
    file_path: S.NullOr(S.String),
  }),
).annotate({ identifier: "LLMSkillSpecProblem" }) as any as S.Schema<LLMSkillSpecProblem>;

/** Why this skill is left out of the skills bundle and the plugin marketplace, as stable codes with author-facing messages. Empty when the skill packages cleanly. */
export type LLMSkillSpecProblemsList = Array<LLMSkillSpecProblem>;
export const LLMSkillSpecProblemsList = /*@__PURE__*/ S.Array(
  LLMSkillSpecProblem,
) as any as S.Schema<LLMSkillSpecProblemsList>;

export interface LLMSkill {
  id?: string;
  /** Unique skill name. Lowercase letters, numbers, and hyphens only. Max 64 characters. */
  name?: string;
  /** What this skill does and when to use it. */
  description?: string;
  /** Total length of the full body in characters, independent of any body_offset/body_length paging. Compare against the length of the returned body to detect a truncated response. */
  body_total_length?: number;
  /** When body_length paging stops before the end of the body, the character offset to request next (pass as body_offset). Null when the returned body reaches the end. */
  body_next_offset?: number | null;
  /** The SKILL.md instruction content (markdown). */
  body?: string;
  /** License name or reference to a bundled license file. */
  license?: string;
  /** Environment requirements (intended product, system packages, network access, etc.). */
  compatibility?: string;
  /** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
  allowed_tools?: LLMSkillAllowedToolsList;
  /** Arbitrary key-value metadata. */
  metadata?: LLMSkillMetadataMap;
  /** Server-owned classification — set by the producing system (the Signals harness stamps "scout"), not writable via the API. Empty for an ordinary skill. Groups skills into their own surface (e.g. the Scouts tab) independently of the skill name. */
  category?: string;
  /** Users who own this skill, seed-creator first. Ownership is keyed on the logical skill (not a version), so it's stable across edits. Prefer this over created_by to learn who to route reviews or questions to. Set via the owners field on create/update (a list of user UUIDs). Empty for scout sandbox fetches of skills that haven't opted into the report channel. */
  owners?: LLMSkillOwnersList;
  /** Bundled files manifest. Each entry carries path, content_type, and line/char counts — no content; fetch content via /llm_skills/name/{name}/files/{path}/. */
  files?: LLMSkillFilesList;
  /** Flat list of markdown headings parsed from the skill body. Useful as a lightweight table of contents. */
  outline?: LLMSkillOutlineList;
  /** Why this skill is left out of the skills bundle and the plugin marketplace, as stable codes with author-facing messages. Empty when the skill packages cleanly. */
  spec_problems?: LLMSkillSpecProblemsList;
  version?: number;
  /** Optional note describing what changed in this version. Set when the version is published. */
  version_description?: string | null;
  created_by?: UserBasic | null;
  created_at?: string;
  updated_at?: string;
  deleted?: boolean;
  is_latest?: boolean;
  latest_version?: number;
  version_count?: number;
  first_version_created_at?: string;
}
export const LLMSkill = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    description: S.optional(S.String),
    body_total_length: S.optional(S.Number),
    body_next_offset: S.optional(S.NullOr(S.Number)),
    body: S.optional(S.String),
    license: S.optional(S.String),
    compatibility: S.optional(S.String),
    allowed_tools: S.optional(LLMSkillAllowedToolsList),
    metadata: S.optional(LLMSkillMetadataMap),
    category: S.optional(S.String),
    owners: S.optional(LLMSkillOwnersList),
    files: S.optional(LLMSkillFilesList),
    outline: S.optional(LLMSkillOutlineList),
    spec_problems: S.optional(LLMSkillSpecProblemsList),
    version: S.optional(S.Number),
    version_description: S.optional(S.NullOr(S.String)),
    created_by: S.optional(S.NullOr(UserBasic)),
    created_at: S.optional(S.String),
    updated_at: S.optional(S.String),
    deleted: S.optional(S.Boolean),
    is_latest: S.optional(S.Boolean),
    latest_version: S.optional(S.Number),
    version_count: S.optional(S.Number),
    first_version_created_at: S.optional(S.String),
  }),
).annotate({ identifier: "LLMSkill" }) as any as S.Schema<LLMSkill>;

export interface CreateLlmSkillsNameFileRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** File path relative to skill root, e.g. 'scripts/setup.sh' or 'references/guide.md'. */
  path?: string;
  /** Text content of the file. */
  content?: string;
  /** MIME type of the file content. */
  content_type?: string;
  /** Latest version you are editing from. If provided, the request fails with 409 when another write has landed in the meantime. */
  base_version?: number;
}
export const CreateLlmSkillsNameFileRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    path: S.optional(S.String),
    content: S.optional(S.String),
    content_type: S.optional(S.String),
    base_version: S.optional(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/files/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateLlmSkillsNameFileRequest",
}) as any as S.Schema<CreateLlmSkillsNameFileRequest>;

export type GetLlmSkillsBundleRequestContent = "stub" | "full";
export const GetLlmSkillsBundleRequestContent = S.String;

export interface GetLlmSkillsBundleRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** What each skill directory in the zip contains. 'stub' (default) writes a SKILL.md with the name, description and instructions to fetch the skill over the PostHog MCP when it is invoked. 'full' writes the rendered SKILL.md, every bundled file and the Codex sidecar. * `stub` - stub * `full` - full */
  content?: GetLlmSkillsBundleRequestContent | (string & {});
  /** Maximum number of skills in the zip, newest first; default 50, at most 100. Every skill in the zip costs the agent prompt context on each turn, so pick what the harness can usefully carry. Skills past the limit are reported in X-Skills-Dropped. */
  limit?: number;
}
export const GetLlmSkillsBundleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    content: S.optional(GetLlmSkillsBundleRequestContent.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/llm_skills/bundle/", code: 200 }),
  ),
).annotate({
  identifier: "GetLlmSkillsBundleRequest",
}) as any as S.Schema<GetLlmSkillsBundleRequest>;

export interface GetLlmSkillsBundleResponse {}
export const GetLlmSkillsBundleResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "GetLlmSkillsBundleResponse",
}) as any as S.Schema<GetLlmSkillsBundleResponse>;

export interface GetLlmSkillsNameRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Maximum number of characters of the body to return starting at body_offset. Omit to return the whole body from the offset onwards. When the slice stops before the end, body_next_offset is the offset to request next. */
  body_length?: number;
  /** Zero-based character offset to start the returned body from. Use with body_length to page through a large body that a client would otherwise truncate. Compare the returned body length against body_total_length to detect truncation, then re-fetch from body_next_offset. Defaults to 0 (start of body). */
  body_offset?: number;
  /** Specific skill version to fetch. If omitted, the latest version is returned. */
  version?: number;
}
export const GetLlmSkillsNameRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    body_length: S.optional(S.Number.pipe(T.Query())),
    body_offset: S.optional(S.Number.pipe(T.Query())),
    version: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/",
      code: 200,
    }),
  ),
).annotate({ identifier: "GetLlmSkillsNameRequest" }) as any as S.Schema<GetLlmSkillsNameRequest>;

export interface GetLlmSkillsNameFileRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  file_path: string;
  /** Specific skill version to fetch. If omitted, the latest version is returned. */
  version?: number;
}
export const GetLlmSkillsNameFileRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    file_path: S.String.pipe(T.Label()),
    version: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/files/{file_path}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetLlmSkillsNameFileRequest",
}) as any as S.Schema<GetLlmSkillsNameFileRequest>;

export interface LLMSkillFile {
  path?: string;
  content?: string;
  content_type?: string;
}
export const LLMSkillFile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String),
    content: S.optional(S.String),
    content_type: S.optional(S.String),
  }),
).annotate({ identifier: "LLMSkillFile" }) as any as S.Schema<LLMSkillFile>;

export interface GetLlmSkillsNameSkillMdRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Specific skill version to fetch. If omitted, the latest version is returned. */
  version?: number;
}
export const GetLlmSkillsNameSkillMdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    version: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/skill-md/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetLlmSkillsNameSkillMdRequest",
}) as any as S.Schema<GetLlmSkillsNameSkillMdRequest>;

export type LLMSkillMarkdownFrontmatterMetadataMap = { [key: string]: string | undefined };
export const LLMSkillMarkdownFrontmatterMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<LLMSkillMarkdownFrontmatterMetadataMap>;

/** The frontmatter block of content as a JSON object. Equal to yaml.safe_load of that block, so a listing can carry the same fields the file carries. */
export interface LLMSkillMarkdownFrontmatter {
  name: string;
  description: string;
  license?: string;
  compatibility?: string;
  metadata: LLMSkillMarkdownFrontmatterMetadataMap;
  allowed_tools?: string;
}
export const LLMSkillMarkdownFrontmatter = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    description: S.String,
    license: S.optional(S.String),
    compatibility: S.optional(S.String),
    metadata: LLMSkillMarkdownFrontmatterMetadataMap,
    allowed_tools: S.optional(S.String.pipe(T.Body("allowed-tools"))),
  }),
).annotate({
  identifier: "LLMSkillMarkdownFrontmatter",
}) as any as S.Schema<LLMSkillMarkdownFrontmatter>;

export interface LLMSkillMarkdown {
  /** Name of the skill, which is also its directory name. */
  name: string;
  /** Version of the skill that this SKILL.md was rendered from. */
  version: number;
  /** The complete SKILL.md file: the YAML frontmatter block, a blank line, then the skill body. Serve these bytes as the file; a digest must be taken over this exact string. */
  content: string;
  /** The frontmatter block of content as a JSON object. Equal to yaml.safe_load of that block, so a listing can carry the same fields the file carries. */
  frontmatter: LLMSkillMarkdownFrontmatter;
}
export const LLMSkillMarkdown = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    version: S.Number,
    content: S.String,
    frontmatter: LLMSkillMarkdownFrontmatter,
  }),
).annotate({ identifier: "LLMSkillMarkdown" }) as any as S.Schema<LLMSkillMarkdown>;

export interface GetLlmSkillsResolveNameRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Return versions older than this version number. Mutually exclusive with offset. */
  before_version?: number;
  /** Maximum number of versions to return per page (1-100). */
  limit?: number;
  /** Zero-based offset into version history for pagination. Mutually exclusive with before_version. */
  offset?: number;
  /** Specific skill version to fetch. If omitted, the latest version is returned. */
  version?: number;
  /** Exact skill version UUID to resolve. */
  version_id?: string;
}
export const GetLlmSkillsResolveNameRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    before_version: S.optional(S.Number.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    version: S.optional(S.Number.pipe(T.Query())),
    version_id: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/llm_skills/resolve/name/{skill_name}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetLlmSkillsResolveNameRequest",
}) as any as S.Schema<GetLlmSkillsResolveNameRequest>;

export interface LLMSkillVersionSummary {
  id?: string;
  version?: number;
  version_description?: string | null;
  created_by?: UserBasic | null;
  created_at?: string;
  is_latest?: boolean;
}
export const LLMSkillVersionSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    version: S.optional(S.Number),
    version_description: S.optional(S.NullOr(S.String)),
    created_by: S.optional(S.NullOr(UserBasic)),
    created_at: S.optional(S.String),
    is_latest: S.optional(S.Boolean),
  }),
).annotate({ identifier: "LLMSkillVersionSummary" }) as any as S.Schema<LLMSkillVersionSummary>;

export type LLMSkillResolveResponseVersionsList = Array<LLMSkillVersionSummary>;
export const LLMSkillResolveResponseVersionsList = /*@__PURE__*/ S.Array(
  LLMSkillVersionSummary,
) as any as S.Schema<LLMSkillResolveResponseVersionsList>;

export interface LLMSkillResolveResponse {
  skill?: LLMSkill;
  versions?: LLMSkillResolveResponseVersionsList;
  has_more?: boolean;
}
export const LLMSkillResolveResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    skill: S.optional(LLMSkill),
    versions: S.optional(LLMSkillResolveResponseVersionsList),
    has_more: S.optional(S.Boolean),
  }),
).annotate({ identifier: "LLMSkillResolveResponse" }) as any as S.Schema<LLMSkillResolveResponse>;

export interface ListLlmSkillsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Filter skills to this exact category. Pass "scout" for Signals scouts, or an empty string to return only uncategorized skills. Omit the parameter entirely to return skills of every category. */
  category?: string;
  /** Filter skills by the ID of the user who created them. */
  created_by_id?: number;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter skills by the ID of a user who owns them. Ownership is keyed on the logical skill, so this is stable across versions — unlike created_by_id, which tracks whoever published the latest version. */
  owner_id?: number;
  /** Optional substring filter applied to skill names and descriptions. */
  search?: string;
}
export const ListLlmSkillsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    category: S.optional(S.String.pipe(T.Query())),
    created_by_id: S.optional(S.Number.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    owner_id: S.optional(S.Number.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/api/projects/{project_id}/llm_skills/", code: 200 })),
).annotate({ identifier: "ListLlmSkillsRequest" }) as any as S.Schema<ListLlmSkillsRequest>;

/** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
export type LLMSkillListAllowedToolsList = Array<string>;
export const LLMSkillListAllowedToolsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<LLMSkillListAllowedToolsList>;

/** Arbitrary key-value metadata. */
export type LLMSkillListMetadataMap = { [key: string]: unknown | undefined };
export const LLMSkillListMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<LLMSkillListMetadataMap>;

/** Users who own this skill, seed-creator first. Ownership is keyed on the logical skill (not a version), so it's stable across edits. Prefer this over created_by to learn who to route reviews or questions to. Set via the owners field on create/update (a list of user UUIDs). Empty for scout sandbox fetches of skills that haven't opted into the report channel. */
export type LLMSkillListOwnersList = Array<UserBasic>;
export const LLMSkillListOwnersList = /*@__PURE__*/ S.Array(
  UserBasic,
) as any as S.Schema<LLMSkillListOwnersList>;

/** Flat list of markdown headings parsed from the skill body. Useful as a lightweight table of contents. */
export type LLMSkillListOutlineList = Array<LLMSkillOutlineEntry>;
export const LLMSkillListOutlineList = /*@__PURE__*/ S.Array(
  LLMSkillOutlineEntry,
) as any as S.Schema<LLMSkillListOutlineList>;

/** Why this skill is left out of the skills bundle and the plugin marketplace, as stable codes with author-facing messages. Empty when the skill packages cleanly. */
export type LLMSkillListSpecProblemsList = Array<LLMSkillSpecProblem>;
export const LLMSkillListSpecProblemsList = /*@__PURE__*/ S.Array(
  LLMSkillSpecProblem,
) as any as S.Schema<LLMSkillListSpecProblemsList>;

/** List serializer that omits body and file manifest — progressive disclosure (Level 1). */
export interface LLMSkillList {
  id?: string;
  /** Unique skill name. Lowercase letters, numbers, and hyphens only. Max 64 characters. */
  name?: string;
  /** What this skill does and when to use it. */
  description?: string;
  /** License name or reference to a bundled license file. */
  license?: string;
  /** Environment requirements (intended product, system packages, network access, etc.). */
  compatibility?: string;
  /** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
  allowed_tools?: LLMSkillListAllowedToolsList;
  /** Arbitrary key-value metadata. */
  metadata?: LLMSkillListMetadataMap;
  /** Server-owned classification — set by the producing system (the Signals harness stamps "scout"), not writable via the API. Empty for an ordinary skill. Groups skills into their own surface (e.g. the Scouts tab) independently of the skill name. */
  category?: string;
  /** Users who own this skill, seed-creator first. Ownership is keyed on the logical skill (not a version), so it's stable across edits. Prefer this over created_by to learn who to route reviews or questions to. Set via the owners field on create/update (a list of user UUIDs). Empty for scout sandbox fetches of skills that haven't opted into the report channel. */
  owners?: LLMSkillListOwnersList;
  /** Flat list of markdown headings parsed from the skill body. Useful as a lightweight table of contents. */
  outline?: LLMSkillListOutlineList;
  /** Why this skill is left out of the skills bundle and the plugin marketplace, as stable codes with author-facing messages. Empty when the skill packages cleanly. */
  spec_problems?: LLMSkillListSpecProblemsList;
  version?: number;
  /** Optional note describing what changed in this version. Set when the version is published. */
  version_description?: string | null;
  created_by?: UserBasic | null;
  created_at?: string;
  updated_at?: string;
  deleted?: boolean;
  is_latest?: boolean;
  latest_version?: number;
  version_count?: number;
  first_version_created_at?: string;
}
export const LLMSkillList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    description: S.optional(S.String),
    license: S.optional(S.String),
    compatibility: S.optional(S.String),
    allowed_tools: S.optional(LLMSkillListAllowedToolsList),
    metadata: S.optional(LLMSkillListMetadataMap),
    category: S.optional(S.String),
    owners: S.optional(LLMSkillListOwnersList),
    outline: S.optional(LLMSkillListOutlineList),
    spec_problems: S.optional(LLMSkillListSpecProblemsList),
    version: S.optional(S.Number),
    version_description: S.optional(S.NullOr(S.String)),
    created_by: S.optional(S.NullOr(UserBasic)),
    created_at: S.optional(S.String),
    updated_at: S.optional(S.String),
    deleted: S.optional(S.Boolean),
    is_latest: S.optional(S.Boolean),
    latest_version: S.optional(S.Number),
    version_count: S.optional(S.Number),
    first_version_created_at: S.optional(S.String),
  }),
).annotate({ identifier: "LLMSkillList" }) as any as S.Schema<LLMSkillList>;

export type PaginatedLLMSkillListListResultsList = Array<LLMSkillList>;
export const PaginatedLLMSkillListListResultsList = /*@__PURE__*/ S.Array(
  LLMSkillList,
) as any as S.Schema<PaginatedLLMSkillListListResultsList>;

export interface PaginatedLLMSkillListList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedLLMSkillListListResultsList;
}
export const PaginatedLLMSkillListList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedLLMSkillListListResultsList),
  }),
).annotate({
  identifier: "PaginatedLLMSkillListList",
}) as any as S.Schema<PaginatedLLMSkillListList>;

export interface LlmSkillsImportCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A spec-compliant skill .zip (a SKILL.md plus optional bundled files under scripts/, references/, assets/). */
  file: string;
}
export const LlmSkillsImportCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    file: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/import/",
      code: 200,
      contentType: "form-urlencoded",
    }),
  ),
).annotate({
  identifier: "LlmSkillsImportCreateRequest",
}) as any as S.Schema<LlmSkillsImportCreateRequest>;

export interface LlmSkillsMarketplaceInstallCommandCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Roll the existing marketplace credential to issue a fresh token, replacing the old one (this invalidates any setup using the previous token). Ignored when no credential exists yet — the first call always mints one. Only affects this user's own credential. */
  rotate?: boolean;
}
export const LlmSkillsMarketplaceInstallCommandCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    rotate: S.optional(S.Boolean),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/marketplace/install-command/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsMarketplaceInstallCommandCreateRequest",
}) as any as S.Schema<LlmSkillsMarketplaceInstallCommandCreateRequest>;

/** * `absent` - absent * `exists` - exists * `created` - created * `rotated` - rotated */
export type LLMSkillMarketplaceCommandStatusEnum = "absent" | "exists" | "created" | "rotated";
export const LLMSkillMarketplaceCommandStatusEnum = S.String;

export interface LLMSkillMarketplaceCommand {
  /** absent: no credential yet. exists: one already exists (no token returned). created: a new credential was just minted. rotated: the existing credential was rolled. * `absent` - absent * `exists` - exists * `created` - created * `rotated` - rotated */
  status: LLMSkillMarketplaceCommandStatusEnum;
  /** Whether this user already has a marketplace credential for the team's skill store. */
  connected: boolean;
  /** The plugin name the command installs (Claude Code and Codex). */
  plugin_name: string;
  /** The marketplace name, used by the Codex install command. */
  marketplace_name: string;
  /** Label of this user's marketplace credential (a scoped Personal API Key). */
  label: string;
  /** The marketplace git repository URL, with no credential embedded. */
  repo_url: string;
  /** Claude Code: ready-to-paste `/plugin marketplace add` command with the live token embedded. Returned only when a token was just issued (status created/rotated); null otherwise. */
  command: string | null;
  /** Claude Code install command with a YOUR_PHS_TOKEN placeholder instead of a live token; always present. */
  command_template: string;
  /** OpenAI Codex: two-line `codex plugin marketplace add` + `codex plugin add` command with the live token embedded. Returned only when a token was just issued (status created/rotated); null otherwise. */
  codex_command: string | null;
  /** Codex install command with a YOUR_PHS_TOKEN placeholder instead of a live token; always present. */
  codex_command_template: string;
  /** The raw read-only `phx_` credential. Returned once, only when minted or rotated; it cannot be retrieved again afterwards. */
  token: string | null;
  /** Masked preview of the existing credential (e.g. phx_...abcd). */
  mask_value: string | null;
  /** When the credential was created. */
  created_at: string | null;
  /** When the credential was last rotated. */
  last_rolled_at: string | null;
}
export const LLMSkillMarketplaceCommand = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: LLMSkillMarketplaceCommandStatusEnum,
    connected: S.Boolean,
    plugin_name: S.String,
    marketplace_name: S.String,
    label: S.String,
    repo_url: S.String,
    command: S.NullOr(S.String),
    command_template: S.String,
    codex_command: S.NullOr(S.String),
    codex_command_template: S.String,
    token: S.NullOr(S.String),
    mask_value: S.NullOr(S.String),
    created_at: S.NullOr(S.String),
    last_rolled_at: S.NullOr(S.String),
  }),
).annotate({
  identifier: "LLMSkillMarketplaceCommand",
}) as any as S.Schema<LLMSkillMarketplaceCommand>;

export interface LlmSkillsMarketplaceInstallCommandRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
}
export const LlmSkillsMarketplaceInstallCommandRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/llm_skills/marketplace/install-command/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsMarketplaceInstallCommandRetrieveRequest",
}) as any as S.Schema<LlmSkillsMarketplaceInstallCommandRetrieveRequest>;

export interface LlmSkillsNameArchiveCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
}
export const LlmSkillsNameArchiveCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/archive/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNameArchiveCreateRequest",
}) as any as S.Schema<LlmSkillsNameArchiveCreateRequest>;

export interface LlmSkillsNameArchiveCreateResponse {}
export const LlmSkillsNameArchiveCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "LlmSkillsNameArchiveCreateResponse",
}) as any as S.Schema<LlmSkillsNameArchiveCreateResponse>;

export interface LlmSkillsNameDuplicateCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Name for the duplicated skill. Must be unique, and cannot be the name of a skill PostHog ships. */
  new_name?: string;
}
export const LlmSkillsNameDuplicateCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    new_name: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/duplicate/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNameDuplicateCreateRequest",
}) as any as S.Schema<LlmSkillsNameDuplicateCreateRequest>;

export interface LlmSkillsNameExportRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Specific skill version to fetch. If omitted, the latest version is returned. */
  version?: number;
}
export const LlmSkillsNameExportRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    version: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/export/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNameExportRetrieveRequest",
}) as any as S.Schema<LlmSkillsNameExportRetrieveRequest>;

export interface LlmSkillsNameExportRetrieveResponse {}
export const LlmSkillsNameExportRetrieveResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "LlmSkillsNameExportRetrieveResponse",
}) as any as S.Schema<LlmSkillsNameExportRetrieveResponse>;

export interface LlmSkillsNameFilesDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  file_path: string;
  /** Latest version you are editing from. If provided, the request fails with 409 when another write has landed in the meantime. */
  base_version?: number;
}
export const LlmSkillsNameFilesDestroyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    file_path: S.String.pipe(T.Label()),
    base_version: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/files/{file_path}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNameFilesDestroyRequest",
}) as any as S.Schema<LlmSkillsNameFilesDestroyRequest>;

export interface LlmSkillsNameFilesRenameCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Current file path to rename. */
  old_path?: string;
  /** New file path. Must not already exist in the skill. */
  new_path?: string;
  /** Latest version you are editing from. If provided, the request fails with 409 when another write has landed in the meantime. */
  base_version?: number;
}
export const LlmSkillsNameFilesRenameCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    old_path: S.optional(S.String),
    new_path: S.optional(S.String),
    base_version: S.optional(S.Number),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/files-rename/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNameFilesRenameCreateRequest",
}) as any as S.Schema<LlmSkillsNameFilesRenameCreateRequest>;

/** Tags used to group the scout in the fleet. */
export type CommunitySkillScoutConfigTagsList = Array<string>;
export const CommunitySkillScoutConfigTagsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CommunitySkillScoutConfigTagsList>;

/** The scout settings a published scout travels with. Every field is optional. An omitted field means the scout-create form's own default applies. */
export interface CommunitySkillScoutConfig {
  /** How often the scout runs, in minutes. Ignored when run_cron_schedule is set. */
  run_interval_minutes?: number;
  /** Five-field cron expression for the scout's schedule, which takes precedence over the interval. */
  run_cron_schedule?: string;
  /** Whether the scout writes its reports to the inbox. False means it runs as a dry run. */
  emit?: boolean;
  /** Tags used to group the scout in the fleet. */
  tags?: CommunitySkillScoutConfigTagsList;
}
export const CommunitySkillScoutConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run_interval_minutes: S.optional(S.Number),
    run_cron_schedule: S.optional(S.String),
    emit: S.optional(S.Boolean),
    tags: S.optional(CommunitySkillScoutConfigTagsList),
  }),
).annotate({
  identifier: "CommunitySkillScoutConfig",
}) as any as S.Schema<CommunitySkillScoutConfig>;

/** Tags used for filtering and discovery in the marketplace, e.g. ['web-analytics', 'triage']. */
export type LlmSkillsNamePublishCommunityCreateRequestTagsList = Array<string>;
export const LlmSkillsNamePublishCommunityCreateRequestTagsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<LlmSkillsNamePublishCommunityCreateRequestTagsList>;

export interface LlmSkillsNamePublishCommunityCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Immutable ID of the skill version that the publisher reviewed. */
  expected_skill_id: string;
  /** Skill version that the publisher reviewed. The request returns 409 if the latest version changed. */
  expected_version: number;
  /** Category of the skill the publisher reviewed. Registering a skill as a scout changes its category without raising its version, so the version alone would let a skill reviewed as an ordinary one publish as a scout. The request returns 409 if the category changed. Omit it to skip that check. */
  expected_category?: string;
  /** Schedule, emit posture and tags to publish alongside a scout, so it arrives in another project with its cadence intact. Rejected for a skill that is not a scout. */
  scout_config?: CommunitySkillScoutConfig;
  /** Human-friendly display name for the community listing. Defaults to a title-cased skill slug. Must be a single line: it is used as the pull request title and commit message. */
  display_name?: string;
  /** Tags used for filtering and discovery in the marketplace, e.g. ['web-analytics', 'triage']. */
  tags?: LlmSkillsNamePublishCommunityCreateRequestTagsList;
  /** The publisher's GitHub username, used for public attribution on the listing and PR. Optional, and self-reported: it is not verified against the publisher's PostHog account. */
  author_handle?: string;
}
export const LlmSkillsNamePublishCommunityCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    expected_skill_id: S.String,
    expected_version: S.Number,
    expected_category: S.optional(S.String),
    scout_config: S.optional(CommunitySkillScoutConfig),
    display_name: S.optional(S.String),
    tags: S.optional(LlmSkillsNamePublishCommunityCreateRequestTagsList),
    author_handle: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/publish-community/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNamePublishCommunityCreateRequest",
}) as any as S.Schema<LlmSkillsNamePublishCommunityCreateRequest>;

export interface CommunitySkillPublishResult {
  /** URL of the pull request opened in the community-skills repo for maintainer review. */
  pr_url: string;
  /** Number of the opened pull request. */
  pr_number: number;
  /** Name of the branch created in the community-skills repo. */
  branch: string;
}
export const CommunitySkillPublishResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    pr_url: S.String,
    pr_number: S.Number,
    branch: S.String,
  }),
).annotate({
  identifier: "CommunitySkillPublishResult",
}) as any as S.Schema<CommunitySkillPublishResult>;

export interface LlmSkillsNameRenameCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** New name for the skill. Must be unique in the project, cannot be the name of a skill PostHog ships, and must not start with 'signals-scout-' or 'review-hog-'. */
  new_name: string;
}
export const LlmSkillsNameRenameCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    new_name: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/rename/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LlmSkillsNameRenameCreateRequest",
}) as any as S.Schema<LlmSkillsNameRenameCreateRequest>;

export interface LlmSkillsSearchRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Case-insensitive substring to search across ordinary skill names, descriptions, bodies, file paths, and Markdown file contents. */
  query: string;
}
export const LlmSkillsSearchRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    query: S.String.pipe(T.Query()),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/llm_skills/search/", code: 200 }),
  ),
).annotate({
  identifier: "LlmSkillsSearchRetrieveRequest",
}) as any as S.Schema<LlmSkillsSearchRetrieveRequest>;

/** * `name` - name * `description` - description * `body` - body * `file_path` - file_path * `file_content` - file_content */
export type MatchedFieldEnum = "name" | "description" | "body" | "file_path" | "file_content";
export const MatchedFieldEnum = S.String;

export interface LLMSkillSearchMatch {
  /** Skill field that matched the search query. * `name` - name * `description` - description * `body` - body * `file_path` - file_path * `file_content` - file_content */
  matched_field: MatchedFieldEnum;
  /** Skill-relative file path for body or bundled-file matches. Omitted for name and description matches. */
  path?: string;
  /** One-based line containing the match when the result came from a body or bundled file. */
  line?: number;
  /** Short excerpt showing why this skill matched. */
  excerpt: string;
}
export const LLMSkillSearchMatch = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    matched_field: MatchedFieldEnum,
    path: S.optional(S.String),
    line: S.optional(S.Number),
    excerpt: S.String,
  }),
).annotate({ identifier: "LLMSkillSearchMatch" }) as any as S.Schema<LLMSkillSearchMatch>;

/** Up to two locations that matched the search query, ordered by field relevance. */
export type LLMSkillSearchResultMatchesList = Array<LLMSkillSearchMatch>;
export const LLMSkillSearchResultMatchesList = /*@__PURE__*/ S.Array(
  LLMSkillSearchMatch,
) as any as S.Schema<LLMSkillSearchResultMatchesList>;

export interface LLMSkillSearchResult {
  /** Unique skill name. */
  name: string;
  /** What this skill does and when to use it. */
  description: string;
  /** Relevance score used to rank this result. Higher scores are more relevant. */
  score: number;
  /** Up to two locations that matched the search query, ordered by field relevance. */
  matches: LLMSkillSearchResultMatchesList;
}
export const LLMSkillSearchResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    description: S.String,
    score: S.Number,
    matches: LLMSkillSearchResultMatchesList,
  }),
).annotate({ identifier: "LLMSkillSearchResult" }) as any as S.Schema<LLMSkillSearchResult>;

/** Matching ordinary skills in relevance order. */
export type LLMSkillSearchResponseResultsList = Array<LLMSkillSearchResult>;
export const LLMSkillSearchResponseResultsList = /*@__PURE__*/ S.Array(
  LLMSkillSearchResult,
) as any as S.Schema<LLMSkillSearchResponseResultsList>;

export interface LLMSkillSearchResponse {
  /** Number of matching skills returned, capped at 10. */
  count: number;
  /** Matching ordinary skills in relevance order. */
  results: LLMSkillSearchResponseResultsList;
}
export const LLMSkillSearchResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    results: LLMSkillSearchResponseResultsList,
  }),
).annotate({ identifier: "LLMSkillSearchResponse" }) as any as S.Schema<LLMSkillSearchResponse>;

export interface LLMSkillEditOperation {
  /** Text to find in the target content. Must match exactly once. */
  old?: string;
  /** Replacement text. */
  new?: string;
}
export const LLMSkillEditOperation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    old: S.optional(S.String),
    new: S.optional(S.String),
  }),
).annotate({ identifier: "LLMSkillEditOperation" }) as any as S.Schema<LLMSkillEditOperation>;

/** List of find/replace operations to apply to the current skill body. Each edit's 'old' text must match exactly once. Edits are applied sequentially. Mutually exclusive with body. */
export type UpdateLlmSkillsNamePartialRequestEditsList = Array<LLMSkillEditOperation>;
export const UpdateLlmSkillsNamePartialRequestEditsList = /*@__PURE__*/ S.Array(
  LLMSkillEditOperation,
) as any as S.Schema<UpdateLlmSkillsNamePartialRequestEditsList>;

/** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
export type UpdateLlmSkillsNamePartialRequestAllowedToolsList = Array<string>;
export const UpdateLlmSkillsNamePartialRequestAllowedToolsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateLlmSkillsNamePartialRequestAllowedToolsList>;

/** Arbitrary key-value metadata. */
export type UpdateLlmSkillsNamePartialRequestMetadataMap = { [key: string]: unknown | undefined };
export const UpdateLlmSkillsNamePartialRequestMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<UpdateLlmSkillsNamePartialRequestMetadataMap>;

/** Bundled files to include with this version. Replaces all files from the previous version. Mutually exclusive with file_edits. */
export type UpdateLlmSkillsNamePartialRequestFilesList = Array<LLMSkillFileInput>;
export const UpdateLlmSkillsNamePartialRequestFilesList = /*@__PURE__*/ S.Array(
  LLMSkillFileInput,
) as any as S.Schema<UpdateLlmSkillsNamePartialRequestFilesList>;

/** Sequential find/replace operations to apply to this file's content. */
export type LLMSkillFileEditEditsList = Array<LLMSkillEditOperation>;
export const LLMSkillFileEditEditsList = /*@__PURE__*/ S.Array(
  LLMSkillEditOperation,
) as any as S.Schema<LLMSkillFileEditEditsList>;

export interface LLMSkillFileEdit {
  /** Path of the bundled file to edit. Must match an existing file on the current skill version. */
  path?: string;
  /** Sequential find/replace operations to apply to this file's content. */
  edits?: LLMSkillFileEditEditsList;
}
export const LLMSkillFileEdit = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String),
    edits: S.optional(LLMSkillFileEditEditsList),
  }),
).annotate({ identifier: "LLMSkillFileEdit" }) as any as S.Schema<LLMSkillFileEdit>;

/** Per-file find/replace updates. Each entry targets one existing file by path and applies sequential edits to its content. Non-targeted files carry forward unchanged. Cannot add, remove, or rename files — use 'files' for that. Mutually exclusive with files. */
export type UpdateLlmSkillsNamePartialRequestFileEditsList = Array<LLMSkillFileEdit>;
export const UpdateLlmSkillsNamePartialRequestFileEditsList = /*@__PURE__*/ S.Array(
  LLMSkillFileEdit,
) as any as S.Schema<UpdateLlmSkillsNamePartialRequestFileEditsList>;

/** Replace the skill's owners with these user UUIDs (each a member of this project). Omit to leave owners unchanged; pass an empty list to clear them. Owners are keyed on the logical skill, so setting them is independent of the version being published — a body edit alone never changes ownership. */
export type UpdateLlmSkillsNamePartialRequestOwnersList = Array<string>;
export const UpdateLlmSkillsNamePartialRequestOwnersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateLlmSkillsNamePartialRequestOwnersList>;

export interface UpdateLlmSkillsNamePartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  skill_name: string;
  /** Full skill body (SKILL.md instruction content) to publish as a new version. Mutually exclusive with edits. */
  body?: string;
  /** List of find/replace operations to apply to the current skill body. Each edit's 'old' text must match exactly once. Edits are applied sequentially. Mutually exclusive with body. */
  edits?: UpdateLlmSkillsNamePartialRequestEditsList;
  /** Updated description for the new version. */
  description?: string;
  /** License name or reference. */
  license?: string;
  /** Environment requirements. */
  compatibility?: string;
  /** Tools the skill asks to use. Tool names cannot contain whitespace. A harness that reads the skill from a file (zip export, git marketplace, a content=full bundle) treats the list as pre-approved. A harness that loads the skill over MCP, including the default content=stub bundle, ignores the list until the user approves that grant. */
  allowed_tools?: UpdateLlmSkillsNamePartialRequestAllowedToolsList;
  /** Arbitrary key-value metadata. */
  metadata?: UpdateLlmSkillsNamePartialRequestMetadataMap;
  /** Bundled files to include with this version. Replaces all files from the previous version. Mutually exclusive with file_edits. */
  files?: UpdateLlmSkillsNamePartialRequestFilesList;
  /** Per-file find/replace updates. Each entry targets one existing file by path and applies sequential edits to its content. Non-targeted files carry forward unchanged. Cannot add, remove, or rename files — use 'files' for that. Mutually exclusive with files. */
  file_edits?: UpdateLlmSkillsNamePartialRequestFileEditsList;
  /** Replace the skill's owners with these user UUIDs (each a member of this project). Omit to leave owners unchanged; pass an empty list to clear them. Owners are keyed on the logical skill, so setting them is independent of the version being published — a body edit alone never changes ownership. */
  owners?: UpdateLlmSkillsNamePartialRequestOwnersList;
  /** Latest version you are editing from. Used for optimistic concurrency checks. Required when publishing content changes; optional for an owner-only update (when omitted, owners are replaced without a concurrency check). */
  base_version?: number;
  /** Optional note describing what changed in this version. Shown in the version history. */
  version_description?: string;
}
export const UpdateLlmSkillsNamePartialRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    skill_name: S.String.pipe(T.Label()),
    body: S.optional(S.String),
    edits: S.optional(UpdateLlmSkillsNamePartialRequestEditsList),
    description: S.optional(S.String),
    license: S.optional(S.String),
    compatibility: S.optional(S.String),
    allowed_tools: S.optional(UpdateLlmSkillsNamePartialRequestAllowedToolsList),
    metadata: S.optional(UpdateLlmSkillsNamePartialRequestMetadataMap),
    files: S.optional(UpdateLlmSkillsNamePartialRequestFilesList),
    file_edits: S.optional(UpdateLlmSkillsNamePartialRequestFileEditsList),
    owners: S.optional(UpdateLlmSkillsNamePartialRequestOwnersList),
    base_version: S.optional(S.Number),
    version_description: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/api/projects/{project_id}/llm_skills/name/{skill_name}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateLlmSkillsNamePartialRequest",
}) as any as S.Schema<UpdateLlmSkillsNamePartialRequest>;

export type CreateLlmSkillError = PosthogOpError;
export const createLlmSkill: API.OperationMethod<
  CreateLlmSkillRequest,
  LLMSkill,
  CreateLlmSkillError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateLlmSkillRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateLlmSkillsNameFileError = PosthogOpError;
export const createLlmSkillsNameFile: API.OperationMethod<
  CreateLlmSkillsNameFileRequest,
  LLMSkill,
  CreateLlmSkillsNameFileError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateLlmSkillsNameFileRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetLlmSkillsBundleError = PosthogOpError;
/** One zip of the requesting user's store skills, for unpacking into a skills directory. */
export const getLlmSkillsBundle: API.OperationMethod<
  GetLlmSkillsBundleRequest,
  GetLlmSkillsBundleResponse,
  GetLlmSkillsBundleError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetLlmSkillsBundleRequest,
  output: GetLlmSkillsBundleResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetLlmSkillsNameError = PosthogOpError;
export const getLlmSkillsName: API.OperationMethod<
  GetLlmSkillsNameRequest,
  LLMSkill,
  GetLlmSkillsNameError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetLlmSkillsNameRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetLlmSkillsNameFileError = PosthogOpError;
export const getLlmSkillsNameFile: API.OperationMethod<
  GetLlmSkillsNameFileRequest,
  LLMSkillFile,
  GetLlmSkillsNameFileError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetLlmSkillsNameFileRequest,
  output: LLMSkillFile,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetLlmSkillsNameSkillMdError = PosthogOpError;
/** The rendered SKILL.md plus its frontmatter as JSON, for a host that serves the file. Both halves come from one renderer, so a digest a client takes over ``content`` still describes the fields it reads from ``frontmatter``. */
export const getLlmSkillsNameSkillMd: API.OperationMethod<
  GetLlmSkillsNameSkillMdRequest,
  LLMSkillMarkdown,
  GetLlmSkillsNameSkillMdError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetLlmSkillsNameSkillMdRequest,
  output: LLMSkillMarkdown,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetLlmSkillsResolveNameError = PosthogOpError;
export const getLlmSkillsResolveName: API.OperationMethod<
  GetLlmSkillsResolveNameRequest,
  LLMSkillResolveResponse,
  GetLlmSkillsResolveNameError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetLlmSkillsResolveNameRequest,
  output: LLMSkillResolveResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListLlmSkillsError = PosthogOpError;
export const listLlmSkills: API.OperationMethod<
  ListLlmSkillsRequest,
  PaginatedLLMSkillListList,
  ListLlmSkillsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListLlmSkillsRequest,
  output: PaginatedLLMSkillListList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsImportCreateError = PosthogOpError;
export const llmSkillsImportCreate: API.OperationMethod<
  LlmSkillsImportCreateRequest,
  LLMSkill,
  LlmSkillsImportCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsImportCreateRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsMarketplaceInstallCommandCreateError = PosthogOpError;
/** Mint the user's read-only marketplace credential (or rotate it) and return the install command. Per-user: rotating only ever invalidates this user's own credential, never a teammate's. */
export const llmSkillsMarketplaceInstallCommandCreate: API.OperationMethod<
  LlmSkillsMarketplaceInstallCommandCreateRequest,
  LLMSkillMarketplaceCommand,
  LlmSkillsMarketplaceInstallCommandCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsMarketplaceInstallCommandCreateRequest,
  output: LLMSkillMarketplaceCommand,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsMarketplaceInstallCommandRetrieveError = PosthogOpError;
/** Report whether the user already has a marketplace credential, without minting one. The token is unrecoverable, so an existing credential returns its mask only — the UI shows "already connected, existing setups keep working" and offers an explicit rotate. */
export const llmSkillsMarketplaceInstallCommandRetrieve: API.OperationMethod<
  LlmSkillsMarketplaceInstallCommandRetrieveRequest,
  LLMSkillMarketplaceCommand,
  LlmSkillsMarketplaceInstallCommandRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsMarketplaceInstallCommandRetrieveRequest,
  output: LLMSkillMarketplaceCommand,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNameArchiveCreateError = PosthogOpError;
export const llmSkillsNameArchiveCreate: API.OperationMethod<
  LlmSkillsNameArchiveCreateRequest,
  LlmSkillsNameArchiveCreateResponse,
  LlmSkillsNameArchiveCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNameArchiveCreateRequest,
  output: LlmSkillsNameArchiveCreateResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNameDuplicateCreateError = PosthogOpError;
export const llmSkillsNameDuplicateCreate: API.OperationMethod<
  LlmSkillsNameDuplicateCreateRequest,
  LLMSkill,
  LlmSkillsNameDuplicateCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNameDuplicateCreateRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNameExportRetrieveError = PosthogOpError;
export const llmSkillsNameExportRetrieve: API.OperationMethod<
  LlmSkillsNameExportRetrieveRequest,
  LlmSkillsNameExportRetrieveResponse,
  LlmSkillsNameExportRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNameExportRetrieveRequest,
  output: LlmSkillsNameExportRetrieveResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNameFilesDestroyError = PosthogOpError;
export const llmSkillsNameFilesDestroy: API.OperationMethod<
  LlmSkillsNameFilesDestroyRequest,
  LLMSkill,
  LlmSkillsNameFilesDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNameFilesDestroyRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNameFilesRenameCreateError = PosthogOpError;
export const llmSkillsNameFilesRenameCreate: API.OperationMethod<
  LlmSkillsNameFilesRenameCreateRequest,
  LLMSkill,
  LlmSkillsNameFilesRenameCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNameFilesRenameCreateRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNamePublishCommunityCreateError = Conflict | PosthogOpError;
export const llmSkillsNamePublishCommunityCreate: API.OperationMethod<
  LlmSkillsNamePublishCommunityCreateRequest,
  CommunitySkillPublishResult,
  LlmSkillsNamePublishCommunityCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNamePublishCommunityCreateRequest,
  output: CommunitySkillPublishResult,
  errors: [Conflict],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsNameRenameCreateError = PosthogOpError;
export const llmSkillsNameRenameCreate: API.OperationMethod<
  LlmSkillsNameRenameCreateRequest,
  LLMSkill,
  LlmSkillsNameRenameCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsNameRenameCreateRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type LlmSkillsSearchRetrieveError = PosthogOpError;
export const llmSkillsSearchRetrieve: API.OperationMethod<
  LlmSkillsSearchRetrieveRequest,
  LLMSkillSearchResponse,
  LlmSkillsSearchRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LlmSkillsSearchRetrieveRequest,
  output: LLMSkillSearchResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateLlmSkillsNamePartialError = PosthogOpError;
export const updateLlmSkillsNamePartial: API.OperationMethod<
  UpdateLlmSkillsNamePartialRequest,
  LLMSkill,
  UpdateLlmSkillsNamePartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateLlmSkillsNamePartialRequest,
  output: LLMSkill,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
