import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { PosthogProtocol, type PosthogOpError, type PosthogOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

export type CreatePersonsBatchByDistinctIdsRequestFormat = "csv" | "json";
export const CreatePersonsBatchByDistinctIdsRequestFormat = S.String;

export interface CreatePersonsBatchByDistinctIdsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: CreatePersonsBatchByDistinctIdsRequestFormat | (string & {});
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
}
export const CreatePersonsBatchByDistinctIdsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(CreatePersonsBatchByDistinctIdsRequestFormat.pipe(T.Query())),
    properties: S.optional(S.Unknown),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/persons/batch_by_distinct_ids/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreatePersonsBatchByDistinctIdsRequest",
}) as any as S.Schema<CreatePersonsBatchByDistinctIdsRequest>;

export interface CreatePersonsBatchByDistinctIdsResponse {}
export const CreatePersonsBatchByDistinctIdsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "CreatePersonsBatchByDistinctIdsResponse",
}) as any as S.Schema<CreatePersonsBatchByDistinctIdsResponse>;

export type CreatePersonsBatchByUuidRequestFormat = "csv" | "json";
export const CreatePersonsBatchByUuidRequestFormat = S.String;

export interface CreatePersonsBatchByUuidRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: CreatePersonsBatchByUuidRequestFormat | (string & {});
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
}
export const CreatePersonsBatchByUuidRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(CreatePersonsBatchByUuidRequestFormat.pipe(T.Query())),
    properties: S.optional(S.Unknown),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/persons/batch_by_uuids/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreatePersonsBatchByUuidRequest",
}) as any as S.Schema<CreatePersonsBatchByUuidRequest>;

export interface CreatePersonsBatchByUuidResponse {}
export const CreatePersonsBatchByUuidResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "CreatePersonsBatchByUuidResponse",
}) as any as S.Schema<CreatePersonsBatchByUuidResponse>;

export type CreatePersonsSplitRequestFormat = "csv" | "json";
export const CreatePersonsSplitRequestFormat = S.String;

/** List of distinct_ids to **move off** this person onto new single-id persons. The original person keeps every other distinct_id and its properties. New persons are created with deterministic UUIDs derived from `(team_id, distinct_id)`. Cannot be combined with `main_distinct_id`. */
export type CreatePersonsSplitRequestDistinctIdsToSplitList = Array<string>;
export const CreatePersonsSplitRequestDistinctIdsToSplitList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreatePersonsSplitRequestDistinctIdsToSplitList>;

export interface CreatePersonsSplitRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique value identifying this person. Accepts both numeric ID and UUID. */
  id: string;
  format?: CreatePersonsSplitRequestFormat | (string & {});
  /** The distinct_id to **keep** on this person; every *other* distinct_id is moved to its own new single-id person. If omitted, the first distinct_id on the person is kept. The original person always retains its properties; to clear individual properties afterward, use the delete_property endpoint. To surgically *remove* one or more distinct_ids while leaving the merge intact, use `distinct_ids_to_split` instead — these parameters are inverses of each other and cannot be combined. */
  main_distinct_id?: string | null;
  /** List of distinct_ids to **move off** this person onto new single-id persons. The original person keeps every other distinct_id and its properties. New persons are created with deterministic UUIDs derived from `(team_id, distinct_id)`. Cannot be combined with `main_distinct_id`. */
  distinct_ids_to_split?: CreatePersonsSplitRequestDistinctIdsToSplitList | null;
}
export const CreatePersonsSplitRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    format: S.optional(CreatePersonsSplitRequestFormat.pipe(T.Query())),
    main_distinct_id: S.optional(S.NullOr(S.String)),
    distinct_ids_to_split: S.optional(S.NullOr(CreatePersonsSplitRequestDistinctIdsToSplitList)),
  }).pipe(
    T.Http({ method: "POST", uri: "/api/projects/{project_id}/persons/{id}/split/", code: 200 }),
  ),
).annotate({
  identifier: "CreatePersonsSplitRequest",
}) as any as S.Schema<CreatePersonsSplitRequest>;

export interface PersonSplitResponse {
  /** Always `true` when the split task was enqueued. The split itself runs asynchronously — a 201 response means the task was accepted, not that the merge state has already been updated. */
  success: boolean;
}
export const PersonSplitResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.Boolean,
  }),
).annotate({ identifier: "PersonSplitResponse" }) as any as S.Schema<PersonSplitResponse>;

export type GetPersonRequestFormat = "csv" | "json";
export const GetPersonRequestFormat = S.String;

export interface GetPersonRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique value identifying this person. Accepts both numeric ID and UUID. */
  id: string;
  format?: GetPersonRequestFormat | (string & {});
}
export const GetPersonRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    format: S.optional(GetPersonRequestFormat.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/{id}/", code: 200 })),
).annotate({ identifier: "GetPersonRequest" }) as any as S.Schema<GetPersonRequest>;

export type PersonRecordDistinctIdsList = Array<string>;
export const PersonRecordDistinctIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonRecordDistinctIdsList>;

export interface PersonRecord {
  /** Numeric person ID. */
  id?: number;
  /** Display name derived from person properties (email, name, or username). */
  name?: string;
  distinct_ids?: PersonRecordDistinctIdsList;
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
  /** When this person was first seen (ISO 8601). */
  created_at?: string;
  /** Unique identifier (UUID) for this person. */
  uuid?: string;
  /** Timestamp of the last event from this person, or null. */
  last_seen_at?: string | null;
}
export const PersonRecord = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    name: S.optional(S.String),
    distinct_ids: S.optional(PersonRecordDistinctIdsList),
    properties: S.optional(S.Unknown),
    created_at: S.optional(S.String),
    uuid: S.optional(S.String),
    last_seen_at: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "PersonRecord" }) as any as S.Schema<PersonRecord>;

export type GetPersonsActivityRequestFormat = "csv" | "json";
export const GetPersonsActivityRequestFormat = S.String;

export interface GetPersonsActivityRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this person. */
  id: number;
  format?: GetPersonsActivityRequestFormat | (string & {});
}
export const GetPersonsActivityRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
    format: S.optional(GetPersonsActivityRequestFormat.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/{id}/activity/", code: 200 }),
  ),
).annotate({
  identifier: "GetPersonsActivityRequest",
}) as any as S.Schema<GetPersonsActivityRequest>;

export interface GetPersonsActivityResponse {}
export const GetPersonsActivityResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "GetPersonsActivityResponse",
}) as any as S.Schema<GetPersonsActivityResponse>;

export type GetPersonsAllActivityRequestFormat = "csv" | "json";
export const GetPersonsAllActivityRequestFormat = S.String;

export interface GetPersonsAllActivityRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: GetPersonsAllActivityRequestFormat | (string & {});
}
export const GetPersonsAllActivityRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(GetPersonsAllActivityRequestFormat.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/activity/", code: 200 }),
  ),
).annotate({
  identifier: "GetPersonsAllActivityRequest",
}) as any as S.Schema<GetPersonsAllActivityRequest>;

export interface GetPersonsAllActivityResponse {}
export const GetPersonsAllActivityResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "GetPersonsAllActivityResponse",
}) as any as S.Schema<GetPersonsAllActivityResponse>;

export type GetPersonsCohortRequestFormat = "csv" | "json";
export const GetPersonsCohortRequestFormat = S.String;

export interface GetPersonsCohortRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: GetPersonsCohortRequestFormat | (string & {});
  /** The person ID or UUID to get cohorts for. */
  person_id: string;
}
export const GetPersonsCohortRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(GetPersonsCohortRequestFormat.pipe(T.Query())),
    person_id: S.String.pipe(T.Query()),
  }).pipe(T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/cohorts/", code: 200 })),
).annotate({ identifier: "GetPersonsCohortRequest" }) as any as S.Schema<GetPersonsCohortRequest>;

/** Minimal serializer for cohort references, read by the person cohorts endpoint. */
export interface CohortMinimal {
  id: number;
  name?: string | null;
  count?: number | null;
}
export const CohortMinimal = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.Number,
    name: S.optional(S.NullOr(S.String)),
    count: S.optional(S.NullOr(S.Number)),
  }),
).annotate({ identifier: "CohortMinimal" }) as any as S.Schema<CohortMinimal>;

/** Cohorts the person currently belongs to. */
export type PersonCohortsResponseResultsList = Array<CohortMinimal>;
export const PersonCohortsResponseResultsList = /*@__PURE__*/ S.Array(
  CohortMinimal,
) as any as S.Schema<PersonCohortsResponseResultsList>;

export interface PersonCohortsResponse {
  /** Cohorts the person currently belongs to. */
  results: PersonCohortsResponseResultsList;
}
export const PersonCohortsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    results: PersonCohortsResponseResultsList,
  }),
).annotate({ identifier: "PersonCohortsResponse" }) as any as S.Schema<PersonCohortsResponse>;

export type GetPersonsPropertiesAtTimeRequestFormat = "csv" | "json";
export const GetPersonsPropertiesAtTimeRequestFormat = S.String;

export interface GetPersonsPropertiesAtTimeRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** The distinct_id of the person (mutually exclusive with person_id) */
  distinct_id?: string;
  format?: GetPersonsPropertiesAtTimeRequestFormat | (string & {});
  /** Whether to handle $set_once operations (default: false) */
  include_set_once?: boolean;
  /** The person_id (UUID) to build properties for (mutually exclusive with distinct_id) */
  person_id?: string;
  /** ISO datetime string for the point in time (e.g., '2023-06-15T14:30:00Z') */
  timestamp: string;
}
export const GetPersonsPropertiesAtTimeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    distinct_id: S.optional(S.String.pipe(T.Query())),
    format: S.optional(GetPersonsPropertiesAtTimeRequestFormat.pipe(T.Query())),
    include_set_once: S.optional(S.Boolean.pipe(T.Query())),
    person_id: S.optional(S.String.pipe(T.Query())),
    timestamp: S.String.pipe(T.Query()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/persons/properties_at_time/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetPersonsPropertiesAtTimeRequest",
}) as any as S.Schema<GetPersonsPropertiesAtTimeRequest>;

/** All distinct IDs associated with this person */
export type PersonPropertiesAtTimeResponseDistinctIdsList = Array<string>;
export const PersonPropertiesAtTimeResponseDistinctIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonPropertiesAtTimeResponseDistinctIdsList>;

/** Person properties as they existed at the specified time */
export type PersonPropertiesAtTimeResponsePropertiesMap = {
  [key: string]: string | null | undefined;
};
export const PersonPropertiesAtTimeResponsePropertiesMap = /*@__PURE__*/ S.Record(
  S.String,
  S.NullOr(S.String),
) as any as S.Schema<PersonPropertiesAtTimeResponsePropertiesMap>;

/** All distinct_ids that were queried for this person */
export type PersonPropertiesAtTimeMetadataDistinctIdsQueriedList = Array<string>;
export const PersonPropertiesAtTimeMetadataDistinctIdsQueriedList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonPropertiesAtTimeMetadataDistinctIdsQueriedList>;

/** Serializer for the point-in-time query metadata. */
export interface PersonPropertiesAtTimeMetadata {
  /** The timestamp that was queried in ISO format */
  queried_timestamp?: string;
  /** Whether $set_once operations were included */
  include_set_once?: boolean;
  /** The distinct_id parameter used in the request */
  distinct_id_used?: string | null;
  /** The person_id parameter used in the request */
  person_id_used?: string | null;
  /** Whether the query used 'distinct_id' or 'person_id' mode */
  query_mode?: string;
  /** All distinct_ids that were queried for this person */
  distinct_ids_queried?: PersonPropertiesAtTimeMetadataDistinctIdsQueriedList;
  /** Number of distinct_ids associated with this person */
  distinct_ids_count?: number;
}
export const PersonPropertiesAtTimeMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    queried_timestamp: S.optional(S.String),
    include_set_once: S.optional(S.Boolean),
    distinct_id_used: S.optional(S.NullOr(S.String)),
    person_id_used: S.optional(S.NullOr(S.String)),
    query_mode: S.optional(S.String),
    distinct_ids_queried: S.optional(PersonPropertiesAtTimeMetadataDistinctIdsQueriedList),
    distinct_ids_count: S.optional(S.Number),
  }),
).annotate({
  identifier: "PersonPropertiesAtTimeMetadata",
}) as any as S.Schema<PersonPropertiesAtTimeMetadata>;

/** Serializer for the point-in-time person properties response. */
export interface PersonPropertiesAtTimeResponse {
  /** The person ID */
  id?: number;
  /** The person's display name */
  name?: string;
  /** All distinct IDs associated with this person */
  distinct_ids?: PersonPropertiesAtTimeResponseDistinctIdsList;
  /** Person properties as they existed at the specified time */
  properties?: PersonPropertiesAtTimeResponsePropertiesMap;
  /** When the person was first created */
  created_at?: string;
  /** The person's UUID */
  uuid?: string;
  /** When the person was last seen */
  last_seen_at?: string | null;
  /** Metadata about the point-in-time query */
  point_in_time_metadata?: PersonPropertiesAtTimeMetadata;
}
export const PersonPropertiesAtTimeResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    name: S.optional(S.String),
    distinct_ids: S.optional(PersonPropertiesAtTimeResponseDistinctIdsList),
    properties: S.optional(PersonPropertiesAtTimeResponsePropertiesMap),
    created_at: S.optional(S.String),
    uuid: S.optional(S.String),
    last_seen_at: S.optional(S.NullOr(S.String)),
    point_in_time_metadata: S.optional(PersonPropertiesAtTimeMetadata),
  }),
).annotate({
  identifier: "PersonPropertiesAtTimeResponse",
}) as any as S.Schema<PersonPropertiesAtTimeResponse>;

export type GetPersonsPropertiesTimelineRequestFormat = "csv" | "json";
export const GetPersonsPropertiesTimelineRequestFormat = S.String;

export interface GetPersonsPropertiesTimelineRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this person. */
  id: number;
  format?: GetPersonsPropertiesTimelineRequestFormat | (string & {});
}
export const GetPersonsPropertiesTimelineRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
    format: S.optional(GetPersonsPropertiesTimelineRequestFormat.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/persons/{id}/properties_timeline/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetPersonsPropertiesTimelineRequest",
}) as any as S.Schema<GetPersonsPropertiesTimelineRequest>;

export interface GetPersonsPropertiesTimelineResponse {}
export const GetPersonsPropertiesTimelineResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "GetPersonsPropertiesTimelineResponse",
}) as any as S.Schema<GetPersonsPropertiesTimelineResponse>;

export type GetPersonsValueRequestFormat = "csv" | "json";
export const GetPersonsValueRequestFormat = S.String;

export interface GetPersonsValueRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: GetPersonsValueRequestFormat | (string & {});
  /** The person property key to get values for (e.g., 'email', 'plan', 'role'). */
  key: string;
  /** Optional search string to filter values (case-insensitive substring match). */
  value?: string;
}
export const GetPersonsValueRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(GetPersonsValueRequestFormat.pipe(T.Query())),
    key: S.String.pipe(T.Query()),
    value: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/values/", code: 200 })),
).annotate({ identifier: "GetPersonsValueRequest" }) as any as S.Schema<GetPersonsValueRequest>;

export interface GetPersonsValueResponse {}
export const GetPersonsValueResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "GetPersonsValueResponse",
}) as any as S.Schema<GetPersonsValueResponse>;

export type ListPersonsRequestFormat = "csv" | "json";
export const ListPersonsRequestFormat = S.String;

export type PropertyGroupOperatorEnum = "AND" | "OR";
export const PropertyGroupOperatorEnum = S.String;

export type PropertyItemValueCase3Item = string | number;
export const PropertyItemValueCase3Item = S.Unknown as any as S.Schema<PropertyItemValueCase3Item>;

export type PropertyItemValueCase3List = Array<PropertyItemValueCase3Item>;
export const PropertyItemValueCase3List = /*@__PURE__*/ S.Array(
  PropertyItemValueCase3Item,
) as any as S.Schema<PropertyItemValueCase3List>;

/** Value of your filter. For example `test@example.com` or `https://example.com/test/`. Can be an array for an OR query, like `["test@example.com","ok@example.com"]` */
export type PropertyItemValue = string | number | boolean | PropertyItemValueCase3List;
export const PropertyItemValue = S.Unknown as any as S.Schema<PropertyItemValue>;

/** * `exact` - exact * `is_not` - is_not * `icontains` - icontains * `not_icontains` - not_icontains * `starts_with` - starts_with * `not_starts_with` - not_starts_with * `ends_with` - ends_with * `not_ends_with` - not_ends_with * `regex` - regex * `not_regex` - not_regex * `gt` - gt * `lt` - lt * `gte` - gte * `lte` - lte * `is_set` - is_set * `is_not_set` - is_not_set * `is_date_exact` - is_date_exact * `is_date_after` - is_date_after * `is_date_before` - is_date_before * `in` - in * `not_in` - not_in */
export type PropertyItemOperatorEnum =
  | "exact"
  | "is_not"
  | "icontains"
  | "not_icontains"
  | "starts_with"
  | "not_starts_with"
  | "ends_with"
  | "not_ends_with"
  | "regex"
  | "not_regex"
  | "gt"
  | "lt"
  | "gte"
  | "lte"
  | "is_set"
  | "is_not_set"
  | "is_date_exact"
  | "is_date_after"
  | "is_date_before"
  | "in"
  | "not_in";
export const PropertyItemOperatorEnum = S.String;

export type BlankEnum = "";
export const BlankEnum = S.String;

export type PropertyItemOperator = PropertyItemOperatorEnum | BlankEnum;
export const PropertyItemOperator = S.Unknown as any as S.Schema<PropertyItemOperator>;

/** * `event` - event * `event_metadata` - event_metadata * `feature` - feature * `person` - person * `person_metadata` - person_metadata * `cohort` - cohort * `element` - element * `static-cohort` - static-cohort * `dynamic-cohort` - dynamic-cohort * `precalculated-cohort` - precalculated-cohort * `group` - group * `recording` - recording * `log_entry` - log_entry * `behavioral` - behavioral * `session` - session * `hogql` - hogql * `data_warehouse` - data_warehouse * `data_warehouse_person_property` - data_warehouse_person_property * `error_tracking_issue` - error_tracking_issue * `log` - log * `log_attribute` - log_attribute * `log_resource_attribute` - log_resource_attribute * `metric_attribute` - metric_attribute * `span` - span * `span_attribute` - span_attribute * `span_resource_attribute` - span_resource_attribute * `revenue_analytics` - revenue_analytics * `account_custom_property` - account_custom_property * `flag` - flag * `workflow_variable` - workflow_variable */
export type PropertyFilterTypeEnum =
  | "event"
  | "event_metadata"
  | "feature"
  | "person"
  | "person_metadata"
  | "cohort"
  | "element"
  | "static-cohort"
  | "dynamic-cohort"
  | "precalculated-cohort"
  | "group"
  | "recording"
  | "log_entry"
  | "behavioral"
  | "session"
  | "hogql"
  | "data_warehouse"
  | "data_warehouse_person_property"
  | "error_tracking_issue"
  | "log"
  | "log_attribute"
  | "log_resource_attribute"
  | "metric_attribute"
  | "span"
  | "span_attribute"
  | "span_resource_attribute"
  | "revenue_analytics"
  | "account_custom_property"
  | "flag"
  | "workflow_variable";
export const PropertyFilterTypeEnum = S.String;

export type PropertyItemType = PropertyFilterTypeEnum | BlankEnum;
export const PropertyItemType = S.Unknown as any as S.Schema<PropertyItemType>;

export interface PropertyItem {
  /** Key of the property you're filtering on. For example `email` or `$current_url` */
  key?: string;
  /** Value of your filter. For example `test@example.com` or `https://example.com/test/`. Can be an array for an OR query, like `["test@example.com","ok@example.com"]` */
  value?: PropertyItemValue;
  operator?: PropertyItemOperator | null;
  type?: PropertyItemType;
}
export const PropertyItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    key: S.optional(S.String),
    value: S.optional(PropertyItemValue),
    operator: S.optional(S.NullOr(PropertyItemOperator)),
    type: S.optional(PropertyItemType),
  }),
).annotate({ identifier: "PropertyItem" }) as any as S.Schema<PropertyItem>;

export type PropertyValuesList = Array<PropertyItem>;
export const PropertyValuesList = /*@__PURE__*/ S.Array(
  PropertyItem,
) as any as S.Schema<PropertyValuesList>;

export interface Property {
  /** You can use a simplified version: ```json { "properties": [ { "key": "email", "value": "x@y.com", "operator": "exact", "type": "event" } ] } ``` Or you can create more complicated queries with AND and OR: ```json { "properties": { "type": "AND", "values": [ { "type": "OR", "values": [ {"key": "email", ...}, {"key": "email", ...} ] }, { "type": "AND", "values": [ {"key": "email", ...}, {"key": "email", ...} ] } ] ] } ``` * `AND` - AND * `OR` - OR */
  type?: PropertyGroupOperatorEnum | (string & {});
  values?: PropertyValuesList;
}
export const Property = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(PropertyGroupOperatorEnum),
    values: S.optional(PropertyValuesList),
  }),
).annotate({ identifier: "Property" }) as any as S.Schema<Property>;

export type ListPersonsRequestPropertiesList = Array<Property>;
export const ListPersonsRequestPropertiesList = /*@__PURE__*/ S.Array(
  Property,
) as any as S.Schema<ListPersonsRequestPropertiesList>;

export interface ListPersonsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Names the ClickHouse query this request runs. Send the same id to `DELETE /api/projects/:project_id/query/:client_query_id/` to stop a search that is still running. Up to 128 characters. */
  client_query_id?: string;
  /** Filter list by distinct id. */
  distinct_id?: string;
  /** Filter persons by email (exact match) */
  email?: string;
  format?: ListPersonsRequestFormat | (string & {});
  /** Tag each search result with `matched_fields`, the searched fields the term was found in. A complete email address that exactly matches a distinct ID then returns that person first, followed by every person whose email or name property contains the address. */
  include_matched_fields?: boolean;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter Persons by person properties. */
  properties?: ListPersonsRequestPropertiesList;
  /** Search persons by email, name, person ID, or distinct ID. Partial values match. When the term is a complete email address or UUID that exactly matches a distinct ID or person ID, only that person is returned. */
  search?: string;
}
export const ListPersonsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    client_query_id: S.optional(S.String.pipe(T.Query())),
    distinct_id: S.optional(S.String.pipe(T.Query())),
    email: S.optional(S.String.pipe(T.Query())),
    format: S.optional(ListPersonsRequestFormat.pipe(T.Query())),
    include_matched_fields: S.optional(S.Boolean.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    properties: S.optional(ListPersonsRequestPropertiesList.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/", code: 200 })),
).annotate({ identifier: "ListPersonsRequest" }) as any as S.Schema<ListPersonsRequest>;

export type PersonListRecordDistinctIdsList = Array<string>;
export const PersonListRecordDistinctIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonListRecordDistinctIdsList>;

/** * `distinct_id` - Distinct ID * `email` - Email * `name` - Name * `id` - Person ID */
export type PersonSearchMatchFieldEnum = "distinct_id" | "email" | "name" | "id";
export const PersonSearchMatchFieldEnum = S.String;

/** Only on a search result with `include_matched_fields`: the searched fields the term was found in. */
export type PersonListRecordMatchedFieldsList = Array<PersonSearchMatchFieldEnum>;
export const PersonListRecordMatchedFieldsList = /*@__PURE__*/ S.Array(
  PersonSearchMatchFieldEnum,
) as any as S.Schema<PersonListRecordMatchedFieldsList>;

export interface PersonListRecord {
  /** Numeric person ID. */
  id: number;
  /** Display name derived from person properties (email, name, or username). */
  name: string;
  distinct_ids: PersonListRecordDistinctIdsList;
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
  /** When this person was first seen (ISO 8601). */
  created_at: string;
  /** Unique identifier (UUID) for this person. */
  uuid: string;
  /** Timestamp of the last event from this person, or null. */
  last_seen_at: string | null;
  /** Only on a search result with `include_matched_fields`: the searched fields the term was found in. */
  matched_fields?: PersonListRecordMatchedFieldsList;
}
export const PersonListRecord = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.Number,
    name: S.String,
    distinct_ids: PersonListRecordDistinctIdsList,
    properties: S.optional(S.Unknown),
    created_at: S.String,
    uuid: S.String,
    last_seen_at: S.NullOr(S.String),
    matched_fields: S.optional(PersonListRecordMatchedFieldsList),
  }),
).annotate({ identifier: "PersonListRecord" }) as any as S.Schema<PersonListRecord>;

export type PaginatedPersonListRecordListResultsList = Array<PersonListRecord>;
export const PaginatedPersonListRecordListResultsList = /*@__PURE__*/ S.Array(
  PersonListRecord,
) as any as S.Schema<PaginatedPersonListRecordListResultsList>;

export interface PaginatedPersonListRecordList {
  next?: string | null;
  previous?: string | null;
  count?: number;
  results?: PaginatedPersonListRecordListResultsList;
}
export const PaginatedPersonListRecordList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    count: S.optional(S.Number),
    results: S.optional(PaginatedPersonListRecordListResultsList),
  }),
).annotate({
  identifier: "PaginatedPersonListRecordList",
}) as any as S.Schema<PaginatedPersonListRecordList>;

export type ListPersonsDeletionStatusRequestFormat = "csv" | "json";
export const ListPersonsDeletionStatusRequestFormat = S.String;

export type ListPersonsDeletionStatusRequestStatus = "all" | "completed" | "pending";
export const ListPersonsDeletionStatusRequestStatus = S.String;

export interface ListPersonsDeletionStatusRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: ListPersonsDeletionStatusRequestFormat | (string & {});
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by a specific person UUID. */
  person_uuid?: string;
  /** Filter by deletion status: 'pending', 'completed', or 'all'. */
  status?: ListPersonsDeletionStatusRequestStatus | (string & {});
}
export const ListPersonsDeletionStatusRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(ListPersonsDeletionStatusRequestFormat.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    person_uuid: S.optional(S.String.pipe(T.Query())),
    status: S.optional(ListPersonsDeletionStatusRequestStatus.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/persons/deletion_status/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListPersonsDeletionStatusRequest",
}) as any as S.Schema<ListPersonsDeletionStatusRequest>;

export interface AsyncDeletionStatus {
  /** The UUID of the person whose events are queued for deletion. */
  person_uuid?: string;
  /** When the deletion was requested. */
  created_at?: string;
  /** Current status: 'pending' or 'completed'. */
  status?: string;
  /** When the deletion was verified complete. Null if still pending. */
  delete_verified_at?: string | null;
}
export const AsyncDeletionStatus = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    person_uuid: S.optional(S.String),
    created_at: S.optional(S.String),
    status: S.optional(S.String),
    delete_verified_at: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "AsyncDeletionStatus" }) as any as S.Schema<AsyncDeletionStatus>;

export type PaginatedAsyncDeletionStatusListResultsList = Array<AsyncDeletionStatus>;
export const PaginatedAsyncDeletionStatusListResultsList = /*@__PURE__*/ S.Array(
  AsyncDeletionStatus,
) as any as S.Schema<PaginatedAsyncDeletionStatusListResultsList>;

export interface PaginatedAsyncDeletionStatusList {
  next?: string | null;
  previous?: string | null;
  count?: number;
  results?: PaginatedAsyncDeletionStatusListResultsList;
}
export const PaginatedAsyncDeletionStatusList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    count: S.optional(S.Number),
    results: S.optional(PaginatedAsyncDeletionStatusListResultsList),
  }),
).annotate({
  identifier: "PaginatedAsyncDeletionStatusList",
}) as any as S.Schema<PaginatedAsyncDeletionStatusList>;

export type ListPersonsEmailsRequestFormat = "csv" | "json";
export const ListPersonsEmailsRequestFormat = S.String;

export interface ListPersonsEmailsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this person. */
  id: number;
  /** Start of the time range, matched on sent time. Relative ('-30d', '-24h') or ISO 8601. Defaults to -30d (the retention window) — bounds the ClickHouse partition scan. */
  after?: string;
  /** End of the time range, matched on sent time. Same format as 'after'. Defaults to now. */
  before?: string;
  format?: ListPersonsEmailsRequestFormat | (string & {});
  /** Maximum number of assets to return (1-500, default 50). */
  limit?: number;
  /** Number of assets to skip, for pagination. */
  offset?: number;
}
export const ListPersonsEmailsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
    after: S.optional(S.String.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    format: S.optional(ListPersonsEmailsRequestFormat.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/persons/{id}/emails/", code: 200 }),
  ),
).annotate({ identifier: "ListPersonsEmailsRequest" }) as any as S.Schema<ListPersonsEmailsRequest>;

export interface MessageAsset {
  /** The workflow run this email was sent in. */
  invocation_id: string;
  /** The email step (action node) within the workflow that sent this email. */
  action_id: string;
  /** The workflow id that sent this email — used to navigate from a person's Emails tab back into the originating workflow. */
  function_id: string;
  /** Human-readable workflow name for display. Empty when the workflow has been deleted; clients should fall back to function_id in that case. */
  function_name: string;
  /** The batch run this email belongs to, for batch-triggered workflows. Empty for event-triggered runs. */
  parent_run_id: string;
  /** Message channel this asset was sent on: 'email' or 'push'. The per-person endpoints return one channel each. */
  kind: string;
  /** The recipient's distinct_id. */
  distinct_id: string;
  /** The recipient's person UUID, if resolved. */
  person_id: string;
  /** Who the message went to: the email address for 'email', or the recipient's distinct ID for 'push'. */
  recipient: string;
  /** The email subject line, or the push notification title. */
  subject: string;
  /** Delivery status at capture time. Currently always 'sent' - only delivered messages are captured. */
  status: string;
  /** When the message was sent. */
  sent_at: string;
}
export const MessageAsset = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    invocation_id: S.String,
    action_id: S.String,
    function_id: S.String,
    function_name: S.String,
    parent_run_id: S.String,
    kind: S.String,
    distinct_id: S.String,
    person_id: S.String,
    recipient: S.String,
    subject: S.String,
    status: S.String,
    sent_at: S.String,
  }),
).annotate({ identifier: "MessageAsset" }) as any as S.Schema<MessageAsset>;

export type ListPersonsEmailsResponseBodyList = Array<MessageAsset>;
export const ListPersonsEmailsResponseBodyList = /*@__PURE__*/ S.Array(
  MessageAsset,
) as any as S.Schema<ListPersonsEmailsResponseBodyList>;

export type ListPersonsEmailsResponse = ListPersonsEmailsResponseBodyList;
export const ListPersonsEmailsResponse = /*@__PURE__*/ S.suspend(() =>
  ListPersonsEmailsResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListPersonsEmailsResponse",
}) as any as S.Schema<ListPersonsEmailsResponse>;

export type ListPersonsPushNotificationsRequestFormat = "csv" | "json";
export const ListPersonsPushNotificationsRequestFormat = S.String;

export interface ListPersonsPushNotificationsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique integer value identifying this person. */
  id: number;
  /** Start of the time range, matched on sent time. Relative ('-30d', '-24h') or ISO 8601. Defaults to -30d (the retention window) — bounds the ClickHouse partition scan. */
  after?: string;
  /** End of the time range, matched on sent time. Same format as 'after'. Defaults to now. */
  before?: string;
  format?: ListPersonsPushNotificationsRequestFormat | (string & {});
  /** Maximum number of assets to return (1-500, default 50). */
  limit?: number;
  /** Number of assets to skip, for pagination. */
  offset?: number;
}
export const ListPersonsPushNotificationsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.Number.pipe(T.Label()),
    after: S.optional(S.String.pipe(T.Query())),
    before: S.optional(S.String.pipe(T.Query())),
    format: S.optional(ListPersonsPushNotificationsRequestFormat.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/persons/{id}/push_notifications/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListPersonsPushNotificationsRequest",
}) as any as S.Schema<ListPersonsPushNotificationsRequest>;

export type ListPersonsPushNotificationsResponseBodyList = Array<MessageAsset>;
export const ListPersonsPushNotificationsResponseBodyList = /*@__PURE__*/ S.Array(
  MessageAsset,
) as any as S.Schema<ListPersonsPushNotificationsResponseBodyList>;

export type ListPersonsPushNotificationsResponse = ListPersonsPushNotificationsResponseBodyList;
export const ListPersonsPushNotificationsResponse = /*@__PURE__*/ S.suspend(() =>
  ListPersonsPushNotificationsResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListPersonsPushNotificationsResponse",
}) as any as S.Schema<ListPersonsPushNotificationsResponse>;

export type PersonsBulkDeleteCreateRequestFormat = "csv" | "json";
export const PersonsBulkDeleteCreateRequestFormat = S.String;

/** A list of PostHog person UUIDs to delete (max 1000). */
export type PersonsBulkDeleteCreateRequestIdsList = Array<string>;
export const PersonsBulkDeleteCreateRequestIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonsBulkDeleteCreateRequestIdsList>;

/** A list of distinct IDs whose associated persons will be deleted (max 1000). */
export type PersonsBulkDeleteCreateRequestDistinctIdsList = Array<string>;
export const PersonsBulkDeleteCreateRequestDistinctIdsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonsBulkDeleteCreateRequestDistinctIdsList>;

export interface PersonsBulkDeleteCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: PersonsBulkDeleteCreateRequestFormat | (string & {});
  /** A list of PostHog person UUIDs to delete (max 1000). */
  ids?: PersonsBulkDeleteCreateRequestIdsList;
  /** A list of distinct IDs whose associated persons will be deleted (max 1000). */
  distinct_ids?: PersonsBulkDeleteCreateRequestDistinctIdsList;
  /** If true, queue deletion of all events associated with these persons. */
  delete_events?: boolean;
  /** If true, queue deletion of all recordings associated with these persons. */
  delete_recordings?: boolean;
  /** If true, keep the person records but delete their events and recordings. */
  keep_person?: boolean;
}
export const PersonsBulkDeleteCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(PersonsBulkDeleteCreateRequestFormat.pipe(T.Query())),
    ids: S.optional(PersonsBulkDeleteCreateRequestIdsList),
    distinct_ids: S.optional(PersonsBulkDeleteCreateRequestDistinctIdsList),
    delete_events: S.optional(S.Boolean),
    delete_recordings: S.optional(S.Boolean),
    keep_person: S.optional(S.Boolean),
  }).pipe(
    T.Http({ method: "POST", uri: "/api/projects/{project_id}/persons/bulk_delete/", code: 200 }),
  ),
).annotate({
  identifier: "PersonsBulkDeleteCreateRequest",
}) as any as S.Schema<PersonsBulkDeleteCreateRequest>;

export interface PersonsBulkDeleteCreateResponse {}
export const PersonsBulkDeleteCreateResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate(
  { identifier: "PersonsBulkDeleteCreateResponse" },
) as any as S.Schema<PersonsBulkDeleteCreateResponse>;

export type PersonsDeletePropertyCreateRequestFormat = "csv" | "json";
export const PersonsDeletePropertyCreateRequestFormat = S.String;

export type PersonsDeletePropertyCreateRequestUnsetCase1List = Array<string>;
export const PersonsDeletePropertyCreateRequestUnsetCase1List = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<PersonsDeletePropertyCreateRequestUnsetCase1List>;

/** A property key, or a list of property keys, to remove from this person. */
export type PersonsDeletePropertyCreateRequestUnset =
  | string
  | PersonsDeletePropertyCreateRequestUnsetCase1List;
export const PersonsDeletePropertyCreateRequestUnset =
  S.Unknown as any as S.Schema<PersonsDeletePropertyCreateRequestUnset>;

export interface PersonsDeletePropertyCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique value identifying this person. Accepts both numeric ID and UUID. */
  id: string;
  format?: PersonsDeletePropertyCreateRequestFormat | (string & {});
  /** A property key, or a list of property keys, to remove from this person. */
  _unset?: PersonsDeletePropertyCreateRequestUnset;
}
export const PersonsDeletePropertyCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    format: S.optional(PersonsDeletePropertyCreateRequestFormat.pipe(T.Query())),
    _unset: S.optional(PersonsDeletePropertyCreateRequestUnset.pipe(T.Body("$unset"))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/persons/{id}/delete_property/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PersonsDeletePropertyCreateRequest",
}) as any as S.Schema<PersonsDeletePropertyCreateRequest>;

export interface PersonsDeletePropertyCreateResponse {}
export const PersonsDeletePropertyCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PersonsDeletePropertyCreateResponse",
}) as any as S.Schema<PersonsDeletePropertyCreateResponse>;

export type PersonsResetPersonDistinctIdCreateRequestFormat = "csv" | "json";
export const PersonsResetPersonDistinctIdCreateRequestFormat = S.String;

export interface PersonsResetPersonDistinctIdCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  format?: PersonsResetPersonDistinctIdCreateRequestFormat | (string & {});
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
}
export const PersonsResetPersonDistinctIdCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    format: S.optional(PersonsResetPersonDistinctIdCreateRequestFormat.pipe(T.Query())),
    properties: S.optional(S.Unknown),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/persons/reset_person_distinct_id/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PersonsResetPersonDistinctIdCreateRequest",
}) as any as S.Schema<PersonsResetPersonDistinctIdCreateRequest>;

export interface PersonsResetPersonDistinctIdCreateResponse {}
export const PersonsResetPersonDistinctIdCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PersonsResetPersonDistinctIdCreateResponse",
}) as any as S.Schema<PersonsResetPersonDistinctIdCreateResponse>;

export type PersonsUpdatePropertyCreateRequestFormat = "csv" | "json";
export const PersonsUpdatePropertyCreateRequestFormat = S.String;

export interface PersonsUpdatePropertyCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique value identifying this person. Accepts both numeric ID and UUID. */
  id: string;
  format?: PersonsUpdatePropertyCreateRequestFormat | (string & {});
  /** The property key to set. */
  key?: string;
  /** The property value. Can be a string, number, boolean, or object. */
  value?: unknown;
}
export const PersonsUpdatePropertyCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    format: S.optional(PersonsUpdatePropertyCreateRequestFormat.pipe(T.Query())),
    key: S.optional(S.String),
    value: S.optional(S.Unknown),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/persons/{id}/update_property/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PersonsUpdatePropertyCreateRequest",
}) as any as S.Schema<PersonsUpdatePropertyCreateRequest>;

export interface PersonsUpdatePropertyCreateResponse {}
export const PersonsUpdatePropertyCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PersonsUpdatePropertyCreateResponse",
}) as any as S.Schema<PersonsUpdatePropertyCreateResponse>;

export type UpdatePersonRequestFormat = "csv" | "json";
export const UpdatePersonRequestFormat = S.String;

export interface UpdatePersonRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique value identifying this person. Accepts both numeric ID and UUID. */
  id: string;
  format?: UpdatePersonRequestFormat | (string & {});
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
}
export const UpdatePersonRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    format: S.optional(UpdatePersonRequestFormat.pipe(T.Query())),
    properties: S.optional(S.Unknown),
  }).pipe(T.Http({ method: "PUT", uri: "/api/projects/{project_id}/persons/{id}/", code: 200 })),
).annotate({ identifier: "UpdatePersonRequest" }) as any as S.Schema<UpdatePersonRequest>;

export type UpdatePersonsPartialRequestFormat = "csv" | "json";
export const UpdatePersonsPartialRequestFormat = S.String;

export interface UpdatePersonsPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A unique value identifying this person. Accepts both numeric ID and UUID. */
  id: string;
  format?: UpdatePersonsPartialRequestFormat | (string & {});
  /** Key-value map of person properties set via $set and $set_once operations. */
  properties?: unknown;
}
export const UpdatePersonsPartialRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    format: S.optional(UpdatePersonsPartialRequestFormat.pipe(T.Query())),
    properties: S.optional(S.Unknown),
  }).pipe(T.Http({ method: "PATCH", uri: "/api/projects/{project_id}/persons/{id}/", code: 200 })),
).annotate({
  identifier: "UpdatePersonsPartialRequest",
}) as any as S.Schema<UpdatePersonsPartialRequest>;

export type CreatePersonsBatchByDistinctIdsError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const createPersonsBatchByDistinctIds: API.OperationMethod<
  CreatePersonsBatchByDistinctIdsRequest,
  CreatePersonsBatchByDistinctIdsResponse,
  CreatePersonsBatchByDistinctIdsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreatePersonsBatchByDistinctIdsRequest,
  output: CreatePersonsBatchByDistinctIdsResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreatePersonsBatchByUuidError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const createPersonsBatchByUuid: API.OperationMethod<
  CreatePersonsBatchByUuidRequest,
  CreatePersonsBatchByUuidResponse,
  CreatePersonsBatchByUuidError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreatePersonsBatchByUuidRequest,
  output: CreatePersonsBatchByUuidResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreatePersonsSplitError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** Split distinct_ids off a merged person. Two mutually exclusive modes: - **`distinct_ids_to_split`** (recommended for surgical edits): moves only the listed distinct_ids off this person onto new single-id persons. The original person keeps every other distinct_id and its properties. - **`main_distinct_id`**: keeps only the specified distinct_id on this person; moves every *other* distinct_id off onto its own new person. If omitted, the first distinct_id is kept. The original person always retains its properties. To clear individual properties afterward, use the `delete_property` endpoint. The split runs asynchronously: a 201 response means the task was enqueued. Newly-created split-off persons get a deterministic UUID derived from `(team_id, distinct_id)`, so they can be located client-side without polling. If you need to delete a split-off person after this call, prefer looking it up by that deterministic UUID rather than by distinct_id, since the latter still resolves to the original merged person until the async task completes. */
export const createPersonsSplit: API.OperationMethod<
  CreatePersonsSplitRequest,
  PersonSplitResponse,
  CreatePersonsSplitError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreatePersonsSplitRequest,
  output: PersonSplitResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const getPerson: API.OperationMethod<
  GetPersonRequest,
  PersonRecord,
  GetPersonError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonRequest,
  output: PersonRecord,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonsActivityError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const getPersonsActivity: API.OperationMethod<
  GetPersonsActivityRequest,
  GetPersonsActivityResponse,
  GetPersonsActivityError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonsActivityRequest,
  output: GetPersonsActivityResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonsAllActivityError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const getPersonsAllActivity: API.OperationMethod<
  GetPersonsAllActivityRequest,
  GetPersonsAllActivityResponse,
  GetPersonsAllActivityError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonsAllActivityRequest,
  output: GetPersonsAllActivityResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonsCohortError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const getPersonsCohort: API.OperationMethod<
  GetPersonsCohortRequest,
  PersonCohortsResponse,
  GetPersonsCohortError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonsCohortRequest,
  output: PersonCohortsResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonsPropertiesAtTimeError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** Get person properties as they existed at a specific point in time. This endpoint reconstructs person properties by querying ClickHouse events for $set and $set_once operations up to the specified timestamp. Query parameters: - distinct_id: The distinct_id of the person - timestamp: ISO datetime string for the point in time (e.g., "2023-06-15T14:30:00Z") - include_set_once: Whether to handle $set_once operations (default: false) */
export const getPersonsPropertiesAtTime: API.OperationMethod<
  GetPersonsPropertiesAtTimeRequest,
  PersonPropertiesAtTimeResponse,
  GetPersonsPropertiesAtTimeError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonsPropertiesAtTimeRequest,
  output: PersonPropertiesAtTimeResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonsPropertiesTimelineError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const getPersonsPropertiesTimeline: API.OperationMethod<
  GetPersonsPropertiesTimelineRequest,
  GetPersonsPropertiesTimelineResponse,
  GetPersonsPropertiesTimelineError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonsPropertiesTimelineRequest,
  output: GetPersonsPropertiesTimelineResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetPersonsValueError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const getPersonsValue: API.OperationMethod<
  GetPersonsValueRequest,
  GetPersonsValueResponse,
  GetPersonsValueError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPersonsValueRequest,
  output: GetPersonsValueResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListPersonsError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const listPersons: API.OperationMethod<
  ListPersonsRequest,
  PaginatedPersonListRecordList,
  ListPersonsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListPersonsRequest,
  output: PaginatedPersonListRecordList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListPersonsDeletionStatusError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** List the status of queued event deletions for persons. When you delete a person with `delete_events=true`, an async deletion is queued. Use this endpoint to check whether those deletions are still pending or have been completed. */
export const listPersonsDeletionStatus: API.OperationMethod<
  ListPersonsDeletionStatusRequest,
  PaginatedAsyncDeletionStatusList,
  ListPersonsDeletionStatusError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListPersonsDeletionStatusRequest,
  output: PaginatedAsyncDeletionStatusList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListPersonsEmailsError = PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const listPersonsEmails: API.OperationMethod<
  ListPersonsEmailsRequest,
  ListPersonsEmailsResponse,
  ListPersonsEmailsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListPersonsEmailsRequest,
  output: ListPersonsEmailsResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListPersonsPushNotificationsError = PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const listPersonsPushNotifications: API.OperationMethod<
  ListPersonsPushNotificationsRequest,
  ListPersonsPushNotificationsResponse,
  ListPersonsPushNotificationsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListPersonsPushNotificationsRequest,
  output: ListPersonsPushNotificationsResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type PersonsBulkDeleteCreateError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint allows you to bulk delete persons, either by the PostHog person IDs or by distinct IDs. You can pass in a maximum of 1000 IDs per call. Only events captured before the request will be deleted. Person records are removed in the background shortly after the request returns, so a successful response reports them in `persons_queued_for_deletion` and `persons_deleted` is 0. */
export const personsBulkDeleteCreate: API.OperationMethod<
  PersonsBulkDeleteCreateRequest,
  PersonsBulkDeleteCreateResponse,
  PersonsBulkDeleteCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonsBulkDeleteCreateRequest,
  output: PersonsBulkDeleteCreateResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type PersonsDeletePropertyCreateError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const personsDeletePropertyCreate: API.OperationMethod<
  PersonsDeletePropertyCreateRequest,
  PersonsDeletePropertyCreateResponse,
  PersonsDeletePropertyCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonsDeletePropertyCreateRequest,
  output: PersonsDeletePropertyCreateResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type PersonsResetPersonDistinctIdCreateError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
/** Fix a distinct_id that stays hidden after its person was deleted and created again. Does nothing if no live person uses this distinct_id. In that case, send a new event for it instead. */
export const personsResetPersonDistinctIdCreate: API.OperationMethod<
  PersonsResetPersonDistinctIdCreateRequest,
  PersonsResetPersonDistinctIdCreateResponse,
  PersonsResetPersonDistinctIdCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonsResetPersonDistinctIdCreateRequest,
  output: PersonsResetPersonDistinctIdCreateResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type PersonsUpdatePropertyCreateError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const personsUpdatePropertyCreate: API.OperationMethod<
  PersonsUpdatePropertyCreateRequest,
  PersonsUpdatePropertyCreateResponse,
  PersonsUpdatePropertyCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PersonsUpdatePropertyCreateRequest,
  output: PersonsUpdatePropertyCreateResponse,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdatePersonError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** Only for setting properties on the person. "properties" from the request data will be updated via a "$set" event. This means that only the properties listed will be updated, but other properties won't be removed nor updated. If you would like to remove a property use the `delete_property` endpoint. */
export const updatePerson: API.OperationMethod<
  UpdatePersonRequest,
  PersonRecord,
  UpdatePersonError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdatePersonRequest,
  output: PersonRecord,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdatePersonsPartialError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** This endpoint is meant for reading and deleting persons. To create or update persons, we recommend using the [capture API](https://posthog.com/docs/api/capture), the `$set` and `$unset` [properties](https://posthog.com/docs/product-analytics/user-properties), or one of our SDKs. */
export const updatePersonsPartial: API.OperationMethod<
  UpdatePersonsPartialRequest,
  PersonRecord,
  UpdatePersonsPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdatePersonsPartialRequest,
  output: PersonRecord,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
