import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { PosthogProtocol, type PosthogOpError, type PosthogOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** * `trusted` - Trusted * `full` - Full * `custom` - Custom */
export type SandboxEnvironmentNetworkAccessLevelEnum = "trusted" | "full" | "custom";
export const SandboxEnvironmentNetworkAccessLevelEnum = S.String;

/** Allowed domains for custom network access. */
export type CreateSandboxRequestAllowedDomainsList = Array<string>;
export const CreateSandboxRequestAllowedDomainsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateSandboxRequestAllowedDomainsList>;

/** Repositories this environment applies to (format: org/repo). */
export type CreateSandboxRequestRepositoriesList = Array<string>;
export const CreateSandboxRequestRepositoriesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateSandboxRequestRepositoriesList>;

export interface CreateSandboxRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Display name for the environment. */
  name: string;
  /** Network access policy: trusted (default allowlist), full (unrestricted), or custom. * `trusted` - Trusted * `full` - Full * `custom` - Custom */
  network_access_level?: SandboxEnvironmentNetworkAccessLevelEnum | (string & {});
  /** Allowed domains for custom network access. */
  allowed_domains?: CreateSandboxRequestAllowedDomainsList;
  /** Whether to include default trusted domains (GitHub, npm, PyPI). */
  include_default_domains?: boolean;
  /** Repositories this environment applies to (format: org/repo). */
  repositories?: CreateSandboxRequestRepositoriesList;
  /** Encrypted environment variables (write-only, never returned in responses). */
  environment_variables?: unknown;
  /** If true, only the creator can see this environment; otherwise the whole team can. */
  private?: boolean;
  /** Custom base image for this environment's sandboxes (Modal VM runtime only); null uses the default base. */
  custom_image_id?: string | null;
}
export const CreateSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    name: S.String,
    network_access_level: S.optional(SandboxEnvironmentNetworkAccessLevelEnum),
    allowed_domains: S.optional(CreateSandboxRequestAllowedDomainsList),
    include_default_domains: S.optional(S.Boolean),
    repositories: S.optional(CreateSandboxRequestRepositoriesList),
    environment_variables: S.optional(S.Unknown),
    private: S.optional(S.Boolean),
    custom_image_id: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({ method: "POST", uri: "/api/projects/{project_id}/sandbox_environments/", code: 200 }),
  ),
).annotate({ identifier: "CreateSandboxRequest" }) as any as S.Schema<CreateSandboxRequest>;

export type SandboxEnvironmentDTOAllowedDomainsList = Array<string>;
export const SandboxEnvironmentDTOAllowedDomainsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SandboxEnvironmentDTOAllowedDomainsList>;

export type SandboxEnvironmentDTORepositoriesList = Array<string>;
export const SandboxEnvironmentDTORepositoriesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SandboxEnvironmentDTORepositoriesList>;

/** Names of the environment variables that are set, sorted. Values are write-only and never returned. */
export type SandboxEnvironmentDTOEnvironmentVariableKeysList = Array<string>;
export const SandboxEnvironmentDTOEnvironmentVariableKeysList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SandboxEnvironmentDTOEnvironmentVariableKeysList>;

export type SandboxEnvironmentDTOEffectiveDomainsList = Array<string>;
export const SandboxEnvironmentDTOEffectiveDomainsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<SandboxEnvironmentDTOEffectiveDomainsList>;

export type TaskUserBasicInfoHedgehogConfigMap = { [key: string]: unknown | undefined };
export const TaskUserBasicInfoHedgehogConfigMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<TaskUserBasicInfoHedgehogConfigMap>;

/** Response shape for a task creator, mirroring core ``UserBasicSerializer`` output. */
export interface TaskUserBasicInfo {
  id: number;
  uuid: string;
  distinct_id: string;
  first_name: string;
  last_name: string;
  email: string;
  is_email_verified?: boolean | null;
  hedgehog_config?: TaskUserBasicInfoHedgehogConfigMap | null;
  role_at_organization?: string | null;
}
export const TaskUserBasicInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.Number,
    uuid: S.String,
    distinct_id: S.String,
    first_name: S.String,
    last_name: S.String,
    email: S.String,
    is_email_verified: S.optional(S.NullOr(S.Boolean)),
    hedgehog_config: S.optional(S.NullOr(TaskUserBasicInfoHedgehogConfigMap)),
    role_at_organization: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "TaskUserBasicInfo" }) as any as S.Schema<TaskUserBasicInfo>;

/** A sandbox environment, as returned by list, detail, create and update. */
export interface SandboxEnvironmentDTO {
  id: string;
  name: string;
  network_access_level: string;
  allowed_domains?: SandboxEnvironmentDTOAllowedDomainsList;
  include_default_domains: boolean;
  repositories?: SandboxEnvironmentDTORepositoriesList;
  /** Whether any environment variables are set on this environment. */
  has_environment_variables?: boolean;
  /** Names of the environment variables that are set, sorted. Values are write-only and never returned. */
  environment_variable_keys?: SandboxEnvironmentDTOEnvironmentVariableKeysList;
  private: boolean;
  internal: boolean;
  effective_domains?: SandboxEnvironmentDTOEffectiveDomainsList;
  created_by?: TaskUserBasicInfo | null;
  created_at?: string | null;
  updated_at?: string | null;
  custom_image_id?: string | null;
  custom_image_name?: string | null;
  custom_image_status?: string | null;
}
export const SandboxEnvironmentDTO = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    network_access_level: S.String,
    allowed_domains: S.optional(SandboxEnvironmentDTOAllowedDomainsList),
    include_default_domains: S.Boolean,
    repositories: S.optional(SandboxEnvironmentDTORepositoriesList),
    has_environment_variables: S.optional(S.Boolean),
    environment_variable_keys: S.optional(SandboxEnvironmentDTOEnvironmentVariableKeysList),
    private: S.Boolean,
    internal: S.Boolean,
    effective_domains: S.optional(SandboxEnvironmentDTOEffectiveDomainsList),
    created_by: S.optional(S.NullOr(TaskUserBasicInfo)),
    created_at: S.optional(S.NullOr(S.String)),
    updated_at: S.optional(S.NullOr(S.String)),
    custom_image_id: S.optional(S.NullOr(S.String)),
    custom_image_name: S.optional(S.NullOr(S.String)),
    custom_image_status: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "SandboxEnvironmentDTO" }) as any as S.Schema<SandboxEnvironmentDTO>;

export interface GetSandboxRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/sandbox_environments/{id}/",
      code: 200,
    }),
  ),
).annotate({ identifier: "GetSandboxRequest" }) as any as S.Schema<GetSandboxRequest>;

export interface ListSandboxRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/sandbox_environments/", code: 200 }),
  ),
).annotate({ identifier: "ListSandboxRequest" }) as any as S.Schema<ListSandboxRequest>;

export type PaginatedSandboxEnvironmentDTOListResultsList = Array<SandboxEnvironmentDTO>;
export const PaginatedSandboxEnvironmentDTOListResultsList = /*@__PURE__*/ S.Array(
  SandboxEnvironmentDTO,
) as any as S.Schema<PaginatedSandboxEnvironmentDTOListResultsList>;

export interface PaginatedSandboxEnvironmentDTOList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedSandboxEnvironmentDTOListResultsList;
}
export const PaginatedSandboxEnvironmentDTOList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: PaginatedSandboxEnvironmentDTOListResultsList,
  }),
).annotate({
  identifier: "PaginatedSandboxEnvironmentDTOList",
}) as any as S.Schema<PaginatedSandboxEnvironmentDTOList>;

export interface SandboxDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const SandboxDestroyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/api/projects/{project_id}/sandbox_environments/{id}/",
      code: 200,
    }),
  ),
).annotate({ identifier: "SandboxDestroyRequest" }) as any as S.Schema<SandboxDestroyRequest>;

export interface SandboxDestroyResponse {}
export const SandboxDestroyResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "SandboxDestroyResponse",
}) as any as S.Schema<SandboxDestroyResponse>;

/** Allowed domains for custom network access. */
export type UpdateSandboxPartialRequestAllowedDomainsList = Array<string>;
export const UpdateSandboxPartialRequestAllowedDomainsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateSandboxPartialRequestAllowedDomainsList>;

/** Repositories this environment applies to (format: org/repo). */
export type UpdateSandboxPartialRequestRepositoriesList = Array<string>;
export const UpdateSandboxPartialRequestRepositoriesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateSandboxPartialRequestRepositoriesList>;

export interface UpdateSandboxPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** Display name for the environment. */
  name?: string;
  /** Network access policy: trusted (default allowlist), full (unrestricted), or custom. * `trusted` - Trusted * `full` - Full * `custom` - Custom */
  network_access_level?: SandboxEnvironmentNetworkAccessLevelEnum | (string & {});
  /** Allowed domains for custom network access. */
  allowed_domains?: UpdateSandboxPartialRequestAllowedDomainsList;
  /** Whether to include default trusted domains (GitHub, npm, PyPI). */
  include_default_domains?: boolean;
  /** Repositories this environment applies to (format: org/repo). */
  repositories?: UpdateSandboxPartialRequestRepositoriesList;
  /** Encrypted environment variables (write-only, never returned in responses). */
  environment_variables?: unknown;
  /** If true, only the creator can see this environment; otherwise the whole team can. */
  private?: boolean;
  /** Custom base image for this environment's sandboxes (Modal VM runtime only); null uses the default base. */
  custom_image_id?: string | null;
}
export const UpdateSandboxPartialRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    network_access_level: S.optional(SandboxEnvironmentNetworkAccessLevelEnum),
    allowed_domains: S.optional(UpdateSandboxPartialRequestAllowedDomainsList),
    include_default_domains: S.optional(S.Boolean),
    repositories: S.optional(UpdateSandboxPartialRequestRepositoriesList),
    environment_variables: S.optional(S.Unknown),
    private: S.optional(S.Boolean),
    custom_image_id: S.optional(S.NullOr(S.String)),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/api/projects/{project_id}/sandbox_environments/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateSandboxPartialRequest",
}) as any as S.Schema<UpdateSandboxPartialRequest>;

export type CreateSandboxError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** API for managing sandbox environments that control network access for task runs. */
export const createSandbox: API.OperationMethod<
  CreateSandboxRequest,
  SandboxEnvironmentDTO,
  CreateSandboxError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSandboxRequest,
  output: SandboxEnvironmentDTO,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetSandboxError = Forbidden | NotFound | PosthogOpError;
/** API for managing sandbox environments that control network access for task runs. */
export const getSandbox: API.OperationMethod<
  GetSandboxRequest,
  SandboxEnvironmentDTO,
  GetSandboxError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSandboxRequest,
  output: SandboxEnvironmentDTO,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListSandboxError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** API for managing sandbox environments that control network access for task runs. */
export const listSandbox: API.OperationMethod<
  ListSandboxRequest,
  PaginatedSandboxEnvironmentDTOList,
  ListSandboxError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListSandboxRequest,
  output: PaginatedSandboxEnvironmentDTOList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SandboxDestroyError = Forbidden | NotFound | PosthogOpError;
/** API for managing sandbox environments that control network access for task runs. */
export const sandboxDestroy: API.OperationMethod<
  SandboxDestroyRequest,
  SandboxDestroyResponse,
  SandboxDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SandboxDestroyRequest,
  output: SandboxDestroyResponse,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateSandboxPartialError = BadRequest | Forbidden | NotFound | PosthogOpError;
/** API for managing sandbox environments that control network access for task runs. */
export const updateSandboxPartial: API.OperationMethod<
  UpdateSandboxPartialRequest,
  SandboxEnvironmentDTO,
  UpdateSandboxPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateSandboxPartialRequest,
  output: SandboxEnvironmentDTO,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
