import * as API from "@distilled.cloud/core/api";
import * as C from "@distilled.cloud/core/category";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { PosthogProtocol, type PosthogOpError, type PosthogOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { PosthogOpError, PosthogOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export class Forbidden
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<Forbidden>()("Forbidden", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withAuthError),
    [{ status: 403 }],
  ) {}

export class NotFound
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<NotFound>()("NotFound", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 404 }],
  ) {}

/** * `DateTime` - DateTime * `String` - String * `Numeric` - Numeric * `Boolean` - Boolean * `Object` - Object */
export type SchemaPropertyTypeEnum = "DateTime" | "String" | "Numeric" | "Boolean" | "Object";
export const SchemaPropertyTypeEnum = S.String;

export interface SchemaPropertyGroupPropertyInput {
  name?: string;
  property_type?: SchemaPropertyTypeEnum | (string & {});
  is_required?: boolean;
  is_optional_in_types?: boolean;
  description?: string;
}
export const SchemaPropertyGroupPropertyInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String),
    property_type: S.optional(SchemaPropertyTypeEnum),
    is_required: S.optional(S.Boolean),
    is_optional_in_types: S.optional(S.Boolean),
    description: S.optional(S.String),
  }),
).annotate({
  identifier: "SchemaPropertyGroupPropertyInput",
}) as any as S.Schema<SchemaPropertyGroupPropertyInput>;

export type CreateSchemaPropertyGroupRequestPropertiesList =
  Array<SchemaPropertyGroupPropertyInput>;
export const CreateSchemaPropertyGroupRequestPropertiesList = /*@__PURE__*/ S.Array(
  SchemaPropertyGroupPropertyInput,
) as any as S.Schema<CreateSchemaPropertyGroupRequestPropertiesList>;

export interface CreateSchemaPropertyGroupRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  name?: string;
  description?: string;
  properties?: CreateSchemaPropertyGroupRequestPropertiesList;
}
export const CreateSchemaPropertyGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    description: S.optional(S.String),
    properties: S.optional(CreateSchemaPropertyGroupRequestPropertiesList),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/schema_property_groups/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateSchemaPropertyGroupRequest",
}) as any as S.Schema<CreateSchemaPropertyGroupRequest>;

export interface SchemaPropertyGroupProperty {
  id?: string;
  name?: string;
  property_type?: SchemaPropertyTypeEnum;
  is_required?: boolean;
  is_optional_in_types?: boolean;
  description?: string;
  created_at?: string;
  updated_at?: string;
}
export const SchemaPropertyGroupProperty = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    property_type: S.optional(SchemaPropertyTypeEnum),
    is_required: S.optional(S.Boolean),
    is_optional_in_types: S.optional(S.Boolean),
    description: S.optional(S.String),
    created_at: S.optional(S.String),
    updated_at: S.optional(S.String),
  }),
).annotate({
  identifier: "SchemaPropertyGroupProperty",
}) as any as S.Schema<SchemaPropertyGroupProperty>;

export type SchemaPropertyGroupPropertiesList = Array<SchemaPropertyGroupProperty>;
export const SchemaPropertyGroupPropertiesList = /*@__PURE__*/ S.Array(
  SchemaPropertyGroupProperty,
) as any as S.Schema<SchemaPropertyGroupPropertiesList>;

export interface EventDefinitionBasic {
  id?: string;
  name?: string;
}
export const EventDefinitionBasic = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
  }),
).annotate({ identifier: "EventDefinitionBasic" }) as any as S.Schema<EventDefinitionBasic>;

export type SchemaPropertyGroupEventsList = Array<EventDefinitionBasic>;
export const SchemaPropertyGroupEventsList = /*@__PURE__*/ S.Array(
  EventDefinitionBasic,
) as any as S.Schema<SchemaPropertyGroupEventsList>;

export type UserBasicHedgehogConfigMap = { [key: string]: unknown | undefined };
export const UserBasicHedgehogConfigMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Unknown,
) as any as S.Schema<UserBasicHedgehogConfigMap>;

/** * `engineering` - Engineering * `data` - Data * `product` - Product Management * `founder` - Founder * `leadership` - Leadership * `marketing` - Marketing * `sales` - Sales / Success * `student` - Student * `other` - Other */
export type RoleAtOrganizationEnum =
  | "engineering"
  | "data"
  | "product"
  | "founder"
  | "leadership"
  | "marketing"
  | "sales"
  | "student"
  | "other";
export const RoleAtOrganizationEnum = S.String;

export type BlankEnum = "";
export const BlankEnum = S.String;

export type UserBasicRoleAtOrganization = RoleAtOrganizationEnum | BlankEnum;
export const UserBasicRoleAtOrganization =
  S.Unknown as any as S.Schema<UserBasicRoleAtOrganization>;

export interface UserBasic {
  id?: number;
  uuid?: string;
  distinct_id?: string | null;
  first_name?: string;
  last_name?: string;
  email?: string;
  is_email_verified?: boolean | null;
  hedgehog_config?: UserBasicHedgehogConfigMap | null;
  role_at_organization?: UserBasicRoleAtOrganization | null;
}
export const UserBasic = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.Number),
    uuid: S.optional(S.String),
    distinct_id: S.optional(S.NullOr(S.String)),
    first_name: S.optional(S.String),
    last_name: S.optional(S.String),
    email: S.optional(S.String),
    is_email_verified: S.optional(S.NullOr(S.Boolean)),
    hedgehog_config: S.optional(S.NullOr(UserBasicHedgehogConfigMap)),
    role_at_organization: S.optional(S.NullOr(UserBasicRoleAtOrganization)),
  }),
).annotate({ identifier: "UserBasic" }) as any as S.Schema<UserBasic>;

export interface SchemaPropertyGroup {
  id?: string;
  name?: string;
  description?: string;
  properties?: SchemaPropertyGroupPropertiesList;
  events?: SchemaPropertyGroupEventsList;
  created_at?: string;
  updated_at?: string;
  created_by?: UserBasic | null;
}
export const SchemaPropertyGroup = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.optional(S.String),
    name: S.optional(S.String),
    description: S.optional(S.String),
    properties: S.optional(SchemaPropertyGroupPropertiesList),
    events: S.optional(SchemaPropertyGroupEventsList),
    created_at: S.optional(S.String),
    updated_at: S.optional(S.String),
    created_by: S.optional(S.NullOr(UserBasic)),
  }),
).annotate({ identifier: "SchemaPropertyGroup" }) as any as S.Schema<SchemaPropertyGroup>;

export interface GetSchemaPropertyGroupRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this schema property group. */
  id: string;
}
export const GetSchemaPropertyGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/schema_property_groups/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetSchemaPropertyGroupRequest",
}) as any as S.Schema<GetSchemaPropertyGroupRequest>;

export interface ListSchemaPropertyGroupsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListSchemaPropertyGroupsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/schema_property_groups/", code: 200 }),
  ),
).annotate({
  identifier: "ListSchemaPropertyGroupsRequest",
}) as any as S.Schema<ListSchemaPropertyGroupsRequest>;

export type PaginatedSchemaPropertyGroupListResultsList = Array<SchemaPropertyGroup>;
export const PaginatedSchemaPropertyGroupListResultsList = /*@__PURE__*/ S.Array(
  SchemaPropertyGroup,
) as any as S.Schema<PaginatedSchemaPropertyGroupListResultsList>;

export interface PaginatedSchemaPropertyGroupList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: PaginatedSchemaPropertyGroupListResultsList;
}
export const PaginatedSchemaPropertyGroupList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.optional(S.Number),
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: S.optional(PaginatedSchemaPropertyGroupListResultsList),
  }),
).annotate({
  identifier: "PaginatedSchemaPropertyGroupList",
}) as any as S.Schema<PaginatedSchemaPropertyGroupList>;

export interface SchemaPropertyGroupsDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this schema property group. */
  id: string;
}
export const SchemaPropertyGroupsDestroyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/api/projects/{project_id}/schema_property_groups/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SchemaPropertyGroupsDestroyRequest",
}) as any as S.Schema<SchemaPropertyGroupsDestroyRequest>;

export interface SchemaPropertyGroupsDestroyResponse {}
export const SchemaPropertyGroupsDestroyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "SchemaPropertyGroupsDestroyResponse",
}) as any as S.Schema<SchemaPropertyGroupsDestroyResponse>;

export type UpdateSchemaPropertyGroupRequestPropertiesList =
  Array<SchemaPropertyGroupPropertyInput>;
export const UpdateSchemaPropertyGroupRequestPropertiesList = /*@__PURE__*/ S.Array(
  SchemaPropertyGroupPropertyInput,
) as any as S.Schema<UpdateSchemaPropertyGroupRequestPropertiesList>;

export interface UpdateSchemaPropertyGroupRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this schema property group. */
  id: string;
  name?: string;
  description?: string;
  properties?: UpdateSchemaPropertyGroupRequestPropertiesList;
}
export const UpdateSchemaPropertyGroupRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    description: S.optional(S.String),
    properties: S.optional(UpdateSchemaPropertyGroupRequestPropertiesList),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/api/projects/{project_id}/schema_property_groups/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateSchemaPropertyGroupRequest",
}) as any as S.Schema<UpdateSchemaPropertyGroupRequest>;

export type UpdateSchemaPropertyGroupsPartialRequestPropertiesList =
  Array<SchemaPropertyGroupPropertyInput>;
export const UpdateSchemaPropertyGroupsPartialRequestPropertiesList = /*@__PURE__*/ S.Array(
  SchemaPropertyGroupPropertyInput,
) as any as S.Schema<UpdateSchemaPropertyGroupsPartialRequestPropertiesList>;

export interface UpdateSchemaPropertyGroupsPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** A UUID string identifying this schema property group. */
  id: string;
  name?: string;
  description?: string;
  properties?: UpdateSchemaPropertyGroupsPartialRequestPropertiesList;
}
export const UpdateSchemaPropertyGroupsPartialRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    name: S.optional(S.String),
    description: S.optional(S.String),
    properties: S.optional(UpdateSchemaPropertyGroupsPartialRequestPropertiesList),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/api/projects/{project_id}/schema_property_groups/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateSchemaPropertyGroupsPartialRequest",
}) as any as S.Schema<UpdateSchemaPropertyGroupsPartialRequest>;

export type CreateSchemaPropertyGroupError = BadRequest | Forbidden | NotFound | PosthogOpError;
export const createSchemaPropertyGroup: API.OperationMethod<
  CreateSchemaPropertyGroupRequest,
  SchemaPropertyGroup,
  CreateSchemaPropertyGroupError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSchemaPropertyGroupRequest,
  output: SchemaPropertyGroup,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetSchemaPropertyGroupError = Forbidden | NotFound | PosthogOpError;
export const getSchemaPropertyGroup: API.OperationMethod<
  GetSchemaPropertyGroupRequest,
  SchemaPropertyGroup,
  GetSchemaPropertyGroupError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSchemaPropertyGroupRequest,
  output: SchemaPropertyGroup,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListSchemaPropertyGroupsError = BadRequest | Forbidden | NotFound | PosthogOpError;
export const listSchemaPropertyGroups: API.OperationMethod<
  ListSchemaPropertyGroupsRequest,
  PaginatedSchemaPropertyGroupList,
  ListSchemaPropertyGroupsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListSchemaPropertyGroupsRequest,
  output: PaginatedSchemaPropertyGroupList,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type SchemaPropertyGroupsDestroyError = Forbidden | NotFound | PosthogOpError;
export const schemaPropertyGroupsDestroy: API.OperationMethod<
  SchemaPropertyGroupsDestroyRequest,
  SchemaPropertyGroupsDestroyResponse,
  SchemaPropertyGroupsDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SchemaPropertyGroupsDestroyRequest,
  output: SchemaPropertyGroupsDestroyResponse,
  errors: [Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateSchemaPropertyGroupError = BadRequest | Forbidden | NotFound | PosthogOpError;
export const updateSchemaPropertyGroup: API.OperationMethod<
  UpdateSchemaPropertyGroupRequest,
  SchemaPropertyGroup,
  UpdateSchemaPropertyGroupError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateSchemaPropertyGroupRequest,
  output: SchemaPropertyGroup,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateSchemaPropertyGroupsPartialError =
  | BadRequest
  | Forbidden
  | NotFound
  | PosthogOpError;
export const updateSchemaPropertyGroupsPartial: API.OperationMethod<
  UpdateSchemaPropertyGroupsPartialRequest,
  SchemaPropertyGroup,
  UpdateSchemaPropertyGroupsPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateSchemaPropertyGroupsPartialRequest,
  output: SchemaPropertyGroup,
  errors: [BadRequest, Forbidden, NotFound],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
