import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (see scripts/convert.ts). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { PosthogProtocol, type PosthogOpError, type PosthogOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { PosthogOpError, PosthogOpContext };

/** * `all` - all * `label` - label */
export type ReviewModeEnum = "all" | "label";
export const ReviewModeEnum = S.String;

export interface CreateStamphogRepoConfigRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** SCM provider this config talks to. Defaults to 'github'. */
  provider?: string;
  /** Repository full name, e.g. 'PostHog/posthog'. */
  repository: string;
  /** Whether stamphog actively reviews pull requests for this repo. */
  enabled?: boolean;
  /** Whether merged PRs on this repo are captured for the daily Slack digest. */
  digest_enabled?: boolean;
  /** When reviews run: 'all' reviews every pull request (the default); 'label' reviews only pull requests carrying the trigger label, mirroring the Action's opt-in flow. * `all` - all * `label` - label */
  review_mode?: ReviewModeEnum | (string & {});
  /** Pull request label that triggers a review when review_mode is 'label'. Defaults to 'stamphog'. */
  trigger_label?: string;
}
export const CreateStamphogRepoConfigRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    provider: S.optional(S.String),
    repository: S.String,
    enabled: S.optional(S.Boolean),
    digest_enabled: S.optional(S.Boolean),
    review_mode: S.optional(ReviewModeEnum),
    trigger_label: S.optional(S.String),
  }).pipe(
    T.Http({ method: "POST", uri: "/api/projects/{project_id}/stamphog/repo_configs/", code: 200 }),
  ),
).annotate({
  identifier: "CreateStamphogRepoConfigRequest",
}) as any as S.Schema<CreateStamphogRepoConfigRequest>;

export interface StamphogRepoConfig {
  id: string;
  /** SCM provider this config talks to. Defaults to 'github'. */
  provider?: string;
  /** Repository full name, e.g. 'PostHog/posthog'. */
  repository: string;
  /** Whether stamphog actively reviews pull requests for this repo. */
  enabled: boolean;
  /** Provider app installation ID that authorizes API calls for this repo. Set only by the verified sync_installation flow; ignored on direct writes. */
  installation_id: string;
  /** Whether merged PRs on this repo are captured for the daily Slack digest. Requires 'enabled', since the digest reports what stamphog approved. */
  digest_enabled?: boolean;
  /** When reviews run: 'all' reviews every pull request (the default); 'label' reviews only pull requests carrying the trigger label, mirroring the Action's opt-in flow. * `all` - all * `label` - label */
  review_mode: ReviewModeEnum;
  /** Pull request label that triggers a review when review_mode is 'label'. Defaults to 'stamphog'. */
  trigger_label?: string;
  /** The caller's access level on the stamphog resource, resolved for the team that owns this row. 'editor' can turn reviews on. 'manager' is required to turn them off or to change review_mode or trigger_label. */
  user_access_level: string | null;
  created_at: string;
  updated_at: string;
}
export const StamphogRepoConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    provider: S.optional(S.String),
    repository: S.String,
    enabled: S.Boolean,
    installation_id: S.String,
    digest_enabled: S.optional(S.Boolean),
    review_mode: ReviewModeEnum,
    trigger_label: S.optional(S.String),
    user_access_level: S.NullOr(S.String),
    created_at: S.String,
    updated_at: S.String,
  }),
).annotate({ identifier: "StamphogRepoConfig" }) as any as S.Schema<StamphogRepoConfig>;

export interface CreateStamphogRepoConfigsSyncInstallationRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** GitHub App installation ID from the fresh-install Setup URL redirect. Optional: absent or blank means discover the caller's installations from the OAuth code instead (authorize-first flow). The id is not trusted on its own — ownership is always proven via the code. */
  installation_id?: string;
  /** GitHub user-to-server OAuth code from the post-install redirect (present when the App has 'Request user authorization during installation' enabled). Exchanged server-side to prove the caller owns the installation before its repos are bound. */
  code: string;
  /** Signed state token minted by install_info and round-tripped through GitHub's install redirect. Binds the callback to the team and user that started the flow, so a stolen installation_id + code can't be replayed against another team's session. */
  state: string;
}
export const CreateStamphogRepoConfigsSyncInstallationRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    installation_id: S.optional(S.String),
    code: S.String,
    state: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/sync_installation/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateStamphogRepoConfigsSyncInstallationRequest",
}) as any as S.Schema<CreateStamphogRepoConfigsSyncInstallationRequest>;

/** Repo configs this team already had for the installation's repositories, now bound to it. A sync creates no repo config: use add_repository to turn reviews on for a repository. */
export type StamphogSyncInstallationResponseSyncedList = Array<StamphogRepoConfig>;
export const StamphogSyncInstallationResponseSyncedList = /*@__PURE__*/ S.Array(
  StamphogRepoConfig,
) as any as S.Schema<StamphogSyncInstallationResponseSyncedList>;

/** Repository full names skipped because another team already owns them under this installation. */
export type StamphogSyncInstallationResponseSkippedList = Array<string>;
export const StamphogSyncInstallationResponseSkippedList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StamphogSyncInstallationResponseSkippedList>;

/** One installation of the App the authorizing user can reach, offered for an explicit pick. */
export interface StamphogDiscoveredInstallation {
  /** GitHub installation id, as a string. */
  id: string;
  /** Login of the org or user account the installation lives on. */
  account_login: string;
}
export const StamphogDiscoveredInstallation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    account_login: S.String,
  }),
).annotate({
  identifier: "StamphogDiscoveredInstallation",
}) as any as S.Schema<StamphogDiscoveredInstallation>;

/** Populated only on the discovery path when the caller can reach MORE than one installation of this App: nothing was bound, and the user must pick which installation to connect. The frontend re-runs the authorize flow and calls back with the chosen installation_id, which the explicit path verifies. Empty whenever a bind happened (or nothing was found). */
export type StamphogSyncInstallationResponseInstallationsList =
  Array<StamphogDiscoveredInstallation>;
export const StamphogSyncInstallationResponseInstallationsList = /*@__PURE__*/ S.Array(
  StamphogDiscoveredInstallation,
) as any as S.Schema<StamphogSyncInstallationResponseInstallationsList>;

/** Result of syncing an installation: the team's rows bound to it, and what the team can add now. */
export interface StamphogSyncInstallationResponse {
  /** Repo configs this team already had for the installation's repositories, now bound to it. A sync creates no repo config: use add_repository to turn reviews on for a repository. */
  synced: StamphogSyncInstallationResponseSyncedList;
  /** Repository full names skipped because another team already owns them under this installation. */
  skipped: StamphogSyncInstallationResponseSkippedList;
  /** How many repositories this team can add after the sync, across all its connected installations. List them with available_repositories. */
  available_count: number;
  /** True only on the discovery path (no installation_id) when the caller can reach no installation of this App — it isn't installed anywhere they can see. The frontend should route the user to the GitHub install page (install_url). Always false on the explicit installation_id path. */
  app_not_installed: boolean;
  /** Populated only on the discovery path when the caller can reach MORE than one installation of this App: nothing was bound, and the user must pick which installation to connect. The frontend re-runs the authorize flow and calls back with the chosen installation_id, which the explicit path verifies. Empty whenever a bind happened (or nothing was found). */
  installations: StamphogSyncInstallationResponseInstallationsList;
}
export const StamphogSyncInstallationResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    synced: StamphogSyncInstallationResponseSyncedList,
    skipped: StamphogSyncInstallationResponseSkippedList,
    available_count: S.Number,
    app_not_installed: S.Boolean,
    installations: StamphogSyncInstallationResponseInstallationsList,
  }),
).annotate({
  identifier: "StamphogSyncInstallationResponse",
}) as any as S.Schema<StamphogSyncInstallationResponse>;

export interface CreateStamphogReviewRunRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Full name of the GitHub repository, e.g. 'PostHog/posthog'. It must be connected and enabled in Stamphog. */
  repository: string;
  /** Pull request number on GitHub. */
  pr_number: number;
}
export const CreateStamphogReviewRunRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repository: S.String,
    pr_number: S.Number,
  }).pipe(
    T.Http({ method: "POST", uri: "/api/projects/{project_id}/stamphog/review_runs/", code: 200 }),
  ),
).annotate({
  identifier: "CreateStamphogReviewRunRequest",
}) as any as S.Schema<CreateStamphogReviewRunRequest>;

/** * `self_driving` - SELF_DRIVING * `manual` - MANUAL * `label` - LABEL * `all` - ALL */
export type ReviewRunTriggerEnum = "self_driving" | "manual" | "label" | "all";
export const ReviewRunTriggerEnum = S.String;

/** * `queued` - QUEUED * `gated` - GATED * `reviewing` - REVIEWING * `completed` - COMPLETED * `failed` - FAILED * `superseded` - SUPERSEDED */
export type ReviewRunStatusEnum =
  | "queued"
  | "gated"
  | "reviewing"
  | "completed"
  | "failed"
  | "superseded";
export const ReviewRunStatusEnum = S.String;

/** * `none` - NONE * `approved` - APPROVED * `refused` - REFUSED * `escalate` - ESCALATE * `wait` - WAIT * `error` - ERROR */
export type ReviewRunVerdictEnum = "none" | "approved" | "refused" | "escalate" | "wait" | "error";
export const ReviewRunVerdictEnum = S.String;

/** Allowlisted, content-free slice of ``ReviewRun.gate_result``. The raw gate blob nests ``gates``, ``classification``, and ``policy`` sub-objects that carry repository content — changed-file paths (``safe_migration_files``, ``invalid_folder_files``), manifest gate messages, and declared ``policy.scopes`` — which a project member without repo access must not read. Only the terminal decision is exposed. */
export interface GateResultSummary {
  /** Whether the deterministic gates blocked auto-review before the reviewer ran. */
  gate_blocked: boolean;
  /** The engine's raw final-verdict token, if the run reached a verdict. */
  final_verdict: string;
}
export const GateResultSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    gate_blocked: S.Boolean,
    final_verdict: S.String,
  }),
).annotate({ identifier: "GateResultSummary" }) as any as S.Schema<GateResultSummary>;

/** Allowlisted, non-sensitive slice of ``ReviewRun.output``. The raw ``output`` blob also holds the reviewer's stdout, the full PR payload, changed-file patches, and default-branch policy file contents, none of which the API returns. The reviewer's reasoning, the text stamphog posts on GitHub, is parsed out of the stdout and returned as ``reasoning``. */
export interface ReviewOutputSummary {
  /** Version of the stamphog engine that produced this review, if it reported one. */
  stamphog_version: string;
  /** Exit code of the reviewer process in the sandbox, if the run reached the sandbox stage. */
  reviewer_exit_code: number;
}
export const ReviewOutputSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    stamphog_version: S.String,
    reviewer_exit_code: S.Number,
  }),
).annotate({ identifier: "ReviewOutputSummary" }) as any as S.Schema<ReviewOutputSummary>;

/** Issues the reviewer found that block approval. */
export type ReviewReasoningShowstoppersList = Array<string>;
export const ReviewReasoningShowstoppersList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ReviewReasoningShowstoppersList>;

/** The reviewer's reasoning for one run, the same text stamphog posts as its GitHub review. */
export interface ReviewReasoning {
  /** The reviewer's explanation of its verdict. */
  reasoning: string | null;
  /** Issues the reviewer found that block approval. */
  showstoppers: ReviewReasoningShowstoppersList | null;
  /** The review text stamphog posts on GitHub: the reasoning, the judgment points, and the gate outcome. */
  review_body: string | null;
  /** A plain-language summary of what the change does. */
  change_summary: string | null;
}
export const ReviewReasoning = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    reasoning: S.NullOr(S.String),
    showstoppers: S.NullOr(ReviewReasoningShowstoppersList),
    review_body: S.NullOr(S.String),
    change_summary: S.NullOr(S.String),
  }),
).annotate({ identifier: "ReviewReasoning" }) as any as S.Schema<ReviewReasoning>;

export interface ReviewRun {
  id: string;
  /** ID of the pull request this review run belongs to. */
  pull_request: string;
  /** Full name of the repository this review run belongs to. */
  repository: string;
  /** Pull request number on GitHub. */
  pr_number: number;
  /** Full URL to the pull request on GitHub. */
  pr_url: string;
  /** Pull request title as of the last webhook delivery applied. */
  title: string;
  /** GitHub login of the pull request author. */
  author_login: string;
  /** Commit SHA of the PR head at the time this run started. */
  head_sha: string;
  /** Branch name of the PR head. */
  head_branch: string;
  /** GitHub webhook delivery ID that triggered this run, used for deduplication. */
  delivery_id: string | null;
  /** What caused this run to exist: self-driving inbox provenance, a manual request through the API, the repo's trigger label, or the repo reviewing every PR event. * `self_driving` - SELF_DRIVING * `manual` - MANUAL * `label` - LABEL * `all` - ALL */
  trigger: ReviewRunTriggerEnum;
  /** Current stage of the review run's lifecycle. * `queued` - QUEUED * `gated` - GATED * `reviewing` - REVIEWING * `completed` - COMPLETED * `failed` - FAILED * `superseded` - SUPERSEDED */
  status: ReviewRunStatusEnum;
  /** Final verdict reached by the reviewer, if any. * `none` - NONE * `approved` - APPROVED * `refused` - REFUSED * `escalate` - ESCALATE * `wait` - WAIT * `error` - ERROR */
  verdict: ReviewRunVerdictEnum;
  /** Allowlisted deterministic gate outcome (gate_blocked, final_verdict). The nested gate, classification, and policy sub-objects are excluded — they carry changed-file paths and policy scopes, repository content a project member without repo access must not read. */
  gate_result: GateResultSummary;
  /** Allowlisted subset of the reviewer output blob (stamphog version, reviewer exit code). The raw reviewer stdout, PR payload, changed-file patches, and policy file contents are excluded. The reviewer's reasoning, the text stamphog posts on GitHub, is in `reasoning` instead. */
  output: ReviewOutputSummary;
  /** The reviewer's reasoning, the same text stamphog posts as its GitHub review. Returned only when retrieving a single run, and null in list results. Its fields are null until the reviewer has run. */
  reasoning: ReviewReasoning | null;
  /** Error message if the run failed, blank otherwise. */
  error: string;
  /** ID of the GitHub review this run posted, null if it never posted one. */
  posted_review_id: number | null;
  /** When this run's verdict reached GitHub, null if it never did. */
  verdict_posted_at: string | null;
  /** When this run's GitHub approval was retracted because the head moved, null if it wasn't. */
  approval_dismissed_at: string | null;
  /** When the review run was created. */
  created_at: string;
  /** When the review run was last updated. */
  updated_at: string;
  /** When the review run reached a terminal state, if it has. */
  completed_at: string | null;
}
export const ReviewRun = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    pull_request: S.String,
    repository: S.String,
    pr_number: S.Number,
    pr_url: S.String,
    title: S.String,
    author_login: S.String,
    head_sha: S.String,
    head_branch: S.String,
    delivery_id: S.NullOr(S.String),
    trigger: ReviewRunTriggerEnum,
    status: ReviewRunStatusEnum,
    verdict: ReviewRunVerdictEnum,
    gate_result: GateResultSummary,
    output: ReviewOutputSummary,
    reasoning: S.NullOr(ReviewReasoning),
    error: S.String,
    posted_review_id: S.NullOr(S.Number),
    verdict_posted_at: S.NullOr(S.String),
    approval_dismissed_at: S.NullOr(S.String),
    created_at: S.String,
    updated_at: S.String,
    completed_at: S.NullOr(S.String),
  }),
).annotate({ identifier: "ReviewRun" }) as any as S.Schema<ReviewRun>;

/** The review run a request points at. */
export interface ReviewRequestResponse {
  /** The review run for the pull request's current head. Poll it by id until status is terminal (completed, gated, failed, or superseded). */
  run: ReviewRun;
  /** True when this request queued a new run. False when a queued, running, or finished run already covered the current head, which is returned instead. */
  created: boolean;
}
export const ReviewRequestResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    run: ReviewRun,
    created: S.Boolean,
  }),
).annotate({ identifier: "ReviewRequestResponse" }) as any as S.Schema<ReviewRequestResponse>;

export interface GetStamphogDigestRunRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetStamphogDigestRunRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/stamphog/digest_runs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStamphogDigestRunRequest",
}) as any as S.Schema<GetStamphogDigestRunRequest>;

/** * `manual` - MANUAL * `slack_name_match` - SLACK_NAME_MATCH * `stamphog_config` - STAMPHOG_CONFIG * `owners_contact` - OWNERS_CONTACT */
export type ResolutionSourceEnum =
  | "manual"
  | "slack_name_match"
  | "stamphog_config"
  | "owners_contact";
export const ResolutionSourceEnum = S.String;

/** * `pending` - PENDING * `completed` - COMPLETED * `failed` - FAILED */
export type DigestRunStatusEnum = "pending" | "completed" | "failed";
export const DigestRunStatusEnum = S.String;

/** One merged pull request as the digest listed it. */
export interface DigestSummaryPR {
  /** Pull request number on GitHub. */
  pr_number: number;
  /** Pull request title. */
  title: string;
  /** Full URL to the pull request on GitHub. */
  url: string;
  /** GitHub login of the pull request author. */
  author_login: string;
  /** The one-line summary of the change that the digest posted. */
  summary: string;
  /** Repository full name, e.g. 'PostHog/posthog'. Blank on older runs. */
  repository: string;
}
export const DigestSummaryPR = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    pr_number: S.Number,
    title: S.String,
    url: S.String,
    author_login: S.String,
    summary: S.String,
    repository: S.String,
  }),
).annotate({ identifier: "DigestSummaryPR" }) as any as S.Schema<DigestSummaryPR>;

/** The merged pull requests the digest listed, in the order it listed them. */
export type DigestSummaryPrsList = Array<DigestSummaryPR>;
export const DigestSummaryPrsList = /*@__PURE__*/ S.Array(
  DigestSummaryPR,
) as any as S.Schema<DigestSummaryPrsList>;

/** What the digest posted to Slack: the headline and the pull requests it listed. */
export interface DigestSummary {
  /** Prose about the merges with real consequence. Blank when the digest led with its first line. */
  headline: string;
  /** The merged pull requests the digest listed, in the order it listed them. */
  prs: DigestSummaryPrsList;
}
export const DigestSummary = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    headline: S.String,
    prs: DigestSummaryPrsList,
  }),
).annotate({ identifier: "DigestSummary" }) as any as S.Schema<DigestSummary>;

export interface DigestRun {
  id: string;
  /** Digest bucket this run drained, e.g. a team slug or 'repo:PostHog/posthog'. */
  audience_key: string;
  /** Slack channel this digest was posted to, e.g. 'C012AB3CD'. */
  slack_channel_id: string;
  /** Human-readable name of that channel, for display. */
  slack_channel_name: string;
  /** Why the digest went to this channel: 'slack_name_match' (no declaration anywhere, so the audience_key matched a same-named Slack channel), 'stamphog_config' (the channel the repo declared under 'digest:' in .stamphog/policy.yml), 'owners_contact' (a teams: entry in a root owners.yaml named it), or 'manual' (no longer produced). * `manual` - MANUAL * `slack_name_match` - SLACK_NAME_MATCH * `stamphog_config` - STAMPHOG_CONFIG * `owners_contact` - OWNERS_CONTACT */
  resolution_source: ResolutionSourceEnum;
  /** Current state of the digest run (pending, completed, failed). * `pending` - PENDING * `completed` - COMPLETED * `failed` - FAILED */
  status: DigestRunStatusEnum;
  /** Number of merged PRs included in the posted digest. */
  pr_count: number;
  /** What the digest posted: its headline and the merged pull requests it listed. Both are empty on a run with nothing to post, and on runs stored before this format. */
  summary: DigestSummary;
  /** Slack message timestamp of the posted digest, if posted. */
  slack_message_ts: string;
  /** Error message if the run failed, blank otherwise. */
  error: string;
  /** When the digest run was created. */
  created_at: string;
  /** When the digest was posted to Slack, if it was. */
  posted_at: string | null;
}
export const DigestRun = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    audience_key: S.String,
    slack_channel_id: S.String,
    slack_channel_name: S.String,
    resolution_source: ResolutionSourceEnum,
    status: DigestRunStatusEnum,
    pr_count: S.Number,
    summary: DigestSummary,
    slack_message_ts: S.String,
    error: S.String,
    created_at: S.String,
    posted_at: S.NullOr(S.String),
  }),
).annotate({ identifier: "DigestRun" }) as any as S.Schema<DigestRun>;

export interface GetStamphogPullRequestRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetStamphogPullRequestRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/stamphog/pull_requests/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStamphogPullRequestRequest",
}) as any as S.Schema<GetStamphogPullRequestRequest>;

export interface StamphogPullRequest {
  id: string;
  /** Full name of the repository this pull request belongs to. */
  repository: string;
  /** Pull request number on GitHub. */
  pr_number: number;
  /** Pull request title, refreshed on every relevant webhook delivery. */
  title: string;
  /** GitHub login of the pull request author. */
  author_login: string;
  /** Full URL to the pull request on GitHub. */
  pr_url: string;
  /** Branch name of the PR head. */
  head_branch: string;
  /** Whether this pull request has merged (merged_at is set). */
  merged: boolean;
  /** When the pull request merged, null if it hasn't. */
  merged_at: string | null;
  /** Merge commit SHA, blank until the pull request merges. */
  merge_commit_sha: string;
  /** Lines added, recorded when the pull request merges. */
  additions: number;
  /** Lines deleted, recorded when the pull request merges. */
  deletions: number;
  /** Files changed, recorded when the pull request merges. */
  changed_files: number;
  /** When this pull request was first captured. */
  created_at: string;
  /** When this pull request was last updated. */
  updated_at: string;
}
export const StamphogPullRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    repository: S.String,
    pr_number: S.Number,
    title: S.String,
    author_login: S.String,
    pr_url: S.String,
    head_branch: S.String,
    merged: S.Boolean,
    merged_at: S.NullOr(S.String),
    merge_commit_sha: S.String,
    additions: S.Number,
    deletions: S.Number,
    changed_files: S.Number,
    created_at: S.String,
    updated_at: S.String,
  }),
).annotate({ identifier: "StamphogPullRequest" }) as any as S.Schema<StamphogPullRequest>;

export interface GetStamphogRepoConfigRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetStamphogRepoConfigRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStamphogRepoConfigRequest",
}) as any as S.Schema<GetStamphogRepoConfigRequest>;

export interface GetStamphogRepoConfigsAvailableRepositoryRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Maximum number of repositories to return. Defaults to 50, at most 200. */
  limit?: number;
  /** Case-insensitive substring to match against the repository full name, e.g. 'posthog'. */
  search?: string;
}
export const GetStamphogRepoConfigsAvailableRepositoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    search: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/available_repositories/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStamphogRepoConfigsAvailableRepositoryRequest",
}) as any as S.Schema<GetStamphogRepoConfigsAvailableRepositoryRequest>;

/** Repository full names the team can add, sorted by name and capped by limit. Only repositories a project member proved access to on GitHub are listed, and never one another project already holds under the same installation. */
export type StamphogAvailableRepositoriesRepositoriesList = Array<string>;
export const StamphogAvailableRepositoriesRepositoriesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StamphogAvailableRepositoriesRepositoriesList>;

/** Repositories from the team's connected GitHub installations that are not added to stamphog yet. */
export interface StamphogAvailableRepositories {
  /** Repository full names the team can add, sorted by name and capped by limit. Only repositories a project member proved access to on GitHub are listed, and never one another project already holds under the same installation. */
  repositories: StamphogAvailableRepositoriesRepositoriesList;
  /** How many repositories match the search in total, before limit applies. */
  total_count: number;
  /** Whether a project member connected a GitHub installation yet. False means GitHub must be connected before any repository can be added. True with a total_count of 0 and no search means no repository is left to add. */
  has_installation: boolean;
}
export const StamphogAvailableRepositories = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    repositories: StamphogAvailableRepositoriesRepositoriesList,
    total_count: S.Number,
    has_installation: S.Boolean,
  }),
).annotate({
  identifier: "StamphogAvailableRepositories",
}) as any as S.Schema<StamphogAvailableRepositories>;

export interface GetStamphogReviewRunRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const GetStamphogReviewRunRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/stamphog/review_runs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetStamphogReviewRunRequest",
}) as any as S.Schema<GetStamphogReviewRunRequest>;

export interface ListStamphogDigestRunsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by the Slack channel the digest was posted to, e.g. 'C012AB3CD'. */
  slack_channel_id?: string;
}
export const ListStamphogDigestRunsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    slack_channel_id: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/stamphog/digest_runs/", code: 200 }),
  ),
).annotate({
  identifier: "ListStamphogDigestRunsRequest",
}) as any as S.Schema<ListStamphogDigestRunsRequest>;

export type PaginatedDigestRunListResultsList = Array<DigestRun>;
export const PaginatedDigestRunListResultsList = /*@__PURE__*/ S.Array(
  DigestRun,
) as any as S.Schema<PaginatedDigestRunListResultsList>;

export interface PaginatedDigestRunList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedDigestRunListResultsList;
}
export const PaginatedDigestRunList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: PaginatedDigestRunListResultsList,
  }),
).annotate({ identifier: "PaginatedDigestRunList" }) as any as S.Schema<PaginatedDigestRunList>;

export interface ListStamphogPullRequestsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** Filter by merge state: true for merged pull requests, false for unmerged. */
  merged?: boolean;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by pull request number. */
  pr_number?: number;
}
export const ListStamphogPullRequestsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    merged: S.optional(S.Boolean.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    pr_number: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/stamphog/pull_requests/", code: 200 }),
  ),
).annotate({
  identifier: "ListStamphogPullRequestsRequest",
}) as any as S.Schema<ListStamphogPullRequestsRequest>;

export type PaginatedStamphogPullRequestListResultsList = Array<StamphogPullRequest>;
export const PaginatedStamphogPullRequestListResultsList = /*@__PURE__*/ S.Array(
  StamphogPullRequest,
) as any as S.Schema<PaginatedStamphogPullRequestListResultsList>;

export interface PaginatedStamphogPullRequestList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedStamphogPullRequestListResultsList;
}
export const PaginatedStamphogPullRequestList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: PaginatedStamphogPullRequestListResultsList,
  }),
).annotate({
  identifier: "PaginatedStamphogPullRequestList",
}) as any as S.Schema<PaginatedStamphogPullRequestList>;

export interface ListStamphogRepoConfigsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
}
export const ListStamphogRepoConfigsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/stamphog/repo_configs/", code: 200 }),
  ),
).annotate({
  identifier: "ListStamphogRepoConfigsRequest",
}) as any as S.Schema<ListStamphogRepoConfigsRequest>;

export type PaginatedStamphogRepoConfigListResultsList = Array<StamphogRepoConfig>;
export const PaginatedStamphogRepoConfigListResultsList = /*@__PURE__*/ S.Array(
  StamphogRepoConfig,
) as any as S.Schema<PaginatedStamphogRepoConfigListResultsList>;

export interface PaginatedStamphogRepoConfigList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedStamphogRepoConfigListResultsList;
}
export const PaginatedStamphogRepoConfigList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: PaginatedStamphogRepoConfigListResultsList,
  }),
).annotate({
  identifier: "PaginatedStamphogRepoConfigList",
}) as any as S.Schema<PaginatedStamphogRepoConfigList>;

export type ListStamphogReviewRunsRequestTrigger = "all" | "label" | "manual" | "self_driving";
export const ListStamphogReviewRunsRequestTrigger = S.String;

export interface ListStamphogReviewRunsRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Number of results to return per page. */
  limit?: number;
  /** The initial index from which to return the results. */
  offset?: number;
  /** Filter by pull request number. */
  pr_number?: number;
  /** Filter by repository full name, e.g. 'PostHog/posthog'. */
  repository?: string;
  /** Filter by review run status. */
  status?: string;
  /** Filter by what caused the run. Leave it unset to include runs from every trigger. 'all' is not a wildcard: it matches only runs in repos that review every pull request event. The other values: 'label' (the repo's trigger label opted the PR in), 'manual' (someone requested the review through the API or MCP), and 'self_driving' (stamphog reviewed a bot-authored PR from the inbox). */
  trigger?: ListStamphogReviewRunsRequestTrigger | (string & {});
}
export const ListStamphogReviewRunsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
    offset: S.optional(S.Number.pipe(T.Query())),
    pr_number: S.optional(S.Number.pipe(T.Query())),
    repository: S.optional(S.String.pipe(T.Query())),
    status: S.optional(S.String.pipe(T.Query())),
    trigger: S.optional(ListStamphogReviewRunsRequestTrigger.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/api/projects/{project_id}/stamphog/review_runs/", code: 200 }),
  ),
).annotate({
  identifier: "ListStamphogReviewRunsRequest",
}) as any as S.Schema<ListStamphogReviewRunsRequest>;

export type PaginatedReviewRunListResultsList = Array<ReviewRun>;
export const PaginatedReviewRunListResultsList = /*@__PURE__*/ S.Array(
  ReviewRun,
) as any as S.Schema<PaginatedReviewRunListResultsList>;

export interface PaginatedReviewRunList {
  count: number;
  next?: string | null;
  previous?: string | null;
  results: PaginatedReviewRunListResultsList;
}
export const PaginatedReviewRunList = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    count: S.Number,
    next: S.optional(S.NullOr(S.String)),
    previous: S.optional(S.NullOr(S.String)),
    results: PaginatedReviewRunListResultsList,
  }),
).annotate({ identifier: "PaginatedReviewRunList" }) as any as S.Schema<PaginatedReviewRunList>;

export interface StamphogRepoConfigsAddRepositoryCreateRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  /** Repository full name, e.g. 'PostHog/posthog'. It must be in one of the project's connected GitHub installations, as available_repositories lists them. A repository the project already has is turned back on. */
  repository: string;
}
export const StamphogRepoConfigsAddRepositoryCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    repository: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/add_repository/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "StamphogRepoConfigsAddRepositoryCreateRequest",
}) as any as S.Schema<StamphogRepoConfigsAddRepositoryCreateRequest>;

export interface StamphogRepoConfigsDestroyRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
}
export const StamphogRepoConfigsDestroyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "StamphogRepoConfigsDestroyRequest",
}) as any as S.Schema<StamphogRepoConfigsDestroyRequest>;

export interface StamphogRepoConfigsDestroyResponse {}
export const StamphogRepoConfigsDestroyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "StamphogRepoConfigsDestroyResponse",
}) as any as S.Schema<StamphogRepoConfigsDestroyResponse>;

export interface StamphogRepoConfigsInstallInfoRetrieveRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
}
export const StamphogRepoConfigsInstallInfoRetrieveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/install_info/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "StamphogRepoConfigsInstallInfoRetrieveRequest",
}) as any as S.Schema<StamphogRepoConfigsInstallInfoRetrieveRequest>;

/** Static info the frontend needs to render the 'Connect a repository' button. */
export interface StamphogInstallInfo {
  /** URL-friendly slug of the dedicated Stamphog GitHub App, or blank if unconfigured. */
  app_slug: string;
  /** GitHub install URL (github.com/apps/<slug>/installations/new) the 'Connect' button opens. The user picks a GitHub account there and chooses which repositories the App can reach, including an account where the App is already installed. Blank if the App slug is unconfigured. */
  install_url: string;
  /** GitHub authorize URL (github.com/login/oauth/authorize). GitHub's redirect after configuring an existing installation carries no OAuth code, so the client passes through this URL once: an installed App redirects straight back with a code, which sync_installation uses to prove ownership. Blank if the App client id is unconfigured. */
  authorize_url: string;
}
export const StamphogInstallInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    app_slug: S.String,
    install_url: S.String,
    authorize_url: S.String,
  }),
).annotate({ identifier: "StamphogInstallInfo" }) as any as S.Schema<StamphogInstallInfo>;

export interface UpdateStamphogRepoConfigRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** SCM provider this config talks to. Defaults to 'github'. */
  provider?: string;
  /** Repository full name, e.g. 'PostHog/posthog'. */
  repository: string;
  /** Whether stamphog actively reviews pull requests for this repo. */
  enabled?: boolean;
  /** Whether merged PRs on this repo are captured for the daily Slack digest. */
  digest_enabled?: boolean;
  /** When reviews run: 'all' reviews every pull request (the default); 'label' reviews only pull requests carrying the trigger label, mirroring the Action's opt-in flow. * `all` - all * `label` - label */
  review_mode?: ReviewModeEnum | (string & {});
  /** Pull request label that triggers a review when review_mode is 'label'. Defaults to 'stamphog'. */
  trigger_label?: string;
}
export const UpdateStamphogRepoConfigRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    provider: S.optional(S.String),
    repository: S.String,
    enabled: S.optional(S.Boolean),
    digest_enabled: S.optional(S.Boolean),
    review_mode: S.optional(ReviewModeEnum),
    trigger_label: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateStamphogRepoConfigRequest",
}) as any as S.Schema<UpdateStamphogRepoConfigRequest>;

export interface UpdateStamphogRepoConfigsPartialRequest {
  /** Project ID of the project you're trying to access. To find the ID of the project, make a call to /api/projects/. */
  project_id: string;
  id: string;
  /** SCM provider this config talks to. Defaults to 'github'. */
  provider?: string;
  /** Repository full name, e.g. 'PostHog/posthog'. */
  repository?: string;
  /** Whether stamphog actively reviews pull requests for this repo. */
  enabled?: boolean;
  /** Whether merged PRs on this repo are captured for the daily Slack digest. */
  digest_enabled?: boolean;
  /** When reviews run: 'all' reviews every pull request (the default); 'label' reviews only pull requests carrying the trigger label, mirroring the Action's opt-in flow. * `all` - all * `label` - label */
  review_mode?: ReviewModeEnum | (string & {});
  /** Pull request label that triggers a review when review_mode is 'label'. Defaults to 'stamphog'. */
  trigger_label?: string;
}
export const UpdateStamphogRepoConfigsPartialRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    project_id: S.String.pipe(T.Label()),
    id: S.String.pipe(T.Label()),
    provider: S.optional(S.String),
    repository: S.optional(S.String),
    enabled: S.optional(S.Boolean),
    digest_enabled: S.optional(S.Boolean),
    review_mode: S.optional(ReviewModeEnum),
    trigger_label: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "PATCH",
      uri: "/api/projects/{project_id}/stamphog/repo_configs/{id}/",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateStamphogRepoConfigsPartialRequest",
}) as any as S.Schema<UpdateStamphogRepoConfigsPartialRequest>;

export type CreateStamphogRepoConfigError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const createStamphogRepoConfig: API.OperationMethod<
  CreateStamphogRepoConfigRequest,
  StamphogRepoConfig,
  CreateStamphogRepoConfigError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStamphogRepoConfigRequest,
  output: StamphogRepoConfig,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateStamphogRepoConfigsSyncInstallationError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const createStamphogRepoConfigsSyncInstallation: API.OperationMethod<
  CreateStamphogRepoConfigsSyncInstallationRequest,
  StamphogSyncInstallationResponse,
  CreateStamphogRepoConfigsSyncInstallationError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStamphogRepoConfigsSyncInstallationRequest,
  output: StamphogSyncInstallationResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type CreateStamphogReviewRunError = PosthogOpError;
/** History of stamphog review runs, filterable by repository, PR number, and status, plus manual review requests. */
export const createStamphogReviewRun: API.OperationMethod<
  CreateStamphogReviewRunRequest,
  ReviewRequestResponse,
  CreateStamphogReviewRunError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateStamphogReviewRunRequest,
  output: ReviewRequestResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetStamphogDigestRunError = PosthogOpError;
/** Read-only history of posted (or attempted) digests, filterable by Slack channel. */
export const getStamphogDigestRun: API.OperationMethod<
  GetStamphogDigestRunRequest,
  DigestRun,
  GetStamphogDigestRunError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStamphogDigestRunRequest,
  output: DigestRun,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetStamphogPullRequestError = PosthogOpError;
/** Read-only pull requests stamphog knows about, filterable by PR number and merge state. */
export const getStamphogPullRequest: API.OperationMethod<
  GetStamphogPullRequestRequest,
  StamphogPullRequest,
  GetStamphogPullRequestError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStamphogPullRequestRequest,
  output: StamphogPullRequest,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetStamphogRepoConfigError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const getStamphogRepoConfig: API.OperationMethod<
  GetStamphogRepoConfigRequest,
  StamphogRepoConfig,
  GetStamphogRepoConfigError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStamphogRepoConfigRequest,
  output: StamphogRepoConfig,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetStamphogRepoConfigsAvailableRepositoryError = PosthogOpError;
/** List repositories from the project's connected GitHub installations that are not added to stamphog yet, so they can be added with add_repository. */
export const getStamphogRepoConfigsAvailableRepository: API.OperationMethod<
  GetStamphogRepoConfigsAvailableRepositoryRequest,
  StamphogAvailableRepositories,
  GetStamphogRepoConfigsAvailableRepositoryError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStamphogRepoConfigsAvailableRepositoryRequest,
  output: StamphogAvailableRepositories,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type GetStamphogReviewRunError = PosthogOpError;
/** History of stamphog review runs, filterable by repository, PR number, and status, plus manual review requests. */
export const getStamphogReviewRun: API.OperationMethod<
  GetStamphogReviewRunRequest,
  ReviewRun,
  GetStamphogReviewRunError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetStamphogReviewRunRequest,
  output: ReviewRun,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListStamphogDigestRunsError = PosthogOpError;
/** Read-only history of posted (or attempted) digests, filterable by Slack channel. */
export const listStamphogDigestRuns: API.OperationMethod<
  ListStamphogDigestRunsRequest,
  PaginatedDigestRunList,
  ListStamphogDigestRunsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStamphogDigestRunsRequest,
  output: PaginatedDigestRunList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListStamphogPullRequestsError = PosthogOpError;
/** Read-only pull requests stamphog knows about, filterable by PR number and merge state. */
export const listStamphogPullRequests: API.OperationMethod<
  ListStamphogPullRequestsRequest,
  PaginatedStamphogPullRequestList,
  ListStamphogPullRequestsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStamphogPullRequestsRequest,
  output: PaginatedStamphogPullRequestList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListStamphogRepoConfigsError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const listStamphogRepoConfigs: API.OperationMethod<
  ListStamphogRepoConfigsRequest,
  PaginatedStamphogRepoConfigList,
  ListStamphogRepoConfigsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStamphogRepoConfigsRequest,
  output: PaginatedStamphogRepoConfigList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type ListStamphogReviewRunsError = PosthogOpError;
/** History of stamphog review runs, filterable by repository, PR number, and status, plus manual review requests. */
export const listStamphogReviewRuns: API.OperationMethod<
  ListStamphogReviewRunsRequest,
  PaginatedReviewRunList,
  ListStamphogReviewRunsError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListStamphogReviewRunsRequest,
  output: PaginatedReviewRunList,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type StamphogRepoConfigsAddRepositoryCreateError = PosthogOpError;
/** Turn reviews on for a repository from the project's connected GitHub installations. Creates the repo config, or turns an existing one back on. Needs the editor level on stamphog. */
export const stamphogRepoConfigsAddRepositoryCreate: API.OperationMethod<
  StamphogRepoConfigsAddRepositoryCreateRequest,
  StamphogRepoConfig,
  StamphogRepoConfigsAddRepositoryCreateError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StamphogRepoConfigsAddRepositoryCreateRequest,
  output: StamphogRepoConfig,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type StamphogRepoConfigsDestroyError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const stamphogRepoConfigsDestroy: API.OperationMethod<
  StamphogRepoConfigsDestroyRequest,
  StamphogRepoConfigsDestroyResponse,
  StamphogRepoConfigsDestroyError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StamphogRepoConfigsDestroyRequest,
  output: StamphogRepoConfigsDestroyResponse,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type StamphogRepoConfigsInstallInfoRetrieveError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const stamphogRepoConfigsInstallInfoRetrieve: API.OperationMethod<
  StamphogRepoConfigsInstallInfoRetrieveRequest,
  StamphogInstallInfo,
  StamphogRepoConfigsInstallInfoRetrieveError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StamphogRepoConfigsInstallInfoRetrieveRequest,
  output: StamphogInstallInfo,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateStamphogRepoConfigError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const updateStamphogRepoConfig: API.OperationMethod<
  UpdateStamphogRepoConfigRequest,
  StamphogRepoConfig,
  UpdateStamphogRepoConfigError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateStamphogRepoConfigRequest,
  output: StamphogRepoConfig,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));

export type UpdateStamphogRepoConfigsPartialError = PosthogOpError;
/** Per-repo stamphog settings — enable/disable review, GitHub App installation, policy overrides. */
export const updateStamphogRepoConfigsPartial: API.OperationMethod<
  UpdateStamphogRepoConfigsPartialRequest,
  StamphogRepoConfig,
  UpdateStamphogRepoConfigsPartialError,
  PosthogOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateStamphogRepoConfigsPartialRequest,
  output: StamphogRepoConfig,
  errors: [],
  protocol: PosthogProtocol,
  retry: Retry.Retry,
}));
