import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-daytona/specs/{openapi,toolbox-openapi,analytics-openapi}.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownDaytonaError } from "../errors.ts";
import { DaytonaProtocol, type DaytonaOpError, type DaytonaOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { DaytonaOpError, DaytonaOpContext };

export interface GetSystemMetricsRequest {}
export const GetSystemMetricsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/system/metrics", code: 200 })),
).annotate({ identifier: "GetSystemMetricsRequest" }) as any as S.Schema<GetSystemMetricsRequest>;

export interface SystemMetrics {
  cpuCount?: number;
  cpuUsedPct?: number;
  diskFree?: number;
  diskTotal?: number;
  diskUsed?: number;
  memCache?: number;
  memTotal?: number;
  memUsed?: number;
  timestamp?: string;
  timestampUnix?: number;
}
export const SystemMetrics = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cpuCount: S.optional(S.Number),
    cpuUsedPct: S.optional(S.Number),
    diskFree: S.optional(S.Number),
    diskTotal: S.optional(S.Number),
    diskUsed: S.optional(S.Number),
    memCache: S.optional(S.Number),
    memTotal: S.optional(S.Number),
    memUsed: S.optional(S.Number),
    timestamp: S.optional(S.String),
    timestampUnix: S.optional(S.Number),
  }),
).annotate({ identifier: "SystemMetrics" }) as any as S.Schema<SystemMetrics>;

export type GetSystemMetricsError = DaytonaOpError;
/** Get sandbox resource metrics Latest CPU/memory/disk usage snapshot for the sandbox. cpuUsedPct is the average CPU usage as a percentage of the CPU limit over the last sample window (0 until the first sample completes). Byte fields are in bytes. */
export const getSystemMetrics: API.OperationMethod<
  GetSystemMetricsRequest,
  SystemMetrics,
  GetSystemMetricsError,
  DaytonaOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSystemMetricsRequest,
  output: SystemMetrics,
  errors: [UnknownDaytonaError],
  protocol: DaytonaProtocol,
  retry: Retry.Retry,
}));
