import * as API from "@distilled.cloud/core/api";
// AUTO-GENERATED by scripts/generate.ts from .generated-specs (specs/spec-mirror-daytona/specs/{openapi,toolbox-openapi,analytics-openapi}.json). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import { UnknownDaytonaError } from "../errors.ts";
import { DaytonaProtocol, type DaytonaOpError, type DaytonaOpContext } from "../protocol.ts";
import * as Retry from "../retry.ts";
import * as T from "../traits.ts";

export type { DaytonaOpError, DaytonaOpContext };

export interface CreateVolumeRequest {
  /** Use with JWT to specify the organization ID */
  xDaytonaOrganizationID?: string;
  name: string;
}
export const CreateVolumeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    xDaytonaOrganizationID: S.optional(S.String.pipe(T.Header("X-Daytona-Organization-ID"))),
    name: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/volumes", code: 200 })),
).annotate({ identifier: "CreateVolumeRequest" }) as any as S.Schema<CreateVolumeRequest>;

/** Volume state */
export type VolumeState =
  | "creating"
  | "ready"
  | "pending_create"
  | "pending_delete"
  | "deleting"
  | "deleted"
  | "error";
export const VolumeState = S.String;

export interface VolumeDto {
  /** Volume ID */
  id: string;
  /** Volume name */
  name: string;
  /** Organization ID */
  organizationId: string;
  /** Volume state */
  state: VolumeState;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** Last used timestamp */
  lastUsedAt?: string | null;
  /** The error reason of the volume */
  errorReason: string | null;
}
export const VolumeDto = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    organizationId: S.String,
    state: VolumeState,
    createdAt: S.String,
    updatedAt: S.String,
    lastUsedAt: S.optional(S.NullOr(S.String)),
    errorReason: S.NullOr(S.String),
  }),
).annotate({ identifier: "VolumeDto" }) as any as S.Schema<VolumeDto>;

export interface DeleteVolumeRequest {
  /** ID of the volume */
  volumeId: string;
  /** Use with JWT to specify the organization ID */
  xDaytonaOrganizationID?: string;
}
export const DeleteVolumeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeId: S.String.pipe(T.Label()),
    xDaytonaOrganizationID: S.optional(S.String.pipe(T.Header("X-Daytona-Organization-ID"))),
  }).pipe(T.Http({ method: "DELETE", uri: "/volumes/{volumeId}", code: 200 })),
).annotate({ identifier: "DeleteVolumeRequest" }) as any as S.Schema<DeleteVolumeRequest>;

export interface DeleteVolumeResponse {}
export const DeleteVolumeResponse = /*@__PURE__*/ S.suspend(() => S.Struct({})).annotate({
  identifier: "DeleteVolumeResponse",
}) as any as S.Schema<DeleteVolumeResponse>;

export interface GetVolumeRequest {
  /** ID of the volume */
  volumeId: string;
  /** Use with JWT to specify the organization ID */
  xDaytonaOrganizationID?: string;
}
export const GetVolumeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeId: S.String.pipe(T.Label()),
    xDaytonaOrganizationID: S.optional(S.String.pipe(T.Header("X-Daytona-Organization-ID"))),
  }).pipe(T.Http({ method: "GET", uri: "/volumes/{volumeId}", code: 200 })),
).annotate({ identifier: "GetVolumeRequest" }) as any as S.Schema<GetVolumeRequest>;

export interface GetVolumeByNameRequest {
  /** Name of the volume */
  name: string;
  /** Use with JWT to specify the organization ID */
  xDaytonaOrganizationID?: string;
}
export const GetVolumeByNameRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String.pipe(T.Label()),
    xDaytonaOrganizationID: S.optional(S.String.pipe(T.Header("X-Daytona-Organization-ID"))),
  }).pipe(T.Http({ method: "GET", uri: "/volumes/by-name/{name}", code: 200 })),
).annotate({ identifier: "GetVolumeByNameRequest" }) as any as S.Schema<GetVolumeByNameRequest>;

export interface ListVolumesRequest {
  /** Include deleted volumes in the response */
  includeDeleted?: boolean;
  /** Use with JWT to specify the organization ID */
  xDaytonaOrganizationID?: string;
}
export const ListVolumesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    includeDeleted: S.optional(S.Boolean.pipe(T.Query())),
    xDaytonaOrganizationID: S.optional(S.String.pipe(T.Header("X-Daytona-Organization-ID"))),
  }).pipe(T.Http({ method: "GET", uri: "/volumes", code: 200 })),
).annotate({ identifier: "ListVolumesRequest" }) as any as S.Schema<ListVolumesRequest>;

export type ListVolumesResponseBodyList = Array<VolumeDto>;
export const ListVolumesResponseBodyList = /*@__PURE__*/ S.Array(
  VolumeDto,
) as any as S.Schema<ListVolumesResponseBodyList>;

export type ListVolumesResponse = ListVolumesResponseBodyList;
export const ListVolumesResponse = /*@__PURE__*/ S.suspend(() =>
  ListVolumesResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({ identifier: "ListVolumesResponse" }) as any as S.Schema<ListVolumesResponse>;

export type CreateVolumeError = DaytonaOpError;
/** Create a new volume */
export const createVolume: API.OperationMethod<
  CreateVolumeRequest,
  VolumeDto,
  CreateVolumeError,
  DaytonaOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVolumeRequest,
  output: VolumeDto,
  errors: [UnknownDaytonaError],
  protocol: DaytonaProtocol,
  retry: Retry.Retry,
}));

export type DeleteVolumeError = DaytonaOpError;
/** Delete volume */
export const deleteVolume: API.OperationMethod<
  DeleteVolumeRequest,
  DeleteVolumeResponse,
  DeleteVolumeError,
  DaytonaOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteVolumeRequest,
  output: DeleteVolumeResponse,
  errors: [UnknownDaytonaError],
  protocol: DaytonaProtocol,
  retry: Retry.Retry,
}));

export type GetVolumeError = DaytonaOpError;
/** Get volume details */
export const getVolume: API.OperationMethod<
  GetVolumeRequest,
  VolumeDto,
  GetVolumeError,
  DaytonaOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVolumeRequest,
  output: VolumeDto,
  errors: [UnknownDaytonaError],
  protocol: DaytonaProtocol,
  retry: Retry.Retry,
}));

export type GetVolumeByNameError = DaytonaOpError;
/** Get volume details by name */
export const getVolumeByName: API.OperationMethod<
  GetVolumeByNameRequest,
  VolumeDto,
  GetVolumeByNameError,
  DaytonaOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVolumeByNameRequest,
  output: VolumeDto,
  errors: [UnknownDaytonaError],
  protocol: DaytonaProtocol,
  retry: Retry.Retry,
}));

export type ListVolumesError = DaytonaOpError;
/** List all volumes */
export const listVolumes: API.OperationMethod<
  ListVolumesRequest,
  ListVolumesResponse,
  ListVolumesError,
  DaytonaOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVolumesRequest,
  output: ListVolumesResponse,
  errors: [UnknownDaytonaError],
  protocol: DaytonaProtocol,
  retry: Retry.Retry,
}));
